"""Offline backing/exit evidence builder. Never calls a network or transacts.

Run: python3 tools/eth/backing_exit_build.py
Input captures live under raw/eth/research-closure-2026-10-04/exit.
Financial fields are copied once into an immutable scoped input, because the
main product chapter data may be regenerated by another researcher.
"""
from carry_economics_build import accrue, borrow_assets
import collections,csv,datetime as dt,hashlib,json,math,pathlib,statistics,sys,functools
from backing_exit_capture import ROOT,RAW,T,BLOCK,keccak

OUT=ROOT/'data/eth/backing_exit_closure.json'
def read(path):return json.loads(path.read_text())
def saved(name):
    p=RAW/(name+'_repaired.json')
    return read(p if p.exists() else RAW/(name+'.json'))
def records(name):return {r['label']:r for r in saved(name)['records']}
def result(rows,label):return rows.get(label,{}).get('response',{}).get('result')
def number(rows,label,dec=18):
    s=result(rows,label)
    return int(s,16)/10**dec if s not in[None,'0x']else None
def words(s):return [int(s[i:i+64],16)for i in range(2,len(s),64)]
@functools.lru_cache(None)
def topic(sig):return '0x'+keccak(sig.encode()).hex()
def addr(word):return '0x'+word[-40:].lower()
def log_order(log):return int(log['blockNumber'],16),int(log['logIndex'],16)
def logs(name):return sorted([x for r in saved(name+'_exitlogs_T')['records']for x in r['response'].get('result',[])],key=lambda x:(int(x['blockNumber'],16),int(x['logIndex'],16)))
def utc(t):return dt.datetime.fromtimestamp(t,dt.timezone.utc).isoformat()
def waits(xs):
    if not xs:return {'observations':0,'median':None,'p90':None,'max':None}
    ys=sorted(xs);return {'observations':len(ys),'median':statistics.median(xs),'p90':ys[math.ceil(.9*len(ys))-1],'max':max(xs),'min':min(xs)}

def cash_receipts(name):
    rr=records(name+'_payout_receipts');out={};count=0
    for tx,r in rr.items():
        receipt=r['response'].get('result')
        if not receipt:continue
        if int(receipt.get('status','0x0'),16)!=1:continue
        count+=1; transfers=collections.Counter()
        for log in receipt.get('logs',[]):
            if len(log.get('topics',[]))==3 and log['topics'][0]==topic('Transfer(address,address,uint256)'):
                transfers[(log['address'].lower(),addr(log['topics'][2]),int(log['data'],16))]+=1
        out[tx]=transfers
    return out,count,len(rr)

def liquid_history():
    ls=logs('liquid_queue');req={};solved=[];cancels=[];assets=collections.defaultdict(int);matched=0;hours=[];examples=[]
    receipts,receiptcount,receiptattempts=cash_receipts('liquid_queue')
    for l in ls:
        if l['topics'][0]==topic('OnChainWithdrawRequested(bytes32,address,address,uint96,uint128,uint128,uint40,uint24,uint24)'):
            w=words(l['data']);req[l['topics'][1]]={'id':l['topics'][1],'user':addr(l['topics'][2]),'asset':addr(l['topics'][3]),'sharesRaw':w[1],'assetsRaw':w[2],'creation':w[3],'maturitySeconds':w[4],'deadlineSeconds':w[5],'requestTransaction':l['transactionHash']}
        elif l['topics'][0]==topic('OnChainWithdrawSolved(bytes32,address,uint256)'):solved.append(l)
        elif l['topics'][0]==topic('OnChainWithdrawCancelled(bytes32,address,uint256)'):cancels.append(l)
    missing=[]
    for l in solved:
        x=req.get(l['topics'][1]);
        if not x:missing.append(l['topics'][1]);continue
        paid=receipts.get(l['transactionHash'],collections.Counter());key=(x['asset'],x['user'],x['assetsRaw'])
        confirmed=paid[key]>0
        if confirmed:paid[key]-=1;matched+=1
        when=int(l['data'],16);wait=(when-x['creation'])/3600;hours.append(wait);assets[x['asset']]+=x['assetsRaw']
        if len(examples)<3 or wait>max(e['waitHours']for e in examples):
            examples.append({'requestId':x['id'],'user':x['user'],'asset':x['asset'],'paidNative':x['assetsRaw']/1e18,'requestUTC':utc(x['creation']),'paidUTC':utc(when),'waitHours':wait,'requestTransaction':x['requestTransaction'],'claimTransaction':l['transactionHash'],'tokenTransferVerified':confirmed})
            examples=sorted(examples,key=lambda e:e['waitHours'])[:2]+[max(examples,key=lambda e:e['waitHours'])]
    return {'coverage':'Ethereum BoringOnChainQueue, blocks 20000000 through T; every requested interval returned successfully. Optimism and older predecessor queues are outside this census.','requestCount':len(req),'fulfilledCount':len(solved),'cancelledCount':len(cancels),'pendingCount':len(req)-len(solved)-len(cancels),'receiptVerifiedCount':matched,'receiptTransactionCount':receiptcount,'receiptTransactionsAttempted':receiptattempts,'totalPaidByAsset':[{'asset':a,'nativeAmount':n/1e18,'unit':'weETH' if a=='0xcd5fe23c85820f7b72d0926fc9b05b43e359b7ee'else'WETH' if a=='0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'else'eETH' if a=='0x35fa164735182de50811e8e2e824cfb9b6118ac2' else 'ERC20, 18-decimal assumption'}for a,n in assets.items()],'waitHours':waits(hours),'examples':examples,'unmatchedRequestIds':missing,'assetMetadataBasis':'Payout contracts are eETH 0x35fa164735182de50811e8e2e824cfb9b6118ac2 and weETH 0xcd5fe23c85820f7b72d0926fc9b05b43e359b7ee. eETH decimals=18 is captured in remaining_known_claims_T.json; weETH metadata is retained with backing_token_balances_T.json. Native quantities are not historical USD proceeds.','waitScope':'Completed requests only. Cancelled/pending requests are excluded, so these waits do not estimate the probability or time of every new exit.','sourcePaths':[str(RAW.relative_to(ROOT)/'liquid_queue_exitlogs_T.json'),str(RAW.relative_to(ROOT)/'liquid_queue_payout_receipts_repaired.json'),str(RAW.relative_to(ROOT)/'remaining_known_claims_T.json')]}

def vault_history(name,unit,token):
    ls=logs(name);withdraws=[x for x in ls if x['topics'][0]==topic('Withdraw(address,address,address,uint256,uint256)')]
    receipts,receiptcount,receiptattempts=cash_receipts(name)if withdraws else ({},0,0)
    matched=0;paid=0;examples=[]
    for l in withdraws:
        w=words(l['data']);key=(token,addr(l['topics'][2]),w[0]);r=receipts.get(l['transactionHash'],collections.Counter());ok=r[key]>0
        if ok:matched+=1;r[key]-=1
        paid+=w[0]
        if len(examples)<3:examples.append({'claimTransaction':l['transactionHash'],'block':int(l['blockNumber'],16),'receiver':key[1],'paidNative':w[0]/1e18,'unit':unit,'tokenTransferVerified':ok})
    census=saved(name+'_exitlogs_T')
    h={'coverage':f"Ethereum vault logs, blocks {census['fromBlock']} through {census['toBlock']} (T); every requested interval returned successfully.",'requestCount':sum(l['topics'][0]==topic('QueuedWithdrawal(address,address,address,uint256,uint256,uint256)')for l in ls),'fulfilledCount':len(withdraws),'receiptVerifiedCount':matched,'receiptTransactionCount':receiptcount,'receiptTransactionsAttempted':receiptattempts,'totalPaidNative':paid/1e18,'nativeUnit':unit,'waitHours':waits([]),'examples':examples,'sourcePaths':[str(RAW.relative_to(ROOT)/(name+'_exitlogs_T.json'))]}
    if withdraws:h['sourcePaths'].append(str(RAW.relative_to(ROOT)/(name+'_payout_receipts_repaired.json')))
    if name=='rocksolid':
        headers={int(k):int(r['response']['result']['timestamp'],16)for k,r in records('rocksolid_exit_block_headers').items()if r['response'].get('result')}
        requests=[x for x in ls if x['topics'][0]==topic('RedeemRequest(address,address,uint256,address,uint256)')];settles=[x for x in ls if x['topics'][0]==topic('SettleRedeem(uint40,uint40,uint256,uint256,uint256,uint256)')]
        wait=[];claimwait=[];last={};unpaired=0;examples=[];ordering_violations=[];paired_settlements=[]
        for l in ls:
            if l['topics'][0]==topic('RedeemRequest(address,address,uint256,address,uint256)'):
                user=addr(l['topics'][1]);last.setdefault(user,[]).append(l)
                sid=int(l['topics'][3],16);s=next((s for s in settles if log_order(s)>log_order(l) and int(s['topics'][1],16)>=sid),None)
                if s and int(l['blockNumber'],16)in headers and int(s['blockNumber'],16)in headers:wait.append((headers[int(s['blockNumber'],16)]-headers[int(l['blockNumber'],16)])/3600)
            elif l['topics'][0]==topic('Withdraw(address,address,address,uint256,uint256)'):
                owner=addr(l['topics'][3]);pending=last.get(owner,[]);shares=words(l['data'])[1]
                if len(pending)==1 and words(pending[0]['data'])[1]==shares:
                    q=pending[0];b=int(l['blockNumber'],16);qb=int(q['blockNumber'],16)
                    if b in headers and qb in headers:
                        elapsed=(headers[b]-headers[qb])/3600;claimwait.append(elapsed)
                        settlement=next((x for x in settles if log_order(x)>log_order(q) and int(x['topics'][1],16)>=int(q['topics'][3],16)),None)
                        if settlement:
                            sb=int(settlement['blockNumber'],16)
                            if log_order(settlement)>log_order(l):ordering_violations.append({'request':q['transactionHash'],'settlement':settlement['transactionHash'],'cash':l['transactionHash']})
                            else:paired_settlements.append((headers[sb]-headers[qb])/3600)
                        examples.append({'requestTransaction':q['transactionHash'],'claimTransaction':l['transactionHash'],'requestUTC':utc(headers[qb]),'paidUTC':utc(headers[b]),'waitHours':elapsed,'requestId':int(q['topics'][3],16),'paidNative':words(l['data'])[0]/1e18,'unit':unit,'tokenTransferVerified':True,'matchBasis':'One preceding unmatched request for controller, exact requested/claimed share quantity.'})
                    last[owner]=[]
                else:unpaired+=1;last[owner]=[]
        h.update(requestCount=len(requests),settlementCount=len(settles),requestToSettlementHours=waits(wait),matchedCashRequestToSettlementHours=waits(paired_settlements),orderingInvariant={'uniquelyMatchedCashClaims':len(claimwait),'settlementFound':len(paired_settlements),'settlementBeforeOrAtCash':len(ordering_violations)==0,'orderBasis':'Block number and log index: request < covering settled epoch <= cash payout. SettleRedeem topic[1] is the settled redeem epoch; topic[2] is its internal settlement ID.','violations':ordering_violations},waitHours=waits(claimwait),cashWaitUnpairedClaims=unpaired,examples=sorted(examples,key=lambda e:e['waitHours'])[:2]+sorted(examples,key=lambda e:e['waitHours'])[-1:],waitScope='Cash waits use only uniquely matched controller requests with exact share quantities. Settlement waits measure when assets became claimable, not when users collected them.')
        h['sourcePaths'].extend([str(RAW.relative_to(ROOT)/'rocksolid_exit_block_headers_repaired.json'),'raw/eth/2026-10-04/strict-products/rocksolid_impl.json'])
    return h

def build():
    frozen=RAW/'financial_inputs_frozen_T.json'
    if not frozen.exists():
        old=read(ROOT/'data/eth/product_chapters.json')
        frozen.write_text(json.dumps({'snapshot':old['snapshot'],'products':[{'id':x['id'],'name':x['name'],'bookNAV_ETH':x['capitalETH'],'bookNAV_USD':x['capitalUSD']}for x in old['products']]},indent=2))
    inp=read(frozen);ps=inp['products'];withdraw=records('withdraw_simulations_T');req=records('request_and_claim_simulations_T');bal=records('backing_token_balances_T')
    price=ps[0]['bookNAV_USD']/ps[0]['bookNAV_ETH'];ethrates={'concrete':1.1049430338706405,'liquid':1,'rocksolid':ps[2]['bookNAV_ETH']/number(withdraw,'rocksolid_totalAssets()'),'liquity':1,'royco':1.2454018786985979}
    units={'concrete':'weETH','liquid':'ETH book NAV','rocksolid':'rETH','liquity':'WETH','royco':'wstETH'}
    histories={'liquid':liquid_history(),'rocksolid':vault_history('rocksolid','rETH','0xae78736cd615f374d3085123a210448e74fc6393'),'liquity':vault_history('liquity','WETH','0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'),'concrete':vault_history('concrete','weETH','0xcd5fe23c85820f7b72d0926fc9b05b43e359b7ee'),'royco':vault_history('royco','wstETH','0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0')}
    for p in ps:
        id=p['id'];p['nativeUnit']=units[id];p['nativeBookNAV']=p['bookNAV_ETH']/ethrates[id];p['demandScenarios']=[]
        for pct in [1,10,30]:
            sim=withdraw.get(id+'_withdraw_'+str(pct)+'pct');response=sim['response']if sim else None
            request= id=='concrete' and bool(response and 'result'in response)
            immediate=id=='liquity' and bool(response and 'result'in response)
            reason={'concrete':'Successful eth_call enters active epoch queue and transfers vault shares into escrow. It does not transfer weETH to the receiver.','liquid':'Ordinary holder direct exit is unauthorized. Queue request requires share allowance; aggregate demand exceeds individual holder capacity at larger sizes and was not simulated as a portfolio unwind.','rocksolid':'New request simulation reverts NotOpen(Closing). Holder has no claimable redemption assets at T.','royco':'ERC4626 withdrawal simulation reverts because maximum immediate withdrawal is zero.','liquity':'The 1% holder withdrawal succeeds. The 10% and 30% calls revert on the configured withdrawal path despite sufficient holder shares.'}[id]
            p['demandScenarios'].append({'navPct':pct,'denominator':'Whole product ETH book NAV at T; Liquid combines Ethereum and Optimism circulating shares. Native calls are on Ethereum only.','nativeAmount':p['nativeBookNAV']*pct/100,'nativeUnit':units[id],'ETH':p['bookNAV_ETH']*pct/100,'USD':p['bookNAV_USD']*pct/100,'simulatedRequest':request if id!='liquid' else None,'simulatedImmediatePayout':immediate if id!='liquid' else None,'successfulWithdrawalSimulation':immediate,'simulationStatus':('not tested as aggregate withdrawal' if id=='liquid' else 'queue request succeeds' if request else 'withdrawal simulation succeeds' if immediate else 'withdrawal simulation reverts'),'reason':reason,'response':response,'withdrawalCall':{'method':sim['method'],'params':sim['params'],'response':response} if sim else None,'requestCall':req.get('rock_request_'+str(pct)+'pct') if id=='rocksolid' else None,'capturePath':str(RAW.relative_to(ROOT)/'withdraw_simulations_T.json')})
        p['historicalExits']=histories[id];p['controlsClosure']={};p['limitations']=[]
    liquid=next(p for p in ps if p['id']=='liquid');b=read(ROOT/'data/eth/etherfi_partial_balance_sheet.json')
    liquid['backing']={'lines':b['lines'],'reconstructedUSD':b['partial_reconstruction_usd'],'residualUSD':b['unresolved_residual_usd'],'residualPct':b['unresolved_residual_pct'],'attributionScope':'Existing mixed-price position reconstruction, including nested book claims. This is not independently audited physical backing.','unattributedBounds':{'nestedMonadBookUSD':21687133.565276448,'nestedMonadRemoteMatchedClaimUSD':None,'residualIsDeficit':False},'newFindings':['The large SPARK balance is an unrelated token named 星火通证, not official SPK. No price was found for that exact token. SPK pricing cannot close this residual.'],'sourcePaths':['data/eth/etherfi_partial_balance_sheet.json']}
    concrete=next(p for p in ps if p['id']=='concrete');aave=397716388.0866408
    s0=number(bal,'concrete_s0xUSD')*number(bal,'s0xUSD_convertToAssets(uint256)');ct=number(bal,'concrete_ctDefiUSDT',6)*number(bal,'ctDefiUSDT_convertToAssets(uint256)',18)
    # convertToAssets(1e18) for a six-decimal receipt returns six-decimal assets:
    # dividing returned value by 1e18 yields the native asset per native share.
    direct=number(bal,'concrete_THUSD',6)+number(bal,'concrete_PYUSD',6)+number(bal,'concrete_USDS')+number(bal,'concrete_WEETH')*ethrates['concrete']*price+number(bal,'concrete_USDC',6)
    visible=aave+direct+s0+ct
    concrete['backing']={'lines':[{'name':'Shared Safe Aave net equity','USD':aave,'basis':'Aave collateral less debt, protocol oracle USD'},{'name':'Direct shared Safe assets','USD':direct,'basis':'weETH standardized quote; THUSD, PYUSD, USDS and USDC at nominal $1'},{'name':'s0xUSD nested book claim','USD':s0,'basis':'convertToAssets at T; 0xUSD nominal $1, not verified cash redemption'},{'name':'ctDefiUSDT nested book claim','USD':ct,'basis':'convertToAssets at T; USDT nominal $1, custody attribution requires a separate look-through'},{'name':'ctwstETH+ internal receipt eliminated','USD':0,'basis':'Shared Safe owns 100% of sibling shares and custody is the same Safe. No second asset is created by that claim.'}],'reconstructedUSD':visible,'residualUSD':concrete['bookNAV_USD']-visible,'residualPct':100*(concrete['bookNAV_USD']-visible)/concrete['bookNAV_USD'],'attributionScope':'Visible shared Safe assets and nested book claims. Beneficial assignment to Delta is not independently established.','unattributedBounds':{'attributableVisibleToDeltaLowerUSD':0,'attributableVisibleToDeltaUpperUSD':visible,'minimumDeltaBookUnmappedToCapturedSharedAssetsUSD':max(0,concrete['bookNAV_USD']-visible),'boundScope':'Upper bound grants Delta every captured visible asset, including conditional nested receipt values. No assertion of insolvency or legal ownership.'},'sourcePaths':['data/eth/concrete_lookthrough_T.json',str(RAW.relative_to(ROOT)/'backing_token_balances_T.json')]}
    royco=next(p for p in ps if p['id']=='royco');auth=records('royco_authority_active_T')
    royco['controlsClosure']={'machineBeacon':'0x5c680ec39bafe8524f3c2fa9d5f6d65f09bd7333','machineImplementationAtT':'0x6a759cae19aa25b41237089eb0bbbc4473bfb996','caliberBeacon':'0x3f5a881db86d6f495823028a1e892e7b2cd7e162','caliberImplementationAtT':'0xe5504cf018e67be842b0e6f738d9a32230c05ec3','riskManager':'0x82eece4a736db0767370d2dffde9bdf6e38aaeb8','riskManagerType':'RoycoAccessManager','configuredInstructionRootDelaySeconds':172800,'durationChangeRole':'14149459376679876623','durationChangeController':'0x84d37a25e46029ce161111420e07ceb78880119e','controllerType':'3-of-4 Safe','durationChangeExecutionDelaySeconds':259200,'unscheduledExecuteReverts':bool(auth['duration_controller_execute_without_schedule']['response'].get('error')),'limits':'This establishes the mapped duration-changing role and its active execution delay at T. It does not establish an immutable delay or audit every governance/admin/module path.'}
    for name in ['machine','caliber']:
        code=result(auth,name+'_implementation_code_T');source=next(RAW.glob(name+'_implementation_verified_T-*.json'));published=read(source)['deployed_bytecode']
        royco['controlsClosure'][name+'ImplementationBinding']={'codeSHA256':hashlib.sha256(bytes.fromhex(code[2:])).hexdigest(),'exactMatchToVerifiedSourceDeployedBytecode':code.lower()==published.lower(),'sourcePath':str(source.relative_to(ROOT))}
    sr=number(bal,'royco_srUSDC_balanceOf(address)',6)*number(bal,'royco_srUSDC_convertToAssets(uint256)',18);cash=.10674117289575942*ethrates['royco']*price
    royco['backing']={'lines':[{'name':'Caliber loose wstETH','USD':cash,'basis':'Fixed-block balance; not freely distributable by wrapper holder'},{'name':'srRoyUSDC nested book claim','USD':sr,'basis':'Fixed-block convertToAssets, USDC nominal $1; separate senior wrapper exit not simulated'}],'reconstructedUSD':cash+sr,'residualUSD':royco['bookNAV_USD']-cash-sr,'residualPct':100*(royco['bookNAV_USD']-cash-sr)/royco['bookNAV_USD'],'attributionScope':'Only loose cash and one identified senior vault token. Loan collateral and debt instructions remain outside this partial figure; subtracting their cached values would not create independently proven fresh backing.','unattributedBounds':{'cashOnlyUSD':cash,'conditionalNestedClaimUSD':sr},'sourcePaths':[str(RAW.relative_to(ROOT)/'royco_authority_initial_T.json'),str(RAW.relative_to(ROOT)/'backing_token_balances_T.json')]}
    strict_snapshot=read(ROOT/'raw/eth/2026-10-04/strict-products/snapshot_rpc.json')['records']
    liquity_share_rate=int(next(x['response']['result']for x in strict_snapshot if x['product']=='liquity' and x['signature']=='convertToAssets(uint256)'),16)/1e18
    rock=next(p for p in ps if p['id']=='rocksolid');nested=number(bal,'rocksolid_rETHLPC',20)*liquity_share_rate*price;idle=number(bal,'rocksolid_RETH')*ethrates['rocksolid']*price+number(bal,'rocksolid_WEETH')*1.1049430338706405*price+number(bal,'rocksolid_USDT',6)
    rock['backing']={'lines':[{'name':'Loose rETH, weETH and USDT in execution wallet','USD':idle,'basis':'Fixed-block balances; standardized T rates and nominal $1 USDT'},{'name':'Liquity ETH Carry receipt','USD':nested,'basis':'20-decimal receipt quantity times fixed-block convertToAssets(1e20) rate. Nested whole-vault book claim, not separately identified carry-only exposure.'}],'reconstructedUSD':idle+nested,'residualUSD':rock['bookNAV_USD']-idle-nested,'residualPct':100*(rock['bookNAV_USD']-idle-nested)/rock['bookNAV_USD'],'attributionScope':'Identified cash and one nested receipt only. Spark debt/collateral and Balancer/gauge receipts remain outside this deliberately incomplete reconstruction.','unattributedBounds':{},'sourcePaths':[str(RAW.relative_to(ROOT)/'backing_token_balances_T.json'),'raw/eth/2026-10-04/strict-products/snapshot_rpc.json']}
    rock['controlsClosure']={'snapshotState':'Closing','stateEnumValue':1,'newRedemptionRequestsAtT':'Rejected with NotOpen(1)','stateTransitionTransaction':'0xb3ed2719618ec664e52d904c4f65eb9dcbbddd7ff1ae5c5599148bbadf23b70a','stateTransitionBlock':26080189,'interpretation':'Verified Lagoon implementation uses initiateClosing -> close. Closing is distinct from ordinary settleRedeem. This observation does not assert economic failure or future permanent deprecation.','bindingScope':'T implementation and exact transition timestamp are separately captured in final_controls_and_substrates_T when available.'}
    binding=records('rocksolid_implementation_binding_T')
    code=result(binding,'rock_implementation_code_T');verified=read(ROOT/'raw/eth/2026-10-04/strict-products/rocksolid_impl.json')['deployed_bytecode']
    header=binding['rock_closing_header']['response'].get('result')
    rock['controlsClosure'].update(implementationAtT='0xe50554ec802375c9c3f9c087a8a7bb8c26d3dedf',implementationSlot=result(binding,'rock_implementation_slot_T'),codeSHA256=hashlib.sha256(bytes.fromhex(code[2:])).hexdigest(),exactMatchToVerifiedSourceDeployedBytecode=code.lower()==verified.lower(),stateTransitionUTC=utc(int(header['timestamp'],16)),stateTransitionCaller=binding['rock_closing_tx']['response']['result']['from'],stateTransitionFunction='initiateClosing()',postTScope='Separate document review observation, 4 October 2026. No later StateUpdated event returned through the captured latest block.',postTStateTransitionCount=len(binding['rock_state_events_after_T']['response'].get('result',[])))
    rock['controlsClosure']['bindingScope']='Fixed-block EIP1967 implementation slot and runtime bytecode exactly match the verified implementation. Full pre-T StateUpdated event history retained.'
    monad=records('monad_token_claims_T');monoexit=records('monad_steak_exit_T');m=number(monoexit,'steak_claim');w=number(monad,'monad_0x10aeaf63194db8d453d4d85a06e5efe1dd0b5417_balanceOf(address)');usdc=number(monad,'monad_0x754704bc059f8c67012fed69bc8a327a5aafb603_balanceOf(address)',6)
    marked=(m+w*1.2454018786985979)*price+usdc
    liquid['backing']['unattributedBounds'].update(nestedMonadRemoteMatchedClaimUSD=marked,nestedMonadBookLessCapturedRemoteClaimsUSD=21687133.565276448-marked,boundScope='Known remote SteakETH book claim and wstETH/USDC balances only. Wrapped MON is identified but unpriced; Ethereum-local assets, undiscovered claims and liabilities have not been fully reconstructed. The difference is a scope residual, not a deficit.')
    liquid['backing']['nestedMonad']={'SteakETHShares':number(monad,'monad_0xbeef04b01e0275d4ac2e2986256bb14e3ff6ef42_balanceOf(address)'),'SteakClaimWETH':m,'looseWstETH':w,'looseUSDC':usdc,'looseWMON':number(monad,'monad_0x3bd359c1119da7da1d913d1c4d2b7c461115433a_balanceOf(address)'),'SteakMaxWithdrawGetterWETH':number(monoexit,'steak_maxWithdraw'),'oneWETHWithdrawalSimulation':monoexit['steak_withdraw_1WETH'],'exitLimit':'maxWithdraw reports zero while a one-WETH withdraw eth_call returns successfully. No simulated transfer trace or T implementation binding is available for this nested receipt, so a successful return is not promoted to proven cash liquidity.','sourcePaths':[str(RAW.relative_to(ROOT)/'monad_token_claims_T.json'),str(RAW.relative_to(ROOT)/'monad_steak_exit_T.json')]}
    liq=next(p for p in ps if p['id']=='liquity');coll=5710.7680883631965*price;debt=6752064.750858128;cash=300.6784334440505*price+1.907946529788722;lp=59.732893164148294*price;partial=coll-debt+cash+lp
    liq['backing']={'lines':[{'name':'Ebisu collateral less ebUSD debt','USD':coll-debt,'basis':'wstETH standardized T rate, debt at nominal $1 ebUSD; this differs from the branch oracle mark'},{'name':'Loose WETH and ebUSD','USD':cash,'basis':'Fixed-block balances; ebUSD nominal $1'},{'name':'Stored Uniswap V4 market book','USD':lp,'basis':'Stored market value, not independently reconstructed pool claim'}],'reconstructedUSD':partial,'residualUSD':liq['bookNAV_USD']-partial,'residualPct':100*(liq['bookNAV_USD']-partial)/liq['bookNAV_USD'],'attributionScope':'Partial positions plus one cached market. Active substrate inventory and other cached markets do not yet independently reconcile totalAssets.','unattributedBounds':{},'sourcePaths':['raw/eth/2026-10-04/strict-products/trove_final_rpc.json','raw/eth/2026-10-04/strict-products/liquity_wallet_T.json','raw/eth/2026-10-04/strict-products/market_controls_rpc.json']}
    known=records('known_nested_claims_T');pool=records('explicit_pool_claims_T');remaining=records('remaining_known_claims_T')
    # Fresh Morpho position binding comes from the last actual Caliber accounting
    # instruction calldata. No cached position ID is guessed into a venue.
    mstate=words(result(remaining,'royco_morpho_market'));mpos=words(result(remaining,'royco_morpho_position'));mparams=words(result(remaining,'royco_morpho_params'));maccrual=records('royco_morpho_accrual_T');rr=int(result(maccrual,'borrow_rate'),16)
    blockts=1790985599;mint=accrue(mstate,rr,blockts);debt=borrow_assets(mpos[1],mstate[2]+mint,mstate[3])/1e6;coll=mpos[2]/1e18*ethrates['royco']*price;royco_cash=.10674117289575942*ethrates['royco']*price;loosePY=.055764926188024165*ethrates['royco']*price
    royco['backing']['lines']=[{'name':'Morpho wstETH collateral','USD':coll,'basis':'Actual T collateral quantity, standardized wstETH/ETH rate and T+1-second ETH quote'},{'name':'Morpho PYUSD debt','USD':-debt,'basis':'T borrow shares plus Morpho pending interest accrued to block timestamp; PYUSD nominal $1'},{'name':'srRoyUSDC senior receipt','USD':sr,'basis':'T convertToAssets book claim, USDC nominal $1; backing of underlying senior-credit system not independently audited'},{'name':'Loose wstETH','USD':royco_cash,'basis':'Actual Caliber cash quantity, standardized price'},{'name':'PYUSD base-token accounting value','USD':loosePY,'basis':'Captured getDetailedAum accounting-token value, repriced with standardized wstETH rate. Not an independently decoded physical PYUSD balance.'}]
    total=coll-debt+sr+royco_cash+loosePY
    royco['backing'].update(reconstructedUSD=total,residualUSD=royco['bookNAV_USD']-total,residualPct=100*(royco['bookNAV_USD']-total)/royco['bookNAV_USD'],attributionScope='Fresh Morpho collateral/debt and an identified senior receipt replace stale Caliber position values. Standardized asset quotes and nominal-dollar assumptions can differ from the parent cached AUM. Senior vault book value remains a nested credit claim.')
    txrows=records('royco_accounting_transactions');lasttx=max((x['response']['result']for x in txrows.values()if x['response'].get('result') and x['response']['result']['input'].startswith('0xe3ee963b')),key=lambda x:int(x['blockNumber'],16))
    royco['liveLoan']={'venue':'Morpho Blue','chain':'Ethereum','marketId':'0xf5c5df23559b0fb56560a7578ea17d81e245153ba64b8132df026c9358864d27','collateral':'wstETH','debt':'PYUSD','collateralQuantity':mpos[2]/1e18,'accruedDebtPYUSD':debt,'storedDebtPYUSD':borrow_assets(mpos[1],mstate[2],mstate[3])/1e6,'borrowAPR':rr/1e18*31536000,'destinationClaim':'srRoyUSDC','destinationClaimUSD':sr,'instructionTransaction':lasttx['hash'],'instructionBlock':int(lasttx['blockNumber'],16),'causalityLimit':'The actual accounting instructions bind both the collateral/debt market and senior receipt. This does not by itself trace every borrowed PYUSD unit through swaps into the USDC receipt.'}
    royco['cachedAccountingScope']={'isAccountingFresh':False,'getNetAum':'reverts PositionAccountingStale','freshPositionReads':'Morpho loan and senior token re-read independently at T; stored Caliber position values are not treated as fresh.'}
    # Spark account collateral already includes sprETH. Do not add sprETH a
    # second time. Variable-debt tokens are also not additional liabilities.
    spark=words(result(known,'rock_spark_account'));sparkeq=(spark[0]-spark[1])/1e8
    live=words(result(known,'rock_pool_getCurrentLiveBalances()'))[2:];pool_supply=number(known,'rock_pool_totalSupply()');gaugeheld=number(bal,'rocksolid_rETH-waEthWETH-gauge');unstaked=number(bal,'rocksolid_rETH-waEthWETH');bpt=(gaugeheld+unstaked)/pool_supply*sum(live)/1e18*price
    ownedlt=number(known,'rock_yield_gauge_convertToAssets(uint256)');lt=ownedlt*number(remaining,'rock_yb_pricePerShare()')*price;native=number(bal,'rocksolid_native_ETH')*price
    rock['backing']['lines'].extend([{'name':'Spark net equity','USD':sparkeq,'basis':'Protocol USD collateral less debt. sprETH receipt and variable-debt token already represented here, not added again.'},{'name':'Balancer V3 pool claim via gauge and tiny unstaked BPT','USD':bpt,'basis':'Pro-rata getCurrentLiveBalances, already rate-adjusted to 18-decimal ETH units; held gauge receipt maps to BPT and gauge BPT custody equals gauge totalSupply at T.'},{'name':'YieldBasis WETH LT claim through gauge','USD':lt,'basis':'Gauge convertToAssets -> LT shares -> LT pricePerShare in WETH. A nested contract book mark, not a cash-exit guarantee.'},{'name':'Execution-wallet native ETH','USD':native,'basis':'Actual eth_getBalance at T'}])
    total=idle+nested+sparkeq+bpt+lt+native
    rock['backing'].update(reconstructedUSD=total,residualUSD=rock['bookNAV_USD']-total,residualPct=100*(rock['bookNAV_USD']-total)/rock['bookNAV_USD'],attributionScope='Known Ethereum execution-wallet cash, Spark net equity, Balancer principal and YieldBasis/nested-vault book claims. Remaining book value has no attributable position in this bounded public inventory; this is not a proven shortfall.')
    rock['exitReserve']={'vaultHeldReth':number(remaining,'rock_vault_rETH'),'scope':'Vault-held rETH is shown separately from the execution-wallet managed subtotal because settled redemption reserves can already have been removed from totalAssets. Beneficial reserve attribution is not independently reconstructed.'}
    cb=words(result(pool,'curve_get_balances()'))[2:];cs=number(pool,'curve_totalSupply()');cg=number(pool,'curve_gauge_balanceOf(address)');dust=number(known,'liquity_substrate_0xefc6516323fbd28e80b85a497b65a86243a54b3e_balanceOf(address)');curve=(cg+dust)/cs*(cb[0]/1e18+cb[1]/1e6)
    liq['backing']['lines'].append({'name':'Curve ebUSD/USDC LP via gauge plus tiny direct receipt','USD':curve,'basis':'Pro-rata fixed-block underlying balances; both stablecoins at nominal $1. Legacy BOLDUSDC symbol does not identify the actual coins.'})
    total=partial+curve;liq['backing'].update(reconstructedUSD=total,residualUSD=liq['bookNAV_USD']-total,residualPct=100*(liq['bookNAV_USD']-total)/liq['bookNAV_USD'],attributionScope='Ebisu collateral less debt, loose cash, Curve ebUSD/USDC principal and the stored Uniswap V4 market book. Different protocol/book prices and uncollected fees remain unreconciled. Fresh accounting update simulations from holder and atomist both lack permission, so stored market marks were not promoted to refreshed values.')
    liq['liveDestination']={'venue':'Curve','chain':'Ethereum','pool':'0xefc6516323fbd28e80b85a497b65a86243a54b3e','gauge':'0x07a01471fa544d9c6531b631e6a96a79a9ad05e9','coin0':'ebUSD','coin0Address':'0x6440f144b7e50d6a8439336510312d2f54beb01d','coin1':'USDC','coin1Address':'0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48','LPBookPrincipalUSD':curve,'causalityLimit':'The Ebisu debt currency and pool coin are verified; exact historical use of each borrowed unit has not been fully transaction-traced.'}
    local=number(remaining,'monad_Ethereum_local_0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2')*price
    liquid['backing']['nestedMonad']['EthereumLocalWETH']=local/price
    matched=marked+local;liquid['backing']['unattributedBounds'].update(nestedMonadCapturedEthereumAndRemoteClaimsUSD=matched,nestedMonadBookLessCapturedClaimsUSD=21687133.565276448-matched)
    liquid['backing']['nestedReceiptReplacementReconstructionUSD']=b['partial_reconstruction_usd']-21687133.565276448+matched
    liquid['backing']['nestedReceiptReplacementResidualUSD']=liquid['bookNAV_USD']-liquid['backing']['nestedReceiptReplacementReconstructionUSD']
    steak_raw=int(result(monad,'monad_0xbeef04b01e0275d4ac2e2986256bb14e3ff6ef42_balanceOf(address)'),16)
    steak_input=int(monoexit['steak_claim']['params'][0]['data'][10:],16)
    liquid['backing']['nestedMonad'].update(SteakCapturedSharesRaw=str(steak_raw),SteakValuationInputSharesRaw=str(steak_input),valuationPrecisionScope='The captured convertToAssets input is 348672 share wei above the exact balance, less than 0.000000000001 share. The quoted subtotal is rounded to cents; this input difference is worth less than $0.00000001 at the stated mark.')
    royco['backing']['excludingUndecodedPYUSDAccountingValue']={'reconstructedUSD':royco['backing']['reconstructedUSD']-loosePY,'residualUSD':royco['backing']['residualUSD']+loosePY,'scope':'Excludes the $185.28847476663583 base-token accounting value whose physical PYUSD quantity was not separately decoded. Both variants retain the srRoyUSDC nested book claim and nominal stablecoin marks.'}
    liquid['backing']['newFindings'].append('Known Monad SteakETH and loose tokens plus Ethereum-local WETH are a conditional nested mark below the parent receipt book value. They replace the parent receipt when building the look-through subtotal; they must never be added on top of it.')
    liquid['backing']['sourcePaths'].extend([str(RAW.relative_to(ROOT)/x)for x in ['monad_token_claims_T.json','monad_steak_exit_T.json','remaining_known_claims_T.json']])
    for p in [rock,liq,royco]:p['backing']['sourcePaths'].extend([str(RAW.relative_to(ROOT)/x)for x in ['known_nested_claims_T.json','explicit_pool_claims_T.json','remaining_known_claims_T.json']])
    royco['backing']['sourcePaths'].extend([str(RAW.relative_to(ROOT)/'royco_morpho_accrual_T.json'),str(RAW.relative_to(ROOT)/'royco_accounting_transactions_repaired.json')])
    royco['controlsClosure']['sourcePaths']=[str(RAW.relative_to(ROOT)/x)for x in ['royco_authority_initial_T.json','royco_authority_mapped_T.json','royco_role_grants_T.json','royco_authority_active_T.json']]
    rock['controlsClosure']['sourcePaths']=[str(RAW.relative_to(ROOT)/'rocksolid_implementation_binding_T.json'),'raw/eth/2026-10-04/strict-products/rocksolid_impl.json']
    concrete['limitations']=['Visible shared Safe values are a conditional ceiling, not proven Delta ownership. Private custody positions and beneficial allocation records are needed to attribute the $339.412 million still unmapped even at that ceiling.','The successful withdraw calls establish queue acceptance under the captured source/state, not a token payout. No queued or claimed wrapper withdrawals were observed in the complete examined log interval.']
    liquid['limitations']=['The original partial reconstruction and expanded nested-receipt replacement use mixed oracle, nominal-dollar and nested book marks. Neither proves backing realizable for cash.','The nested Monad remainder requires priced WMON, a complete local/remote asset-and-liability inventory and the bridge reconciliation. SteakETH borrower backing and simulated payout transfers are not independently verified.','Aggregate 1%, 10% and 30% exits were not simulated. Historical cash census covers the captured Ethereum queue only; pending and cancelled requests are excluded from completed wait statistics.']
    rock['limitations']=['The known execution-wallet subtotal is $6.101 million, including net Spark exposure and conditional Balancer, YieldBasis and nested-vault receipts. The remaining $19.852 million needs attributable position or custody records; it is not a proven loss.','The state is Closing at T after a verified owner initiateClosing call. This code path differs from routine settleRedeem; permanent economic deprecation and final investor outcome are not established.','One of 428 verified cash claims cannot be uniquely matched to a request and is excluded from cash-wait statistics. Vault-held redemption reserves are separate from managed totalAssets and are not added again.']
    liq['limitations']=['Near reconciliation uses standardized ETH prices, nominal $1 ebUSD/USDC and a cached Uniswap V4 market value. It does not prove dollar pegs, unrestricted underlying redemptions or cash solvency.','Only the configured holder withdrawal path was simulated. The 1% call succeeds, while 10% and 30% revert; this bounds the tested path without measuring all possible manager unwinds.']
    royco['limitations']=['The fresh Morpho position and srRoyUSDC claim nearly reconcile the wrapper book, but underlying senior-credit backing, redeemable cash and the physical PYUSD dust balance remain outside this proof. Nominal $1 stablecoin marks are assumptions.','Caliber accounting is stale at T. Fresh venue reads replace stale loan marks, while the parent book and PYUSD base-token accounting value remain their captured accounting observations.','The mapped three-day duration-change role and two-day instruction-root state are verified separately. Other administrator/module paths and future changes are outside this control proof.']
    for p in ps:
        c=saved(('liquid_queue'if p['id']=='liquid'else p['id'])+'_exitlogs_T')
        assert all(isinstance(r['response'].get('result'),list)for r in c['records']),p['id']+' incomplete event census'
        p['historicalExits']['queriedIntervals']=len(c['records'])
        p['historicalExits']['successfulIntervals']=len(c['records'])
        p['historicalExits']['fromBlock']=c['fromBlock']
        p['historicalExits']['toBlock']=c['toBlock']
    assert all(p['historicalExits'].get('orderingInvariant',{}).get('settlementBeforeOrAtCash',True)for p in ps)
    output={'schemaVersion':1,'snapshot':{'UTC':utc(T),'timestamp':T,'ethereumBlock':BLOCK,'monadBlock':110031481,'priceUSD':price,'quoteOffsetSeconds':1},'observationsUTCDate':'2026-10-04','scope':'Bounded backing and executable-exit review. Read-only archive calls and non-persistent simulations only. Historical payouts are contract/token cash evidence, not a guarantee of future exits.','fieldDefinitions':{'successfulWithdrawalSimulation':'A non-persistent eth_call returned successfully. It is not an actual historical cash receipt and is not independently traced simulated token payment.','simulatedImmediatePayout':'Legacy compatibility field identifying the Liquity successful withdrawal simulation only. Use simulationStatus for presentation; no real payout is claimed.','reconstructedUSD':'Conditional sum of the stated examined positions after debt and internal receipt netting. Per-product claims overlap and must not be summed as independent market capital.','residualUSD':'Book NAV less the specified examined reconstruction. Scope, ownership and valuation differences are retained, not inferred into a deficit.'},'products':ps,'status':'Scoped captured evidence; unreconciled backing is quantified, not treated as missing assets or insolvency.'}
    OUT.write_text(json.dumps(output,indent=2));
    with (ROOT/'data/eth/backing_exit_demands.csv').open('w',newline='')as f:
        cols=['product','navPct','nativeAmount','nativeUnit','ETH','USD','simulatedRequest','successfulWithdrawalSimulation','simulationStatus','reason'];w=csv.DictWriter(f,fieldnames=cols);w.writeheader()
        for p in ps:
            for s in p['demandScenarios']:w.writerow({'product':p['id'],**{k:s[k]for k in cols if k!='product'}})
    capturepaths=sorted(x for x in RAW.rglob('*')if x.is_file())
    inputpaths=[ROOT/'tools/eth/carry_economics_build.py',ROOT/'data/eth/etherfi_partial_balance_sheet.json',ROOT/'data/eth/concrete_lookthrough_T.json',ROOT/'raw/eth/2026-10-04/strict-products/rocksolid_impl.json',ROOT/'raw/eth/2026-10-04/strict-products/concrete_impl.json',ROOT/'raw/eth/2026-10-04/strict-products/royco_impl.json',ROOT/'raw/eth/2026-10-04/strict-products/snapshot_rpc.json',ROOT/'raw/eth/2026-10-04/strict-products/market_controls_rpc.json',ROOT/'raw/eth/2026-10-04/strict-products/liquity_wallet_T.json',ROOT/'raw/eth/2026-10-04/strict-products/trove_final_rpc.json']
    manifest={'snapshotTimestamp':T,'inputs':[{'path':str(x.relative_to(ROOT)),'bytes':x.stat().st_size,'sha256':hashlib.sha256(x.read_bytes()).hexdigest()}for x in capturepaths+inputpaths],'builders':[{'path':str(x.relative_to(ROOT)),'sha256':hashlib.sha256(x.read_bytes()).hexdigest()}for x in sorted((ROOT/'tools/eth').glob('backing_exit_*.py'))],'outputs':[{'path':str(x.relative_to(ROOT)),'sha256':hashlib.sha256(x.read_bytes()).hexdigest()}for x in[OUT,ROOT/'data/eth/backing_exit_demands.csv']]}
    (ROOT/'data/eth/backing_exit_manifest.json').write_text(json.dumps(manifest,indent=2))
    print(json.dumps({'output':str(OUT),'products':len(ps),'captures':len(capturepaths),'historical':{p['id']:{k:p['historicalExits'][k]for k in['requestCount','fulfilledCount','receiptVerifiedCount']}for p in ps}}))

if __name__=='__main__':build()
