"""Build the final English findings from the bounded closure ledgers, offline."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
EN=ROOT/'research/eth/en'
def read(name):return json.loads((ROOT/'data/eth'/f'{name}.json').read_text())
def n(value,d=2):return f'{value:,.{d}f}' if value is not None else 'Not established'
def usd(value):return '$'+n(value/1e6,3)+'M'
def run():
    m=read('market_netting_closure');a=read('carry_attribution_closure');b=read('backing_exit_closure');h=m['headline'];w=a['common_window']
    lines=['# Capital, earned income and investor exits','',
    'Final public-record edition, reviewed 4 October 2026. All contract balances and tests retain the financial snapshot of **2 October 2026, 23:59:59 UTC**. Later capture dates do not refresh the snapshot.','',
    'The research separates three quantities that a yield dashboard often puts together: the capital represented by a claim, income earned over a dated period, and proceeds available through an investor exit. Each now has a reproducible ledger. Full-market ownership and private trading records remain outside the measured scope.','',
    '## Unique capital','',
    f'The default market chart measures 21.158M ETH equivalents across dated protocol layers. The new Ethereum custody graph identifies **{n(h["physical_custody_floor_ETH"],3)} ETH** in distinct native-ETH holdings and canonical WETH backed by matching native escrow. This is a restricted custody floor in examined yield venues; reserve cash can be idle. It is not a floor for all assets currently earning yield.','',
    '| Examined custody group | Physical native ETH / escrow-backed WETH |','|---|---:|']
    lines += [f'| {label} | {n(m["root_groups_ETH"][key],3)} |' for key,label in [('issuer_cash','Issuer cash'),('lending_cash','Aave and Spark reserve cash'),('LP_cash','Twenty-eight examined liquidity pools')]]
    lines += ['',f'Finalized withdrawal-queue custody of **{n(h["withdrawal_queue_ETH"],3)} ETH** is separate. Including it gives {n(h["extended_floor_including_withdrawal_queue_ETH"],3)} ETH in the examined custody graph. The queue balance equals locked ETH at the same block. Unfinalized stETH remains a claim rather than an additional physical ETH balance.','',
    f'Canonical WETH supply and native escrow agree at **{n(m["canonical_WETH"]["total_supply_WETH"],3)} ETH**. All canonical WETH plus the named native-ETH holdings defines a scoped ceiling of {n(h["canonical_WETH_scoped_ceiling_ETH"],3)} ETH. This scope excludes actual consensus balances, other native custody and other chains. It gives no global market ceiling or coverage percentage.','',
    f'The largest directly measured receipt repetition is **{n(h["lido_wstETH_lending_repeat_ETH"],3)} ETH equivalent** in Aave and Spark wstETH lender claims. Lido already accounts for the backing. Restaking has another nested path: Kelp node claims sit inside EigenLayer’s stETH strategy, which refers to Lido stake. The ownership edges overlap; adding or subtracting all of them indiscriminately would create a new counting error.','',
    f'Lido’s book reconciles to **{n(m["issuer_accounting"]["lido_book_ETH"],3)} ETH**. Its consensus fields refer to the oracle slot at {m["issuer_accounting"]["last_oracle_reference_UTC"]}, about twelve hours before T. Tested public historical consensus endpoints did not supply the actual state at T. Validator count times 32 ETH is not used as a substitute.','',
    'The pool extension follows the same 21 Uniswap V3 and seven Curve addresses through 25 monthly observations, including the September 2024 baseline. All 700 pool/month cash reads succeeded. The main exhibit uses the 24 completed months from October 2024 to September 2026. This is a history of physical ETH-side custody in a bounded current address census. It does not establish a market-wide historical pool universe, active trading liquidity or LP profit. V4, Balancer, Sushi and the broader pool universe remain outside this reconstruction.','',
    '**Conclusion:** repeated ownership is quantified, a restricted physical custody floor is established, and the global unique earning-capital total remains unavailable. A global number needs actual consensus state, remaining custody and bridge backing, and ownership allocation across all included layers. A blanket percentage haircut would not resolve those records.','',
    'Evidence: [market netting ledger](../../../data/eth/market_netting_closure.json), [custody CSV](../../../data/eth/market_netting_roots.csv), [pool history CSV](../../../data/eth/market_netting_lp_monthly.csv).','',
    '## Earned income','',
    f'Common window: **{w["start_date"]} to {w["end_date"]}**, {n(w["days"],3)} days. The window starts at the last block before the first tracked RLUSD V2 deposit. All included claims, loans and cash reward payments use the same endpoints.','',
    '| Destination / asset | Net claim growth | Cash rewards received | Accrued tracked loan cost | Ending claim | Ending tracked debt |','|---|---:|---:|---:|---:|---:|']
    for s in a['strategies']:
        f=s['funding_coverage'];lines.append(f'| {s["unit"]} | {n(s["claim_growth"])} | {n(s["cash_rewards"])} | {n(s["accrued_borrow_cost"])} | {n(f["ending_destination_claim_assets"])} | {n(f["ending_tracked_accrued_debt_assets"])} |')
    lines += ['', 'All amounts stay in the named asset. Dollar parity is a valuation assumption, not a verified redemption price. These components are not combined into a product carry ROI. In RLUSD, accrued loan costs exceed the captured claim growth and reward receipts; tracked loan principal also exceeds the destination claim. That makes financing coverage essential to interpretation.','',
    'Claim growth is ending claim less opening claim, plus actual withdrawals, less deposits. Destination fees already recognized in the share value are included. The result can contain lending income, donations or other recognized asset changes; it does not independently classify every dollar as organic interest. Cash withdrawals contain returned principal. The gain on redeemed shares uses the disclosed weighted-average acquisition-cost convention.','',
    'Borrowing cost is ending accrued debt less opening debt, plus actual repayments, less new borrowed cash. It includes interest still owed at T. Borrow/repay share ledgers reconcile to historical contract state, and pending interest uses the verified deployed model. Monthly APR quotes are not interpolated into paid cost.','',
    'Reward cash is measured from actual token transfers from the distributor to controlled accounts. Campaign sponsor, entitlement periods and destination allocation remain separate. Receiving a reward inside the window does not establish that the entire reward was earned inside it.','',
    '| Financing coverage | Direct same-token borrow/deposit amount | Deposit principal without that transaction link |','|---|---:|---:|']
    for s in a['strategies']:
        f=s['funding_coverage'];lines.append(f'| {s["unit"]} | {n(f["same_transaction_cooccurring_assets"])} | {n(f["deposit_principal_without_same_token_same_transaction_link"])} |')
    lines += ['', 'Receipt log order is part of the funding test. A deposit made before the loan arrives is not assigned to that loan, even if both events share one transaction. Four additional currency-changing receipts trace USDC loans into RLUSD/PYUSD deposits. The borrowed and invested asset amounts remain separate; no peg conversion or common-dollar profit is assumed.', '', '| Currency-changing deposit | Borrowed cash | Verified transaction |', '|---|---:|---|']
    for row in a['funding_coverage'].get('cross_currency_common_window_links',[]):
        cash='; '.join(n(l['amount'])+' '+l['symbol'] for l in row['loans'])
        lines.append(f'| {n(row["destination_assets"])} {row["destination_symbol"]} | {cash} | [Transfer receipt]({row["sourceURL"]}) |')
    usdc=[l for l in a['other_measured_debt'] if l['symbol']=='USDC']
    lines += ['', f'The other tracked USDC loan accrues {n(sum(l["accrued_borrowing_interest_assets"] for l in usdc))} USDC of cost in this window. It is not included in either same-currency chart. PRIME’s underlying is wYLDS with six decimals; transferred PRIME share basis and its full collateral financing remain unallocated.', '', '| Own-credit diagnostic | Accrual events | Gross recognition-time overlap | Net destination allocation / paid own-interest |', '|---|---:|---:|---|']
    for row in a['own_credit_recycling']['rows']:
        lines.append(f'| {row["symbol"]} | {row["accrual_event_count"]} | {n(row["event_weighted_gross_own_credit_overlap_assets"])} {row["symbol"]} | Not established |')
    fees=a['fees_common_window']
    lines += ['', f'The common window contains {len(fees["payments"])} Ethereum fee-claim payments totaling {n(fees["amounts_by_asset"][0]["amount"],5)} weETH. Payment dates do not assign the earning period or carry strategy. The Ethereum net share return already reflects recognized fees; these payments are not deducted a second time.', '', '| Whole Ethereum share / issuer conversion | ETH book return in the common window |', '|---|---:|']
    for row in a['matched_window_share_returns']:
        lines.append(f'| {row["name"].replace("_"," ")} | {n(row["window_return"]*100,4)}% |')
    lines += ['', 'These whole-share outcomes use identical endpoint blocks. They include every strategy and do not identify the causal carry contribution.']
    pair=a['matched_debt_and_destination_cohorts']['retained_same_unit_pair_summary']
    lines += ['', f'One exact retained pair matches {n(pair["loan_cash_assets"],0)} PYUSD of borrowing and destination deposits. It exists for only {pair["window_seconds"]} seconds before T: destination claim growth is {n(pair["net_accrued_destination_claim_growth_assets"],6)} PYUSD and accrued loan cost is {n(pair["accrued_borrowing_interest_assets"],6)} PYUSD. Their {n(pair["lending_minus_borrowing_component_assets"],6)} PYUSD component is before rewards, outer fees and own-credit allocation. Neither claim income nor loan interest was paid as cash in this interval. This tiny exact-state diagnostic is too short to establish strategy economics and is not annualized. The older18M PYUSD pair has subsequent withdrawals, so its retained acquisition basis cannot be uniquely assigned.'.replace('older18M','older 18M')]
    lines += ['', 'A same-transaction transfer establishes a financing link. It does not identify unique fungible dollars or allocate later profit. Unmatched principal is not assumed unborrowed. Own-credit can recycle a borrower’s interest through a destination it owns; gross recognition-time overlap, where reconstructed, remains a diagnostic rather than additional income. Net own-interest after fees and actual cash distribution remain unallocated.','',
    '**Conclusion:** historical claim growth, loan expense and paid incentives are measured. Staking, other destinations, historical self-credit, outer fees and private payouts are not fully allocated to each carry sleeve or whole product. Complete sleeve net income stays unavailable. The fixed-rate calculator remains a separately labelled scenario.','',
    'Evidence: [income components](../../../data/eth/carry_attribution_closure.json), [historical event ledger](../../../data/eth/carry_attribution_ledger.json), [financing transactions](../../../data/eth/carry_attribution_funding_links.csv).','',
    '## Investor exits','',
    'Demand is tested at 1%, 10% and 30% of each whole accounting book. Calls use the examined Ethereum holder and configured route; Liquid’s book denominator includes Ethereum and Optimism shares. Requests, immediate withdrawals and full portfolio unwinds are separate. Read-only calls persist no state and send no transaction.','',
    '| Product | Book, USD | Examined positions / conditional claims, USD | Book less examined reconstruction, USD | Verified historical cash payout records |','|---|---:|---:|---:|---:|']
    for p in b['products']:
        back=p['backing'];lines.append(f'| {p["name"]} | {usd(p["bookNAV_USD"])} | {usd(back.get("nestedReceiptReplacementReconstructionUSD",back["reconstructedUSD"]))} | {usd(back.get("nestedReceiptReplacementResidualUSD",back["residualUSD"]))} | {p["historicalExits"]["receiptVerifiedCount"]:,} |')
    lines += ['', 'The reconstruction column includes the stated oracle marks and conditional nested claims. Coverage differs by product. Book less examined reconstruction is an unmapped amount; it is not a proven deficit or loss. Shared custody does not establish beneficial assignment to one share book.','']
    for p in b['products']:
        lines += [f'### {p["name"]}','',p['backing']['attributionScope'],'',p['demandScenarios'][0]['reason'],'']
        if p['id']=='concrete':
            bound=p['backing']['unattributedBounds'];lines += [f'Granting Delta every captured visible shared asset gives a conditional attributable ceiling of {usd(bound["attributableVisibleToDeltaUpperUSD"])} and still leaves {usd(bound["minimumDeltaBookUnmappedToCapturedSharedAssetsUSD"])} of its book unmapped to this set. Its captured attributable range starts at zero because beneficial assignment is not established. The sibling internal receipt is eliminated. This makes private asset statements and allocation agreements necessary to reconcile the whole claim.','']
        if p['id']=='liquid':
            back=p['backing'];nested=back['nestedMonad'];lines += [f'The original mixed-price reconstruction was {usd(back["reconstructedUSD"])} with a {usd(back["residualUSD"])} scope residual. The expanded look-through replaces the nested Monad book receipt with captured claims rather than adding them on top: {usd(back["nestedReceiptReplacementReconstructionUSD"])} reconstructed and {usd(back["nestedReceiptReplacementResidualUSD"])} unmapped. It includes {n(nested["SteakETHShares"],6)} SteakETH shares converting to {n(nested["SteakClaimWETH"],6)} WETH in that receipt book, plus known loose balances. SteakETH backing itself is a nested credit claim, not independently reconciled physical assets.', '', nested['exitLimit'], '']
        if p['id']=='royco':lines += ['Machine and Caliber beacon implementations at T match the examined verified bytecode. The instruction-root delay is two days. Duration changes use an active AccessManager role held by a 3-of-4 Safe with a three-day execution delay; an unscheduled execute call reverts. The controls apply to different actions. They do not establish an immutable or universally additive five-day notice, and every other admin/module path is outside this particular proof.','']
        if p['id']=='rocksolid':lines += ['The T contract state is Closing. Verified source distinguishes initiateClosing from ordinary redemption settlement; new redemption requests are rejected in that state. The owner transition is dated in the exit ledger. This is evidence of an initiated closure process, not proof of a loss, completed closure or permanent future deprecation. Historical payout records remain relevant to existing claims.','']
        h=p['historicalExits'];lines += [h['coverage'],'']
        if h['waitHours']['median'] is not None:lines += [f'Completed request-to-cash observations have a median of {n(h["waitHours"]["median"],2)} hours, p90 {n(h["waitHours"]["p90"],2)} hours and maximum {n(h["waitHours"]["max"]/24,2)} days. The wait can include investor collection delay. Cancelled and pending requests are excluded; these figures do not forecast a new request.','']
    lines += ['**Conclusion:** historical token payouts and snapshot execution constraints are documented. Concrete queues requests, Liquid has a measured payout history but no tested aggregate unwind, Rocksolid rejects new requests in Closing, Liquity succeeds at the tested 1% withdrawal size while larger calls revert, and Royco’s examined immediate route is unavailable at T. Public backing and private ownership boundaries remain product-specific.','',
    'Evidence: [backing and exits](../../../data/eth/backing_exit_closure.json), [all demand scenarios](../../../data/eth/backing_exit_demands.csv), [source manifest](../../../data/eth/backing_exit_manifest.json).','',
    '## What this edition supports','',
    'The completed website supports a colleague presentation of the market’s reported layers, two-year category changes, financing mechanics, measured income components and investor exit constraints. It preserves the original Bitcoin chapter structure and uses bars for capital exhibits. Every numerical answer keeps its measurement date, unit, denominator and evidence boundary.','',
    'Private custody allocation, full actual consensus state and a complete strategy-attributed investor P&L cannot be created from public share prices or sampled rates. They remain precise evidence limits, not silently filled estimates. The record needed to improve each answer is stated in its ledger.','']
    text='\n'.join(lines);assert '\u2014' not in text and '\u2013' not in text
    (EN/'CAPITAL-INCOME-EXIT.md').write_text(text)
    print('Final capital, income and exit findings built from the closure ledgers')

if __name__=='__main__':run()
