"""Offline calculation of verified borrowing/deposit/redemption lifecycles."""
import json,datetime as dt,hashlib,sys
from decimal import Decimal as N
from pathlib import Path
import credit_expansion_deep as c
from credit_expansion_build import words,event,string
from keccak_lib import keccak
ROOT=c.ROOT;D=c.D;RAW=c.RAW;T=c.c.T
DEPOSIT='0x'+keccak(b'Deposit(address,address,uint256,uint256)').hex()
WITHDRAW='0x'+keccak(b'Withdraw(address,address,address,uint256,uint256)').hex()
TRANSFER='0x'+keccak(b'Transfer(address,address,uint256)').hex()

def read(name):return json.loads((D/('credit_expansion_deep_'+name+'.json')).read_text())
def debt(shares,market):return (shares*(market[2]+1)+market[3]+1000000-1)//(market[3]+1000000)
def source_for(tx,records):
 return [{k:r[k] for k in ['url','path','sha256','captured_at_UTC']} for r in records if any(x.get('method')=='eth_getTransactionReceipt' and x.get('params')==[tx] for x in (r.get('request') if isinstance(r.get('request'),list) else [r.get('request')]) if isinstance(x,dict))]
def build():
 cap=read('capture');state=read('state');funding=read('funding');wrapper=read('wrapper');records=c.sources();timeline=[];bylabel={};stateindex={}
 for l in state['labels']:
  if l.get('label'):stateindex[(l['label'],l['when'],l['signature'],l.get('market_id'))]=words(l['response'].get('result'))
 for tx in cap['transactions']:
  receipt=tx['response'].get('result')
  if not receipt:continue
  block=int(receipt['blockNumber'],16);ts=int(cap['blocks'][str(block)]['result']['timestamp'],16);wallet=c.A if tx['label'].startswith('A') or any(c.A[2:] in t for l in receipt['logs'] for t in l['topics']) else c.B;vault=c.V1 if wallet==c.A else c.V2;flows=[];vaultflows=[]
  for l in receipt['logs']:
   if l['topics'][0]==TRANSFER and len(l['topics'])==3:
    flows.append({'token':l['address'],'from':'0x'+l['topics'][1][-40:],'to':'0x'+l['topics'][2][-40:],'amount_raw':str(words(l['data'])[0]),'log_index':int(l['logIndex'],16)})
   if l['address']==vault and l['topics'][0] in [DEPOSIT,WITHDRAW]:
    w=words(l['data']);vaultflows.append({'event':'Deposit' if l['topics'][0]==DEPOSIT else 'Withdraw','caller':'0x'+l['topics'][1][-40:],'receiver':'0x'+l['topics'][2][-40:],'owner':'0x'+l['topics'][3][-40:] if l['topics'][0]==WITHDRAW else None,'assets_raw':str(w[0]),'assets_units':w[0]/1e6,'shares_raw':str(w[1]),'shares_units':w[1]/1e18})
  item={'label':tx['label'],'wallet':wallet,'transaction':tx['transaction'],'block':block,'timestamp':ts,'timestamp_UTC':dt.datetime.fromtimestamp(ts,dt.timezone.utc).isoformat(),'gas_ETH':int(receipt['gasUsed'],16)*int(receipt['effectiveGasPrice'],16)/1e18,'Morpho_events':[e for l in receipt['logs'] if (e:=event(l))],'vault_events':vaultflows,'public_ERC20_transfers':flows,'sources':source_for(tx['transaction'],records)};timeline.append(item);bylabel[item['label']]=item
 timeline.sort(key=lambda x:(x['block'],x['transaction']))
 ashare=sum(int(t['vault_events'][0]['shares_raw']) for t in timeline if t['wallet']==c.A and t['vault_events'] and t['vault_events'][0]['event']=='Deposit');withdrawA=bylabel['A_redeem']['vault_events'][0];assert ashare==int(withdrawA['shares_raw'])
 costs=[N(1000000),N('350000.000100'),N(350000)];adeposits=sorted([t for t in timeline if t['wallet']==c.A and t['vault_events'] and t['vault_events'][0]['event']=='Deposit'],key=lambda t:t['timestamp']);grossA=N(withdrawA['assets_raw'])/10**6-sum(costs);model=next(l for l in funding['labels'] if l['label']=='A_redeem');market=model['stored_market'].copy();rate=int(model['response']['result'],16);elapsed=bylabel['A_redeem']['timestamp']-market[4];term1=rate*elapsed;term2=term1*term1//(2*10**18);term3=term2*term1//(3*10**18);pending=market[2]*(term1+term2+term3)//10**18;market[2]+=pending;cases=[]
 for deposit,cost in zip(adeposits,costs):
  if deposit['label']=='A_first_deposit':continue
  predecessor=next(t for t in timeline if t['wallet']==c.A and t['Morpho_events'] and any(e['event']=='Borrow' for e in t['Morpho_events']) and 0<=deposit['timestamp']-t['timestamp']<300);borrow=next(e for e in predecessor['Morpho_events'] if e['event']=='Borrow');allocated=N(withdrawA['assets_raw'])*N(deposit['vault_events'][0]['shares_raw'])/N(ashare)/10**6;debtExit=N(debt(int(borrow['shares_raw']),market))/10**6;loan=N(borrow['assets_raw'])/10**6
  cases.append({'id':'a122-usdc-'+dt.datetime.fromtimestamp(predecessor['timestamp'],dt.timezone.utc).strftime('%Y-%m-%d'),'wallet':c.A,'beneficial_owner':None,'collateral':'OETH','debt_currency':'USDC','destination_name':'RockawayX f(x) Protocol Ecosystem USDC','destination':c.V1,'borrow_transaction':predecessor['transaction'],'deposit_transaction':deposit['transaction'],'redeem_transaction':bylabel['A_redeem']['transaction'],'borrow_timestamp_UTC':predecessor['timestamp_UTC'],'deposit_timestamp_UTC':deposit['timestamp_UTC'],'redeem_timestamp_UTC':bylabel['A_redeem']['timestamp_UTC'],'borrowed_units':float(loan),'deposited_units':float(cost),'minted_shares_raw':deposit['vault_events'][0]['shares_raw'],'allocated_redemption_units':float(allocated),'allocated_vault_income_units':float(allocated-cost),'debt_value_at_redemption_units':float(debtExit),'funding_cost_through_redemption_units':float(debtExit-loan),'allocated_funded_result_before_gas_units':float(allocated-cost-(debtExit-loan)),'allocation_rule':'Pro rata by the exact shares of each lot burned in the common full redemption. This is an analytical lot allocation, not a separate cash payment.','funding_rule':'Historical IRM borrowRateView plus the exact Morpho three-term Taylor accrual and share-to-assets rounding. Valuation at destination exit, not a measured repayment.','terminal_destination_direct_shares':0,'debt_repaid_in_observed_exit':False,'cash_destination':'Zama Confidential USDC wrapper','whole_wallet_profit':None})
 borrowB=next(t for t in timeline if t['wallet']==c.B and any(e['event']=='Borrow' for e in t['Morpho_events']));depositB=next(t for t in timeline if t['wallet']==c.B and t['vault_events'] and t['vault_events'][0]['event']=='Deposit');redeemB=bylabel['B_redeem'];repayB=bylabel['B_repay'];idB=next(e['market_id'] for e in repayB['Morpho_events'] if e['event']=='Repay');p=stateindex[('B_repay','after','position(bytes32,address)',idB)];m=stateindex[('B_repay','after','market(bytes32)',idB)];residualRaw=debt(p[1],m);paidRaw=int(next(e['assets_raw'] for e in repayB['Morpho_events'] if e['event']=='Repay'));returnedRaw=int(redeemB['vault_events'][0]['assets_raw']);residual=residualRaw/1e6;paid=paidRaw/1e6;returned=returnedRaw/1e6;vaultIncomeB=(returnedRaw-10**12)/1e6;fundingCostB=(paidRaw+residualRaw-10**12)/1e6;fundedResultB=(returnedRaw-paidRaw-residualRaw)/1e6;gasB=sum(x['gas_ETH'] for x in [borrowB,depositB,redeemB,repayB]);assert depositB['vault_events'][0]['shares_raw']==redeemB['vault_events'][0]['shares_raw']
 cases.append({'id':'4f87-pyusd-2026-09-17','wallet':c.B,'beneficial_owner':None,'collateral':'weETH','debt_currency':'PYUSD','destination_name':'Sentora Huma PST Main','destination':c.V2,'borrow_transaction':borrowB['transaction'],'deposit_transaction':depositB['transaction'],'redeem_transaction':redeemB['transaction'],'repay_transaction':repayB['transaction'],'borrow_timestamp_UTC':borrowB['timestamp_UTC'],'deposit_timestamp_UTC':depositB['timestamp_UTC'],'redeem_timestamp_UTC':redeemB['timestamp_UTC'],'repay_timestamp_UTC':repayB['timestamp_UTC'],'borrowed_units':1000000,'deposited_units':1000000,'redemption_units':returned,'vault_income_units':vaultIncomeB,'paid_debt_units':paid,'residual_debt_units_at_repayment':residual,'funding_cost_through_repayment_units':fundingCostB,'funded_result_before_gas_units':fundedResultB,'gas_ETH':gasB,'initial_collateral_units':700,'returned_collateral_units':int(next(e['assets_raw'] for e in repayB['Morpho_events'] if e['event']=='WithdrawCollateral'))/1e18,'residual_collateral_units':p[2]/1e18,'loan_position_before_borrow':stateindex[(borrowB['label'],'before','position(bytes32,address)',idB)],'terminal_destination_direct_shares':0,'fully_repaid':False,'whole_wallet_profit':None})
 cases[-1]['residual_measurement']='Exact debt-share conversion in end-of-block state for the repayment block, whose market last-update timestamp equals that block timestamp. Archive eth_call returns end-of-block state, not an intra-transaction trace.'
 cases[-1]['measured_cash_left_after_repayment_units']=(returnedRaw-paidRaw)/1e6
 cases[-1]['result_kind']='Observed cash remaining after repayment minus the debt liability valued in the repayment-block state. Before gas; not whole-wallet profit.'
 destination_metadata_path=D/'credit_expansion_deep_destination_metadata.json'
 destination_metadata=json.loads(destination_metadata_path.read_text()) if destination_metadata_path.exists() else {'labels':[]}
 for case in cases:
  deposit=next(x for x in timeline if x['transaction']==case['deposit_transaction']);supply=next(e for e in deposit['Morpho_events'] if e['event']=='Supply');params=stateindex[(deposit['label'],'after','idToMarketParams(bytes32)',supply['market_id'])];meta={x['signature']:x['response'].get('result') for x in destination_metadata['labels'] if x['market_id']==supply['market_id']}
  case['destination_lending_route']={'protocol':'Morpho Blue','market_id':supply['market_id'],'adapter':supply['on_behalf'],'loan_asset':'0x'+format(params[0],'040x'),'collateral_asset':'0x'+format(params[1],'040x'),'collateral_symbol_at_T':string(meta.get('symbol()')),'collateral_name_at_T':string(meta.get('name()')),'LLTV':params[4]/1e18,'supplied_units_in_deposit_receipt':int(supply['assets_raw'])/1e6,'mechanism':'The deposit receipt shows the vault adapter supplying the underlying to this Morpho lending market. The borrower receives vault shares. The destination is a loan-supplier exposure; its product name is not proof that this wallet directly owns the collateral token.'}
 terminal=[]
 for wallet in [c.A,c.B]:
  ls=[l for l in funding['labels'] if l['label']=='T' and l.get('wallet')==wallet];vals={l['signature']:words(l['response'].get('result')) for l in ls};p=vals['position(bytes32,address)'];m=vals['market(bytes32)'];terminal.append({'wallet':wallet,'financial_timestamp':T,'market_id':ls[0]['market_id'],'destination_direct_share_balance_raw':str(vals['balanceOf(address)'][0]),'destination_PPS_asset_units_per_1e18_shares':vals['convertToAssets(uint256)'][0]/1e6,'borrow_shares_raw':str(p[1]),'collateral_raw':str(p[2]),'debt_units_stored_at_T':debt(p[1],m)/1e6,'market_last_update':m[4],'pending_accrual_seconds_at_T':T-m[4],'debt_measurement':'Stored-market valuation, including interest only through last update. Not fully accrued T debt.'})
 vals={l['signature']:l['response'].get('result') for l in wrapper['labels']};input=vals['cash_out_transaction']['input'];assert input[2:10]==c.c.sel('wrap(address,uint256)');recipient='0x'+input[10:74][-40:];amount=int(input[74:138],16)/1e6;assert recipient==c.A and amount==withdrawA['assets_units']
 privacy={'contract':wrapper['wrapper'],'name':string(vals['name()']),'underlying_at_T':'0x'+vals['underlying()'][-40:],'implementation_at_T':'0x'+vals['EIP1967_implementation'][-40:],'wrap_receiver':recipient,'wrapped_USDC_units':amount,'transaction':bylabel['A_cash_out']['transaction'],'timestamp_UTC':bylabel['A_cash_out']['timestamp_UTC'],'public_trace_boundary':'wrap recipient and deposited USDC amount are public. Subsequent confidential token amounts/balances cannot be reconstructed from public ERC20 flows without authorised decryption or a disclosed accounting statement.','ownership_inferred':False}
 silo=read('silo_legacy');bridges={l['asset']:string(l['response'].get('result')) for l in silo['labels'] if l['signature']=='symbol()'};legacy=[]
 for l in silo['labels']:
  if l['signature']!='getSilo(address)':continue
  r=l['response'].get('result')
  if not r or not int(r,16):continue
  address='0x'+r[-40:];loans=[]
  for asset,symbol in bridges.items():
   related={x['signature']:words(x['response'].get('result')) for x in silo['labels'] if x.get('silo')==address and x.get('asset')==asset};debtValue=related['totalBorrowAmountWithInterest(address,address)'][0]/1e18;loans.append({'asset':asset,'symbol':symbol,'borrow_units_with_interest':debtValue,'deposited_units_with_interest':related['totalDepositsWithInterest(address,address)'][0]/1e18,'borrow_APY_view':related['borrowAPY(address,address)'][0]/1e18,'paused':bool(related['isSiloPaused(address,address)'][0]),'scope':'Entire bridge-asset loan total in this Silo, not an account allocation or a verified USD valuation.'})
  legacy.append({'protocol':'Silo V1','chain':'Ethereum','market_id':address,'ETH_asset':l['asset'],'ETH_symbol':l['symbol'],'financial_timestamp':T,'bridge_loans':loans})
 silo_arb_path=D/'credit_expansion_deep_silo_arb_retry.json';registry_observations=[]
 if silo_arb_path.exists():
  arb=json.loads(silo_arb_path.read_text());bridge_symbols={x['asset']:string(x['response'].get('result')) for x in arb['labels'] if x['signature']=='symbol()'};bridge_decimals={x['asset']:words(x['response'].get('result'))[0] for x in arb['labels'] if x['signature']=='decimals()'}
  for l in arb['labels']:
   if l['signature']!='getSilo(address)' or l['response'].get('result') in [None,'0x'] or not int(l['response']['result'],16):continue
   address='0x'+l['response']['result'][-40:];loans=[]
   for asset,symbol in bridge_symbols.items():
    related={x['signature']:words(x['response'].get('result')) for x in arb['labels'] if x.get('silo')==address and x.get('asset')==asset};decimals=bridge_decimals[asset]
    loans.append({'asset':asset,'symbol':symbol,'denomination_label':'USDC.e (bridged USDC)' if asset=='0xff970a61a04b1ca14834a43f5de4533ebddb5cc8' else symbol,'decimals':decimals,'borrow_units_with_interest':related['totalBorrowAmountWithInterest(address,address)'][0]/10**decimals,'deposited_units_with_interest':related['totalDepositsWithInterest(address,address)'][0]/10**decimals,'borrow_APY_view':related['borrowAPY(address,address)'][0]/1e18,'paused':bool(related['isSiloPaused(address,address)'][0]),'scope':'Entire bridge-asset loan total in this selected Silo, not an account allocation or a verified USD valuation.'})
   legacy.append({'protocol':'Silo V1','chain':'Arbitrum','market_id':address,'ETH_asset':l['asset'],'ETH_symbol':l['symbol'],'financial_timestamp':T,'bridge_loans':loans})
  metadata={x['asset']:{'symbol':string(x['response'].get('result'))} for x in arb.get('current_factory_token_metadata',[]) if x['signature']=='symbol()'}
  pairs=[{'id':x['id'],'config':x['config'],'silos':x['silos'],'assets':[{'address':arb['current_factory_assets'].get(s),**metadata.get(arb['current_factory_assets'].get(s),{})} for s in x['silos']]} for x in arb.get('current_factory_pairs',[])]
  credit_routes=[]
  for pair in pairs:
   ls=[x for x in arb.get('current_factory_credit_states',[]) if x['id']==pair['id']]
   if not ls:continue
   USD=[x for x in ls if x['asset']=='0xaf88d065e77c8cc2239327c5edb3a432268e5831'];ETH=[x for x in ls if x['asset']=='0x82af49447d8a07e3bd95bd0d56f35241523fbab1'];uv={x['signature']:words(x['response'].get('result')) for x in USD};ev={x['signature']:words(x['response'].get('result')) for x in ETH};ec=ev['getConfig(address)'];uc=uv['getConfig(address)'];storage=ev['getSiloStorage()']
   credit_routes.append({'protocol':'Silo current factory generation','chain':'Arbitrum','config_id':pair['id'],'config':pair['config'],'ETH_silo':ETH[0]['silo'],'USD_silo':USD[0]['silo'],'collateral_asset':ETH[0]['asset'],'debt_asset':USD[0]['asset'],'debt_symbol':'USDC','debt_units_with_interest':uv['getDebtAssets()'][0]/1e6,'ETH_borrowable_deposit_units_with_interest':ev['getCollateralAssets()'][0]/1e18,'ETH_protected_deposit_units':storage[2]/1e18,'ETH_max_LTV':ec[10]/1e18,'ETH_liquidation_threshold':ec[11]/1e18,'liquidation_target_LTV':ec[12]/1e18,'ETH_liquidation_fee':ec[13]/1e18,'USD_interest_model':'0x'+format(uc[9],'040x'),'USD_DAO_fee_fraction':uc[0]/1e18,'USD_deployer_fee_fraction':uc[1]/1e18,'hook_receiver':'0x'+format(ec[15],'040x'),'financial_timestamp':T,'status':'fixed_T_read','scope':'Canonical WETH/USDC isolated pair in this factory generation. Debt is the USDC silo total with interest. No borrower purpose, hook trust assessment or global Silo allocation is inferred.'})
  registry_observations.append({'protocol':'Silo current factory generation','chain':'Arbitrum','factory':arb['factory'],'financial_timestamp':T,'next_silo_id':arb['next_silo_id'],'nonzero_configs':len([x for x in arb['factory_configs'] if x['response'].get('result') and int(x['response']['result'],16)]),'enumeration_complete':arb['factory_enumeration_complete'],'pairs':pairs,'canonical_ETH_USD_credit_routes':credit_routes,'canonical_ETH_USD_debt_USDC_units':sum(x['debt_units_with_interest'] for x in credit_routes),'scope':arb['scope'],'archive_provider_repaired':True})
 summary={'financial_snapshot_timestamp':T,'verified_historical_credit_to_yield_cases':3,'borrower_owners_identified':0,'A_full_vault_deposits_USDC':float(sum(costs)),'A_full_vault_redemption_USDC':withdrawA['assets_units'],'A_full_vault_cash_income_USDC':float(grossA),'A_borrowed_lots_allocated_vault_income_USDC':sum(x['allocated_vault_income_units'] for x in cases[:2]),'A_borrowed_lots_funding_cost_at_redemption_USDC':sum(x['funding_cost_through_redemption_units'] for x in cases[:2]),'A_borrowed_lots_allocated_funded_result_before_gas_USDC':sum(x['allocated_funded_result_before_gas_units'] for x in cases[:2]),'B_vault_income_PYUSD':vaultIncomeB,'B_funding_cost_PYUSD':fundingCostB,'B_funded_result_before_gas_PYUSD':fundedResultB,'B_gas_ETH':gasB,'A_wrapped_redemption_USDC':amount,'A_current_carry_allocation':None,'whole_wallet_profit':None,'legacy_Silo_ETH_markets_measured':len(legacy),'legacy_Silo_selected_XAI_debt_units':sum(l['borrow_units_with_interest'] for m in legacy for l in m['bridge_loans'] if l['symbol']=='XAI')}
 summary['lifecycle_transactions']=len(timeline)
 summary['legacy_Silo_Arbitrum_selected_USDCe_debt_units']=round(sum(l['borrow_units_with_interest'] for m in legacy if m['chain']=='Arbitrum' for l in m['bridge_loans'] if l['asset']=='0xff970a61a04b1ca14834a43f5de4533ebddb5cc8'),6)
 summary['Silo_Arbitrum_current_factory_configs']=sum(x['nonzero_configs'] for x in registry_observations)
 summary['Silo_Arbitrum_current_factory_canonical_ETH_USD_routes']=sum(len(x['canonical_ETH_USD_credit_routes']) for x in registry_observations)
 summary['Silo_Arbitrum_current_factory_canonical_ETH_USD_debt_USDC_units']=sum(x['canonical_ETH_USD_debt_USDC_units'] for x in registry_observations)
 fees=read('fees');fee_observations=[]
 accrual_topic='0x'+keccak(b'AccrueInterest(uint256,uint256,uint256,uint256)').hex()
 for vault,label in [(c.V1,'A_redeem'),(c.V2,'B_redeem')]:
  snapshots=[]
  for when in ['before_exit','after_exit','T']:
   ls=[x for x in fees['labels'] if x['vault']==vault and x['when']==when]
   values={x['signature']:words(x['response'].get('result')) for x in ls}
   snapshots.append({'when':when,'block':ls[0]['block'],'performance_fee_fraction':values['performanceFee()'][0]/1e18,'management_fee_per_second_fraction':values['managementFee()'][0]/1e18,'owner_contract_or_account':'0x'+format(values['owner()'][0],'040x'),'preview_redeem_assets_raw':str(values['previewRedeem(uint256)'][0]),'convert_to_assets_raw':str(values['convertToAssets(uint256)'][0])})
  tx=next(x for x in cap['transactions'] if x['label']==label)
  accruals=[words(l['data']) for l in tx['response']['result']['logs'] if l['address']==vault and l['topics'][0]==accrual_topic]
  actual=bylabel[label]['vault_events'][0]['assets_raw']
  fee_observations.append({'vault':vault,'exit_transaction':tx['transaction'],'snapshots':snapshots,'actual_redemption_assets_raw':actual,'actual_equals_post_exit_preview':actual==snapshots[1]['preview_redeem_assets_raw'],'vault_accrual_events_at_exit':[{'previous_total_assets_raw':str(w[0]),'new_total_assets_raw':str(w[1]),'performance_fee_shares_raw':str(w[2]),'management_fee_shares_raw':str(w[3]),'scope':'Vault-wide accrual event, not a fee allocation to this borrower.'} for w in accruals],'redemption_path':'Standard ERC4626 redemption. Verified deployed code calculates fee-aware previewRedeem, burns shares and transfers the resulting assets.','fee_treatment':'Performance and management fees dilute shares during accrual and are already reflected in the paid redemption and measured income. Do not deduct the headline performance fee again. No separate redemption deduction is present in this standard code path; forced-deallocation penalties are a different path.'})
 controls={x['signature']:x['response'].get('result') for x in fees['labels'] if x['vault']==wrapper['wrapper']}
 privacy['control_state_at_T']={'owner':'0x'+controls['owner()'][-40:],'pauser':'0x'+controls['pauser()'][-40:],'paused':bool(int(controls['paused()'],16)),'configured_observers':c.c.array_addresses(controls['observers()']),'meaning':'The owner can add decryption observers, set a pauser, block users and authorise upgrades. A zero pauser means no address currently has the pause role. The empty global observer list does not audit wallet-authorised decryption access or remove the owner power to change these settings.','source_verified_implementation':privacy['implementation_at_T']}
 boundary_path=D/'credit_expansion_deep_public_boundary.json';boundary=None
 if boundary_path.exists():
  b=json.loads(boundary_path.read_text());entries=[];wraps=[];batch_events=[];counterparties=[];event_topics={'0x'+keccak((name+'(uint256,address,bytes32)').encode()).hex():name for name in ['Joined','Quit','Claimed']}
  def public_time(log):
   block=int(log['blockNumber'],16);ts=int(b['blocks'][str(block)]['result']['timestamp'],16)
   return {'transaction':log['transactionHash'],'block':block,'timestamp':ts,'timestamp_UTC':dt.datetime.fromtimestamp(ts,dt.timezone.utc).isoformat()}
  for query in b['queries']:
   for log in query['response'].get('result',[]):
    if query['kind']=='wrap_to_wallet':wraps.append({**public_time(log),'receiver':'0x'+log['topics'][1][-40:],'USDC_raw':str(words(log['data'])[0]),'USDC_units':words(log['data'])[0]/1e6})
    if query['kind'] in ['confidential_from_wallet','confidential_to_wallet']:entries.append({**public_time(log),'from':'0x'+log['topics'][1][-40:],'to':'0x'+log['topics'][2][-40:],'encrypted_amount_handle':log['topics'][3],'amount_units':None,'event_index':int(log['logIndex'],16)})
  for tx,response in b.get('receipts',{}).items():
   for log in response['result']['logs']:
    if log['topics'][0] in event_topics and len(log['topics'])==3 and '0x'+log['topics'][2][-40:]==c.A:batch_events.append({**public_time(log),'contract':log['address'],'event':event_topics[log['topics'][0]],'batch_id':int(log['topics'][1],16),'account':c.A,'encrypted_amount_handle':log['data'],'amount_units':None,'role_verified_for_this_contract':log['address']=='0x2deafb36f3b118d434cde4708e8350eae918724d'})
  for address,response in b.get('counterparty_codes',{}).items():
   source=next(x for x in reversed(records) if x['key']=='post_wrap_counterparty_'+address and x['http_status']==200);verified=json.loads((ROOT/source['path']).read_text());counterparties.append({'address':address,'verified_contract_name':verified['name'],'historical_bytecode_matches_verified':response['result']==verified['deployed_bytecode'],'beneficial_owner':None,'source_path':source['path'],'source_sha256':source['sha256']})
  boundary={'wallet':c.A,'contract':b['contract'],'from_block':b['from_block'],'to_block':b['to_block'],'complete_for_stated_queries':all(q['complete'] for q in b['queries']),'query_counts':[{'kind':q['kind'],'events':len(q['response'].get('result',[])),'complete':q['complete']} for q in b['queries']],'public_wraps':wraps,'encrypted_transfer_events':entries,'batch_events':batch_events,'counterparties':counterparties,'receipt_transactions_added':len(b.get('receipts',{})),'scope':b['scope'],'interpretation':'Public routing shows confidential batch joins and a verified batcher\'s Quit refund events. Encrypted handles do not establish positive transferred quantities, realised yield, exact allocation of the first wrap, or whole-wallet profit. The later additional wrap and incoming confidential events prevent exclusive attribution of fungible balances.'}
  privacy['public_event_census_complete_for_stated_wallet_queries']=boundary['complete_for_stated_queries']
  summary['post_wrap_confidential_outgoing_events']=next(q['events'] for q in boundary['query_counts'] if q['kind']=='confidential_from_wallet')
  summary['post_wrap_confidential_incoming_events']=next(q['events'] for q in boundary['query_counts'] if q['kind']=='confidential_to_wallet')
  summary['post_wrap_public_wrap_events']=len(wraps)
  summary['post_wrap_receiver_wallet_unwrap_finalized_events']=next(q['events'] for q in boundary['query_counts'] if q['kind']=='unwrap_to_wallet')
  summary['post_wrap_public_amount_disclosures']=next(q['events'] for q in boundary['query_counts'] if q['kind']=='public_amount_disclosures')
  summary['post_wrap_additional_receipts']=boundary['receipt_transactions_added']
 primary_links=[{'title':'Morpho Blue borrowing and interest accrual source','url':'https://github.com/morpho-org/morpho-blue/blob/main/src/Morpho.sol','supports':'Pending interest and repayment share accounting.'},{'title':'Morpho Blue three-term interest expansion','url':'https://github.com/morpho-org/morpho-blue/blob/main/src/libraries/MathLib.sol','supports':'Exact pending-interest formula.'},{'title':'Morpho Vault V2 fee and redemption mechanics','url':'https://github.com/morpho-org/vault-v2/blob/main/src/VaultV2.sol','supports':'Fee dilution and standard redemption mechanics; deployed verified source is also captured.'},{'title':'Official Zama confidential wrapper registry and explanation','url':'https://www.zama.org/confidential-tokens','supports':'Official cUSDC address and encrypted balances and transfer amounts.'},{'title':'Zama confidential wrapper control source','url':'https://github.com/zama-ai/protocol-apps/blob/main/contracts/confidential-wrapper/contracts/ConfidentialWrapper.sol','supports':'Owner, observer, pause, denylist and upgrade permissions; the exact implementation at T is separately identified and captured.'},{'title':'Silo V1 official repository','url':'https://github.com/silo-finance/silo-core-v1','supports':'Official deployments and historical lens methods.'}]
 findings=[{'title':'Vault income did not cover the measured borrowing cost','text':'The two borrowed USDC lots receive an allocated 91.840383 USDC of vault income but incur about 239.889887 USDC of funding cost by redemption. Their allocated funded result at that exit is approximately -148.049504 USDC before gas. This is a lot allocation and debt valuation, not a measured repayment or whole-wallet cash profit. The PYUSD sequence receives 1.948867 PYUSD above its deposit. Borrowing cost, including the exact residual liability in the repayment-block state, is 2.347298 PYUSD. Its funded result is -0.398431 PYUSD before gas.'},{'title':'The USDC exit enters a verified confidential wrapper','text':'The full 1,700,553.396390 USDC redemption is wrapped into Zama cUSDC for the same wallet eight minutes later. Public data establish the amount and recipient at this boundary. They do not reveal a complete subsequent allocation or prove that the loan was repaid.'},{'title':'The PYUSD exit leaves debt and collateral','text':'The wallet redeems every PYUSD vault share, repays 1,000,001 PYUSD and withdraws 699.994930347918797441 weETH. The repayment-block state retains 1.347298 PYUSD of debt and 0.005069652081202559 weETH. The borrow shares and collateral remain at T, and interest continues.'},{'title':'Vault fees are already reflected in the measured cash income','text':'The deployed USDC vault has a 10% performance fee and the PYUSD vault has a 15% performance fee at exit and T. Both have a zero management fee in those observations. Standard redemption uses a fee-aware share conversion. The measured income must not be reduced by the headline performance fee a second time.'},{'title':'Selected legacy Silo ETH markets have little XAI debt at T','text':'Three official Ethereum V1 ETH-family markets were read with the legacy repository and lens. Their XAI bridge debt totals about 1.79602246 XAI. This is a selected market total in XAI units. It is not a peg-adjusted dollar value or a census of all Silo markets. Historical Arbitrum reads remain unavailable.'}]
 missing=['Public confidential-token balances and post-wrap allocation require authorised decryption or a disclosed statement.','The completed cUSDC wallet-filtered event census does not trace every other receiver or reconstruct full-wallet debt and reward history.','Separate cash flows cannot establish exclusive funding by fungible loan proceeds. Pro-rata lot return is a stated analytical allocation.','Destination share income includes deployed vault fees. Other rewards, collateral staking income, wallet assets, gas-to-USD conversion, taxes and any outside fees are not included in whole-wallet profit, which remains unknown.','No beneficial owner is verified for either borrower. A historical lending-to-yield route does not identify the whole wallet or its current carry allocation.','Other Silo factory generations, legacy assets and account-level collateral allocation remain outside the bounded registry and selected market reads.']
 if registry_observations:
  findings[-1]['title']='Selected Silo deployments have little measured dollar-token debt'
  findings[-1]['text']='Three selected Ethereum V1 ETH-family markets have about 1.79602246 XAI of bridge debt. Two selected Arbitrum V1 ETH-family markets have 212.334440 units of bridged USDC debt. These are entire bridge-asset loan totals in selected Silos, not a verified dollar valuation or a census of all Silo markets. The earlier Arbitrum archive errors are repaired through a public Blast endpoint at the unchanged snapshot block.'
  findings.append({'title':'The repaired Arbitrum factory contains four canonical lending pairs','text':'All 13 configurations and 26 silo assets are resolved in the examined Arbitrum factory generation. Four configurations pair canonical WETH with native USDC; together they have 0.088410 USDC of debt with interest at T. This measures a dated generation rather than implying that all Silo deployments are empty or small.'})
 if boundary:
  findings.append({'title':'The confidential route is visible, but its quantities remain private','text':'The complete stated cUSDC wallet queries find two outgoing encrypted-transfer events, eight incoming events and two public wraps through T. The second wrap adds 2,002,038.655059 USDC on 17 September. Receipts show confidential batch Joined events and the verified deposit batcher\'s Quit events returning encrypted cUSDC. No receiver-wallet UnwrapFinalized event or public AmountDisclosed event is observed in this wrapper and window. These are public routing and refund events, not measured positive confidential quantities or proof of a completed yield investment.'})
 inputs=[D/'credit_expansion.json',D/'credit_expansion_deep_capture.json',D/'credit_expansion_deep_state.json',D/'credit_expansion_deep_funding.json',D/'credit_expansion_deep_wrapper.json',D/'credit_expansion_deep_silo_legacy.json',D/'credit_expansion_deep_fees.json',D/'credit_expansion_deep_bytecode.json']
 if silo_arb_path.exists():inputs.append(silo_arb_path)
 if destination_metadata_path.exists():inputs.append(destination_metadata_path)
 if boundary_path.exists():inputs.append(boundary_path)
 out={'schema_version':2,'summary':summary,'cases':cases,'chronology':timeline,'terminal_states':terminal,'confidential_wrapper':privacy,'post_wrap_public_boundary':boundary,'fee_observations':fee_observations,'legacy_markets':legacy,'registry_observations':registry_observations,'findings':findings,'missing_public_inputs':missing,'primary_links':primary_links,'sources':records,'inputs':[{'path':str(p.relative_to(ROOT)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in inputs]}
 (D/'credit_expansion_deep.json').write_text(json.dumps(out,indent=2));print(json.dumps(summary,indent=2))

if __name__=='__main__':build()
