"""Frozen-position sensitivities; never label them executable P&L forecasts."""
import json,math
from collect import ROOT,T

def run():
 d=ROOT/'data/eth';r=lambda n:json.loads((d/(n+'.json')).read_text());m=r('etherfi_verified_metrics');res=r('lending_reserve_T')['decoded'];comp=next(x for x in r('etherfi_staking_comparison') if x['days']==30)
 bal=r('balances_ethereum_T');debts={bal['labels'][x['id']-1]['symbol']:int(x['result'],16)/1e18 for x in bal['responses'] if x.get('result')}
 out=[]
 for pool,symbol,receipt in [('aave','variableDebtEthWETH','weETH'),('spark','variableDebtWETH','stETH')]:
  a=next(x for x in m['aave_spark_accounts'] if x['position']=='main_'+pool);loan=next(x for x in res if x['pool']==pool and x['asset'].startswith('0xc02'));coll=next(x for x in res if x['pool']==pool and not x['asset'].startswith('0xc02'))
  s=math.log1p(comp[receipt+'_cumulative_return'])*365/30+coll['supply_APR'];b=loan['variable_borrow_APR'];L=a['gross_leverage'];R=L*s-(L-1)*b
  row={'account':pool,'target_timestamp':T,'collateral_leverage':L,'staking_plus_supply_APR_proxy':s,'current_variable_borrow_APR':b,'modeled_annual_equity_return_before_fees_rewards_costs':R,'borrow_APR_zero_return_break_even':L*s/(L-1),'borrow_increase_bp_to_zero_return':(L*s/(L-1)-b)*10000,'borrow_increase_bp_to_erase_loop_uplift':(s-b)*10000,'debt_WETH_units':debts[symbol],'reserve_WETH_cash_units':loan['underlying_cash_units'],'reserve_cash_over_main_debt':loan['underlying_cash_units']/debts[symbol],'isolated_borrow_shocks':{str(bp):R-(L-1)*bp/10000 for bp in [25,50,100,300]},'note':'Staking proxy is trailing-30d log return annualized; borrow/supply APR is instantaneous T. Hybrid frozen-rate illustration, no forecast, no rewards, manager fees or execution; cash does not establish flash-loan eligibility.'}
  out.append(row)
 (d/'loop_economics_T.json').write_text(json.dumps(out,indent=2))
 lines=['# Экономика, предельная ёмкость и стрессы','', 'Срез T — 2 октября 2026, 23:59:59 UTC. Здесь отделены contract state, model sensitivity и ещё не выполненная execution simulation.','', '## ETH loops: небольшой spread усилен большим плечом','', 'Для модели берём trailing-30d staking log return, annualized в APR, плюс текущий collateral supply APR. WETH debt использует instantaneous variable borrow APR на T. Это смешанное proxy-окно для разбора экономики, без claims о будущей или исторически реализованной прибыли. Rewards, management/performance fees и execution costs исключены.','', '| Account | L | Staking + supply APR proxy | WETH borrow APR на T | Модель return на equity | Borrow uplift до zero return | Uplift до исчезновения loop excess |','|---|---:|---:|---:|---:|---:|---:|']
 for x in out:lines.append(f"| {x['account']} | {x['collateral_leverage']:.3f} | {x['staking_plus_supply_APR_proxy']*100:.3f}% | {x['current_variable_borrow_APR']*100:.3f}% | {x['modeled_annual_equity_return_before_fees_rewards_costs']*100:.3f}% | {x['borrow_increase_bp_to_zero_return']:.1f} bp | {x['borrow_increase_bp_to_erase_loop_uplift']:.1f} bp |")
 lines+=['', 'Даже при positive staking APR усиленная стратегия теряет привлекательность при десятках basis points дополнительного debt cost. Эти thresholds относятся к выбранной модели. Variable rate может изменяться вместе с supply yield, staking yield, utilization и размером позиции.','', '## Rate shocks на фиксированном equity','', '| Account | +25 bp | +50 bp | +100 bp | +300 bp |','|---|---:|---:|---:|---:|']
 for x in out:lines.append('| '+x['account']+' | '+' | '.join(f"{x['isolated_borrow_shocks'][str(bp)]*100:.3f}%" for bp in [25,50,100,300])+' |')
 lines += ['', 'Main Aave +100 bp даёт −12,3245 п.п. годового дохода на account equity и около −2,3136 п.п. на Liquid ETH book NAV до возможных offsets. Изолированный shock нельзя складывать с изменённой lender income, не выполнив полный asset/debt look-through.','', '## Доступный debt asset и закрытие','', '| Account | Main WETH debt | WETH reserve cash | Cash / debt |','|---|---:|---:|---:|']
 for x in out:lines.append(f"| {x['account']} | {x['debt_WETH_units']:,.2f} | {x['reserve_WETH_cash_units']:,.2f} | {x['reserve_cash_over_main_debt']*100:.2f}% |")
 lines += ['', 'Aave reserve cash меньше WETH долга main loop. Одновременный полный repayment через один flash loan только этого резерва ограничен наблюдаемым cash. Это не доказательство невозможности выхода: возможны другие lenders, собственная ликвидность, collateral redemption и поэтапные операции. Spark cash больше долга этого account, но eligibility, caps и route не симулированы.','', 'Ставки прочитаны через 15-word legacy getReserveData layout. WETH cash измерен `balanceOf(aTokenAddress)` на том же fixed block, а debt — balance соответствующего variableDebt token. Max withdraw/flashloan зависит также от paused state, reserve rules и исполнения.','', '## Oracle, market discount и stable debt','', '| Account | HF на T | Изолированный oracle markdown до HF=1 | Borrow +100bp: изменение return equity |','|---|---:|---:|---:|']
 for x in r('stress_scenarios'):lines.append(f"| {x['account']} | {x['HF']:.5f} | {x['oracle_markdown_to_HF_1']*100:.3f}% | {x['borrow_plus_100bp_isolated_equity_return_change_pp']:.3f} п.п. |")
 lines+=['', 'Для ETH debt LST/ETH oracle markdown важнее ETH/USD direction. У stable debt падение ETH/USD действует на HF через collateral value, если stable loan и LT фиксированы. Drone Aave при −20% ETH collateral shock сохраняет HF около 1,112; при −40% HF около 0,834. Это arithmetic sensitivity, без фактического liquidation quote и rebalancing.','', 'DEX discount отдельно меняет исполнимую стоимость выхода. В Aave weETH CAPO source не обязан отслеживать DEX discount. Для principal-only estimate 1% markdown всего collateral уменьшает account equity примерно на L%; точные smart collateral/LP изменения требуют пересчитать pool reserves и liquidity ranges.','', '## Carry: риск кредита и связанных денежных потоков','', 'Dollar-leg loss проходит в ETH book NAV через долю инвестора и ETH conversion. Self-credit diagnostics 8,709 млн RLUSD и 4,759 млн PYUSD показывают связанность borrower и lender потоков; они не являются доступной кассой и не удваивают активы. Curator fees 10%/15% на конкретных carry vaults могут удерживаться даже когда часть borrower payments возвращается собственному инвестору.','', 'Для PRIME/PYUSD проверенное market utilization около 91,8%, для weETH/RLUSD около 88,3%. Current outstanding loan и наличная supply liquidity различаются. Recovery collateral с внебиржевой кредитной зависимостью нельзя считать мгновенной ликвидностью ETH.','', '## Capacity: чего пока нельзя утверждать','', 'Предельная ёмкость не равна protocol TVL. Для E3 минимум определяется LST liquidity/redemption, ETH borrow liquidity, caps, HF и допустимым drawdown. Для E4 добавляются USD borrow capacity, destination yield cap, credit terms и redemption duration. Для E9 — hedge open interest, funding curve, venue margin и custody limits.','', 'Полная stress execution пока открыта: архивные executable DEX quotes, flash-loan eligibility, redemption queue throughput, liquidation transactions, bridge settlement delay и rates/funding paths на 7/30/90 дней. Таблицы выше сохраняют model assumptions и не подменяют эту проверку. Данные: `loop_economics_T.json`, `lending_reserve_T.json`, `stress_scenarios.json`.']
 (ROOT/'research/eth/ECONOMICS.md').write_text('\n'.join(lines)+'\n');print([(x['account'],x['borrow_increase_bp_to_zero_return'],x['reserve_cash_over_main_debt']) for x in out])

if __name__=='__main__':run()
