"""Integrate measured additions into the existing research articles, after legacy builders."""
from finalization_reconstruction_build import EN,D,read,DETAILS
from report_contract_build import table

def run():
 f=read('finalization_reconstruction');pc=read('reader_product_chapters')['products'];c=read('report_contract')
 native=f['native'];paragraph=f"The archived consensus state at T has **{native['activeBalanceETH']:,.3f} actual active ETH**, **{native['activeEffectiveBalanceETH']:,.0f} effective active ETH** and **{native['activeValidatorCount']:,} active validators**. Actual balance and effective stake answer different questions. The active set includes {native['statusCounts']['active_exiting']:,} exiting validators. These balances are measured directly from validator objects, including compounding validators; they are not validator count multiplied by 32. Receipt claims are a separate, overlapping layer."
 native_text='\n\n## Native stake: measured backing, not another wrapper\n\n'+paragraph+'\n\nThe archived slot is **15346798**, state root `'+native['stateRoot']+'`. The public provider marks the response finalized and execution optimistic. The header state root agrees with the saved header; we do not claim an independent state-root recomputation from the validator JSON. Five successful monthly state reads cover May to September 2026. Earlier headers exist but their complete states are pruned at the tested public endpoints. Those missing balances remain absent.\n\n[Archived state endpoint]('+native['source']['url']+'), [monthly observations](../../../data/eth/native-staking-observations.csv), [normalised reconstruction and receipt hashes](../../../data/eth/finalization_reconstruction.json).\n'
 for name in ['BRIEFING','MARKET-STRUCTURE','CAPITAL-INCOME-EXIT','MARKET-COVERAGE']:
  path=EN/(name+'.md');s=path.read_text();s=s.replace('Full historical consensus state was unavailable from the tested public sources.', 'An exact active-validator state is now measured at T; earlier full states are pruned at tested public sources.').replace('Native staking is not measured at T.', 'Native active stake is measured separately at T.')
  path.write_text(s+native_text)
 notes='\n\n## Additional carry books: fixed-block reconstruction\n\nThe final census includes **13 carry-linked books**, of which **10 have current traced routes**. Lido Earn and Avant enter the five largest examined books. Makina DETH, Vesper and ZenSats add distinct smaller routes. Whole books, dollar loans, investment claims and carry equity are kept separate.\n\n'
 for p in pc:
  if not p.get('newReconstruction'):continue
  notes+='## '+p['name']+'\n\n'+p['story']['text']+'\n\n**'+p['story']['lesson']+'**\n\n'
  for step in p['moneyFlow']:notes+='### '+step['title']+'\n\n'+step['text']+'\n\n'
  notes+=table(['Borrowing venue','Debt currency','Actual / stored debt units','Health factor','Scope'],[[r['protocol'],r['debtAsset'],f"{r.get('debtUnits',0):,.6f}",'Different model / not independently measured'if r.get('healthFactor')is None else f"{r['healthFactor']:.6f}",r['scope']]for r in p['charts']['loanLegs']['rows']])+'\n\n'
  notes+='**Holder distribution:** '+p['keyMetrics'][1]['value']+'. '+p['charts']['walletDistribution']['scope']+'\n\n'
  notes+='**Size convention:** '+p['capitalBasis']+'. **Matched claim return:** '+f"{p['charts']['returnVsBorrow']['windowReturns'][0]['cumulativeReturnPct']:+.4f}%"+' from 2 September to 2 October 2026.\n\n'
  notes+='**Fee and exit detail:** '+p['comparison']['fees']+'.\n\n'+table(['Actor','Control'],[[r['who'],r['role']]for r in p['actors']])+'\n\n'
  notes+='**Evidence limits:** '+' '.join(p['limitations'])+'\n\n'+', '.join('['+r['label']+']('+r['url'].replace('data/','../../../data/eth/')+')'for r in p['sources'])+'.\n\n'
 path=EN/'CARRY-PRODUCTS.md';path.write_text(path.read_text()+notes)
 ledgers=f['flowAdjustedLedgers'];lot=f['directFinancedLot']
 econ='\n\n## Two additional dollar investment and funding ledgers\n\nAll figures below use **2 September to 2 October 2026**. New borrowing and repayments are removed from debt growth; share acquisitions and redemptions are removed from investment-value growth. External rewards, gas and executable exit costs are separate.\n\n'
 econ+=table(['Account','Debt token','Investment share-price income','Full-account interest','Difference, before other items'],[[r['id'],r['currency'],f"{r['investmentSharePriceIncome']:,.6f}",f"{r['accruedFundingCost']:,.6f}",f"{r['claimIncomeLessFullAccountInterest']:+,.6f}"]for r in ledgers])+'\n\n'
 econ+='Lido’s opening investment includes **9,855,091 already allocated but unclaimed earnUSD shares**. Their later mint is not new capital. The account also sends **13,304,800 USDT back to the stRATEGY parent** during the window. Its investment claim starts around $20.49M while debt starts around $7.18M; the full-account difference is therefore not a matched-principal carry return.\n\nVesper’s opening and closing vDAI balances reconcile exactly to the saved mint and burn events. The **13.50 DAI** of share-price income is below **452.50 DAI** of accrued funding. Reinvested reward purchases are treated as acquisition flows, so this comparison does not establish the result after external incentives.\n\n'
 econ+='### A directly matched 5M USDT investment\n\nOn **29 September 2026 at 05:59:35 UTC**, one transaction borrows **5,000,000 USDT** from Aave and transfers it to the earnUSD deposit queue. The newly allocated economic claim is **4,838,244.259 earnUSD shares**, worth exactly 5M USDT at the transaction’s archived oracle mark. The 9.855M old allocated shares minted in the same transaction are excluded.\n\nAt T, the new claim has gained **3,651.565 USDT**. The allocated indexed loan interest is **2,250.992 USDT**, leaving **1,400.573 USDT before gas and outer fees**. This is a positive recognised-claim spread over about 3.75 days; it is not a realised cash exit, an organic-income decomposition or a sustainable annual quote. No later account repayment appears before T.\n\n[Borrowing and investment transaction]('+lot['receipt']+'), [flow-adjusted CSV](../../../data/eth/carry-flow-adjusted-ledgers.csv), [normalised ledger](../../../data/eth/finalization_financial_ledgers.json).\n'
 for name in ['BRIEFING','CARRY-MATH','CARRY-LIFECYCLES','CAPITAL-INCOME-EXIT']:
  path=EN/(name+'.md');path.write_text(path.read_text()+econ)
 # The previous discovery review is replaced with the final measured decisions, not kept as an unresolved journal.
 cov=read('carry_coverage_audit');path=EN/'CARRY-COVERAGE-AUDIT.md'
 path.write_text('# Carry coverage and product decisions\n\nFinancial snapshot: **2 October 2026**. Later public discovery locates candidates; contract reads and financial histories use the fixed snapshot.\n\nThe saved DefiLlama screen contains '+str(c['discovery']['materialPools'])+' ETH-name pools above $5M. A match to an existing parent does not establish a reconstructed strategy or additive ETH capital.\n\n'+table(['Product / family','Decision','Evidence'],[[r['product'],r['decision'],r['evidence']]for r in cov['reviewedCases']])+'\n\n'+table(['Examined book','Status','Capital convention / boundary'],[[r['name'],r['statusLabel'],r['allocationEvidence']]for r in c['census']])+'\n\n**YO ETH exclusion:** the saved API contains 606 daily TVL observations from February 2025 to T, with the last observation 87.9 seconds before T at 4,955.87 ETH. Archived Ethereum and Base positions show ETH lending / staking allocations, including IPOR and Morpho receipts. No own dollar loan is established in those inspected positions. The global API book and local oracle-valued share books are overlapping claims, not extra capital.\n\n**ZenSats legacy:** the old vault has zero assets and share supply at T. The active deployment is a measured sub-one-ETH book, included as a micro-position.\n\n[Final reconstruction](../../../data/eth/finalization_reconstruction.json), [status and capital CSV](../../../data/eth/carry-status-and-capital.csv), [material-pool dispositions](../../../data/eth/carry-discovery-dispositions.csv).\n')
 # Later discovery remains dated. Explicitly supersede the earlier allocator decisions.
 for name in ['STRATEGY-UNIVERSE-EXPANSION','CARRY-VARIANTS-EXPANSION','PRODUCT-FINANCIAL-HISTORY']:
  path=EN/(name+'.md');s=path.read_text();title,rest=s.split('\n',1);s=title+'\n\n**Final measurement update, 6 October 2026:** Lido Earn, Avant, Makina DETH, Vesper and active ZenSats now have fixed-block financial reconstructions and matched claim histories. Earlier discovery-only decisions below describe the prior screen; use the [final product chapters](CARRY-PRODUCTS.md) and [coverage decisions](CARRY-COVERAGE-AUDIT.md) for the completed census.\n'+rest
  path.write_text(s)
 # Options and PT: establish funded state without turning a face claim into unique custody.
 detail='\n\n## Fixed-maturity and option capacity at the snapshot\n\nFour active, unexpired Ethereum Pendle markets from the saved registry have verified PT, YT and SY identities at T. Their PT face supplies are **153.219 superWETH**, **123.843 pufETH**, **305.243 stETH** and **5.969 mixWETH** units. SY accounting assets are WETH, native ETH, stETH and WETH respectively. Face supply, market liquidity and underlying unique ETH are different measurements. The zero-address SY asset denotes native ETH, not missing metadata. PT redemption also depends on its conversion index and underlying asset performance. These four markets are an examined active subset, not all fixed-income ETH products.\n\nRibbon ETH Theta has **712.655 ETH of residual reported capital**. Its current option expired on **12 December 2025**. That residual book does not prove active premium selling in October 2026. Thetanuts has a deployed share contract, but the tested public interface does not expose a verified full portfolio valuation; a zero idle WETH balance does not establish zero invested capacity.\n\n[Archived contract states and source hashes](../../../data/eth/finalization_reconstruction.json), [PT identity reads](../../../data/eth/finalization_financial_bindings_T.json), [option-state reads](../../../data/eth/finalization_options_T.json).\n'
 for name in ['MARKET-COVERAGE','STRATEGY-UNIVERSE-EXPANSION','pendle-pt']:
  path=EN/(name+'.md')if name!='pendle-pt'else EN/'dossiers/pendle-pt.md'
  if path.exists():path.write_text(path.read_text()+detail)
 # Update library guide so it leads to the report rather than working plans.
 (EN/'README.md').write_text('# ETH yield research\n\nStart with the [team briefing](BRIEFING.md). The website follows the same eight chapters as Bitcoin Research: answer, market, carry mechanics, Top 5, other carry products, risks, product design and evidence.\n\n[Market structure](MARKET-STRUCTURE.md), [carry history](CARRY-CATEGORY.md), [product mechanisms](CARRY-PRODUCTS.md), [funding and return calculations](CARRY-MATH.md), [coverage decisions](MARKET-COVERAGE.md).\n\nFinancial state is frozen at 2 October 2026. Discovery documents dated later identify additional deployments; they do not replace archived financial values.\n')
 print('Final editorial: native backing, five product mechanisms, flow-adjusted economics, PT and option states integrated.')
