"""Selected WETH market sizes, concentration and explicit reserve accounting gaps."""
import json
from collect import ROOT,T

def run():
 d=ROOT/'data/eth';x=json.loads((d/'weth_lending_markets_T.json').read_text());ms=x['markets'];assert len(ms)==5 and all('lender_claim_units'in m for m in ms)
 balances=json.loads((d/'balances_ethereum_T.json').read_text());bb={balances['labels'][r['id']-1]['symbol']:int(r['result'],16)/1e18 for r in balances['responses'] if r.get('result')}
 a=next(m for m in ms if m['protocol']=='aave' and m['chain']=='ethereum');sp=next(m for m in ms if m['protocol']=='spark');summary={'target_timestamp':T,'selected_WETH_lender_claims':sum(m['lender_claim_units'] for m in ms),'selected_WETH_debt':sum(m['debt_units'] for m in ms),'selected_WETH_cash':sum(m['reserve_cash_units'] for m in ms),'selected_Aave_getReserveDeficit_WETH':sum(m['extra_getters'].get('getReserveDeficit(address)') or 0 for m in ms if m['protocol']=='aave'),'Liquid_ETH_main_share_of_Aave_Ethereum_variable_WETH_debt':bb['variableDebtEthWETH']/a['variable_debt_units'],'Liquid_ETH_main_share_of_Spark_variable_WETH_debt':bb['variableDebtWETH']/sp['variable_debt_units'],'net_unique_market_size':None,'note':'Five selected WETH lender claim markets. Receipt claims/debt can overlap across underlying strategies. Reserve deficits are observed state, not final investor loss or recovery attribution.'}
 (d/'weth_lending_summary_T.json').write_text(json.dumps(summary,indent=2))
 lines=['# WETH lending: размер выбранного сегмента и проверка баланса','', 'Срез T: 2 октября 2026, 23:59:59 UTC. Охват: Aave V3 Ethereum, Base, Arbitrum, Optimism и Spark Ethereum. Addresses получены из primary address book и сверены `getReserveData` на fixed block; WETH cash, aToken claims и debt token supply прочитаны на том же блоке.','', '## Сколько требований и долга','', '| Протокол / сеть | Lender claims, WETH | Outstanding debt, WETH | Reserve cash, WETH | Supply APR на T | Borrow APR на T |','|---|---:|---:|---:|---:|---:|']
 for m in ms:lines.append(f"| {m['protocol']} / {m['chain']} | {m['lender_claim_units']:,.2f} | {m['debt_units']:,.2f} | {m['reserve_cash_units']:,.2f} | {m['supply_APR']*100:.3f}% | {m['variable_borrow_APR']*100:.3f}% |")
 lines += ['', f"Выбранные пять markets имеют **{summary['selected_WETH_lender_claims']:,.2f} WETH lender claims** и **{summary['selected_WETH_debt']:,.2f} WETH outstanding debt**. Cash — {summary['selected_WETH_cash']:,.2f} WETH. Это gross lending-claim segment: его нельзя складывать с LST backing или выдавать за уникальный ETH yield капитал.", '', f"Main Liquid ETH account создаёт **{summary['Liquid_ETH_main_share_of_Aave_Ethereum_variable_WETH_debt']*100:.2f}%** variable WETH debt Aave Ethereum и **{summary['Liquid_ETH_main_share_of_Spark_variable_WETH_debt']*100:.2f}%** variable WETH debt Spark. Доли относятся к одному проверенному borrower account, без добавления всех потенциально связанных borrowers. Это прямая связь demand for ETH loans с managed yield loop.", '', '## Reserve deficit и claims не равны cash + обслуживаемый debt','', '| Сеть Aave | getReserveDeficit(WETH), WETH | Deficit / lender claims | Claims − cash − debt, WETH |','|---|---:|---:|---:|']
 for m in ms:
  if m['protocol']!='aave':continue
  v=m['extra_getters'].get('getReserveDeficit(address)');lines.append(f"| {m['chain']} | {v:,.6f} | {v/m['lender_claim_units']*100:.4f}% | {m['lender_claim_minus_cash_and_debt_units']:,.6f} |")
 lines += ['', 'Aave Ethereum показывает 52 964,453913 WETH reserve deficit; Arbitrum 29 835,199567 WETH. Это значения контрактного getter на T, а не цифры, выведенные только из расхождения двух subtotal. В Optimism/Base значения малы. Spark аналогичные getters в проверенных RPC responses недоступны; ему не присвоен нулевой deficit.', '', '[Определение Aave v3.3](https://github.com/aave-dao/aave-v3-origin/blob/main/docs/3.3/Aave-v3.3-features.md) описывает reserve deficit и permissioned механизм его уменьшения с burn aTokens. Сравнение claims−cash−debt не обязано точно равняться stored deficit: присутствуют treasury accounting, accrued indexes, виртуальные balances и rounding. Здесь разница с getter сохранена, не насильно сведена к нулю.', '', 'Deficit / claims — показатель состояния reserve accounting, **не доказанный haircut держателя aToken**. Recovery assets, внешние компенсации и механика дальнейшего погашения должны быть учтены отдельно. Наличие normal APR или восстановление операционной ликвидности не доказывает, что deficit ledger уже очищен.', '', '## Incident attribution и предел вывода', '', '[Aave service-provider report от 20 апреля](https://governance.aave.com/t/rseth-incident-report-april-20-2026/24580) описывает переход bridge incident rsETH в WETH borrowing exposure на Ethereum/Arbitrum и сценарии покрытия. [Майский update Aave Labs](https://governance.aave.com/t/al-development-update-may-2026/25013) сообщает о ликвидациях, recovery guardian и восстановлении ETH liquidity. Эти disclosures дают контекст; каждый outstanding deficit на T ещё не привязан здесь к полному event-level recovery waterfall.', '', 'Поэтому исследования только staking APY или isolated smart-contract risk недостаточно: качество receipt/bridge collateral способно повлиять на reserve, где lender держит WETH. Отдельно нужно анализировать доход, cash для withdrawals, debt collectability и право на recovery. Не следует интерпретировать указанные текущие состояния как прогноз потерь или как законченный аудит Aave.', '', 'Данные и полные request/response pairs: `weth_lending_markets_T.json`; итоговые числа — `weth_lending_summary_T.json`. Getters проверяются на fixed block каждой сети; historical borrowed state не заменён current UI.']
 (ROOT/'research/eth/LENDING-MARKETS.md').write_text('\n'.join(lines)+'\n');print(summary)

if __name__=='__main__':run()
