"""Reconcile the additional hgETH loan book from fixed-block public reads."""
import hashlib,json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];DATA=ROOT/'data/eth'
def run():
    path=DATA/'manager_case_capture.json';d=json.loads(path.read_text());T=d['snapshot_timestamp']
    def view(month,sig):
        r=next(r for r in d['state'] if r['label']['month']==month and r['label']['signature']==sig)
        return int(r['response']['result'],16)
    conversion={r['label']['month']:int(r['price_response']['result'],16)/1e18 for r in d['oracle_history']}
    history=[]
    for month in conversion:
        label=next(r['label'] for r in d['state'] if r['label']['month']==month)
        assets=view(month,'totalAssets()')/1e18;shares=view(month,'totalSupply()')/1e18;pps=view(month,'convertToAssets(uint256)')/1e18
        history.append({'date':month,'timestamp':label['timestamp'],'block':label['block'],'bookRsETH':assets,'shares':shares,'rsETHPerShare':pps,'ETHPerShare':pps*conversion[month],'bookETH':assets*conversion[month],'rsETHtoETH':conversion[month]})
    history.sort(key=lambda r:r['timestamp']);start=history[0];current=history[-1]
    for h in history:h['ETHBookChangePct']=(h['ETHPerShare']/start['ETHPerShare']-1)*100
    loan=int(d['loan_and_exit_views'][1]['result'],16)/1e18;cash=view('snapshot_T','rsETH buffer balance')/1e18
    fee=view('snapshot_T','totalCollectableFees()')/1e18
    reservedETH=int(d['adapter_reserves'][0]['result'],16)/1e18;adapterRate=int(d['adapter_reserves'][1]['result'],16)/1e18;reservedRsETH=reservedETH*adapterRate
    reconstructed=loan+cash-fee+reservedRsETH;residual=current['bookRsETH']-reconstructed
    records=[json.loads(s) for s in (ROOT/d['raw_manifest']).read_text().splitlines()]
    source_record=next(r for r in reversed(records) if r['key']=='hg_implementation_source' and r.get('path'))
    src=json.loads((ROOT/source_record['path']).read_text());bound=src['deployed_bytecode']==d['loan_and_exit_views'][4]['result']
    owner='0x'+hex(view('snapshot_T','owner()'))[2:].zfill(40)
    owner_words=[int(d['control'][2]['result'][i:i+64],16) for i in range(2,len(d['control'][2]['result']),64)]
    owners=['0x'+hex(w)[2:].zfill(40) for w in owner_words[2:]]
    additional={r['signature']:int(r['response']['result'],16) if r['response'].get('result') else None for r in d.get('additional_views',[])}
    price=json.loads((DATA/'strategy_universe_deep.json').read_text())['snapshot']['ETH_USD']
    result={'snapshot_timestamp':T,'block':26108081,'name':'Kernel Gain hgETH','address':d['address'],'asset':d['asset'],'capitalETH':current['bookETH'],'capitalUSD':current['bookETH']*price,'bookRsETH':current['bookRsETH'],'physicalRsETH':cash,'loanBookRsETH':loan,'reservedAdapterETH':reservedETH,'reservedAdapterRsETH':reservedRsETH,'collectableFeesRsETH':fee,'reconciliationResidualRsETH':residual,'loanRegistryCount':len(d['loan_registry']),'history':history,'fees':{'managementPercentRaw':view('snapshot_T','managementFeePercent()'),'withdrawalFeeRaw':view('snapshot_T','withdrawalFee()'),'scope':'Both measured fee getters are zero at T. Mutable administration and other loan-level charges remain separate.'},'control':{'owner':owner,'threshold':int(d['control'][1]['result'],16),'signers':owners,'settlementAccount':'0x'+hex(view('snapshot_T','settlementAccount()'))[2:].zfill(40),'loansOperator':'0x'+hex(view('snapshot_T','loansOperator()'))[2:].zfill(40),'implementation':'0x'+d['control'][0]['result'][-40:],'runtimeMatchesVerifiedSource':bound},'exit':{'depositsPaused':bool(view('snapshot_T','depositsPaused()')),'withdrawalsPaused':bool(view('snapshot_T','withdrawalsPaused()')),'queriedCaller':owner,'callerMaxWithdrawRsETH':int(d['loan_and_exit_views'][3]['result'],16)/1e18,'callerMaxRedeemShares':int(d['loan_and_exit_views'][2]['result'],16)/1e18,'maxWithdrawalAmountRaw':additional.get('maxWithdrawalAmount()'),'lagDurationSeconds':additional.get('lagDuration()'),'scope':'Owner-specific getters, cash balances and configured delays do not prove a holder payout or portfolio-wide exit capacity.'},'carryUseVerified':False,'wholeInvestorProfit':None,'sources':[{'path':str(path.relative_to(ROOT)),'sha256':hashlib.sha256(path.read_bytes()).hexdigest()},source_record,{'path':'data/eth/strategy_universe_deep.json','sha256':hashlib.sha256((DATA/'strategy_universe_deep.json').read_bytes()).hexdigest()}],'sourceURLs':['https://etherscan.io/address/'+d['address'],'https://eth.blockscout.com/api/v2/smart-contracts/0x4ffe25598489c7259dc9686a2cba0507177bcf7f'],'limits':['The active-loan accounting amount is measured, but 173 registry entries include historical loans and are not 173 active positions.','Individual borrower identity, collateral, rate history, repayments and underlying portfolio allocation remain unclassified in this case.','rsETH and hgETH marks are accounting conversions, not sale prices or paid withdrawal proceeds.','A loan-originating rsETH wrapper is not automatically ETH-collateral dollar carry.']}
    assert bound and abs(residual)<1e-8 and len(owners)==5 and result['control']['threshold']==3
    assert math.isclose(result['capitalETH'],result['bookRsETH']*conversion['snapshot_T'])
    (DATA/'manager_case_chapter.json').write_text(json.dumps(result,indent=2)+'\n')
    article=['# hgETH: an rsETH loan book, not an unexplained yield label','','Financial state is measured at 2 October 2026, 23:59:59 UTC, Ethereum block 26,108,081. The implementation runtime at that block exactly matches the captured verified source.','','## What the holder owns','',f"The hgETH share is a claim on an rsETH-denominated loan pool. Its fixed-T book is {current['bookRsETH']:,.6f} rsETH, equivalent to {result['capitalETH']:,.6f} ETH or ${result['capitalUSD']:,.0f} under the stated rsETH conversion and ETH quote. This nested claim must not be added to rsETH issuer backing as new physical ETH.",'','The implementation accounts for active loan exposure, underlying tokens held by the pool, collectable fees and reserved ETH in a configured adapter. Interest and loan repayments are possible payers. The public loan-book getter does not establish each borrower rate or identify a dollar reinvestment route.','','## Reconcile the book before quoting yield','','| Component | rsETH |','|---|---:|',f'| Active-loan accounting exposure | {loan:,.9f} |',f'| Physical rsETH in the pool | {cash:,.9f} |',f'| Reserved adapter claim, converted to rsETH | {reservedRsETH:,.9f} |',f'| Collectable fees, deducted | {fee:,.9f} |',f'| Reconstructed total | {reconstructed:,.9f} |',f'| Difference from totalAssets | {residual:.12f} |','','The 173 deployed-loan registry entries are an all-time registry at T. Closed entries can remain present; the count is not active loan count, borrower count or current investment count. The aggregate loan exposure is a book accounting quantity rather than immediately available rsETH.','','## The share mark can fall','','| Date | Product book, ETH | rsETH per share | ETH per share | ETH share-value change from first endpoint |','|---|---:|---:|---:|---:|']
    for h in history:article.append(f"| {h['date']} | {h['bookETH']:,.3f} | {h['rsETHPerShare']:.9f} | {h['ETHPerShare']:.9f} | {h['ETHBookChangePct']:.3f}% |")
    article+=['','These are four sampled endpoints. The share-value decline is not a continuous maximum drawdown, a proven realized investor loss or evidence of its cause. The measure excludes separately paid rewards, sale discounts and execution costs. The rsETH conversion itself is an issuer accounting mark.','','## Fees, authority and exit','',f"The measured management and withdrawal fee getters are zero at T. The owner and settlement account are the same Safe, with a measured {result['control']['threshold']}-of-{len(owners)} owner threshold. The loans operator is a separate address. Signer names, Safe modules, full authorization history and loan-level charges are not assigned.",'',f"Deposits paused: {result['exit']['depositsPaused']}. Withdrawals paused: {result['exit']['withdrawalsPaused']}. The pool holds only {cash:,.6f} physical rsETH against {current['bookRsETH']:,.6f} rsETH of book value. The queried owner's maxWithdraw and maxRedeem both return zero. That is a caller-specific result, not a statement that all holders can withdraw zero.",'','Request, processing and claim paths depend on the configured loan and withdrawal machinery. No investor payout receipt is claimed here. Loan repayments, adapter settlement and share redemption must be tested separately before estimating executable exit capacity.','','## Carry classification and remaining work','','This contract adds a material, publicly measured rsETH lending wrapper to the market investigation. It does not prove ETH-collateral dollar carry. Individual loans still require borrower identity, collateral, rate and repayment evidence before their economic route or realized income can be classified.','','[Structured case](../../../data/eth/manager_case_chapter.json), [captured fixed-block calls](../../../data/eth/manager_case_capture.json).','',f"[Pool](https://etherscan.io/address/{d['address']}) and [fixed-T-bound implementation source](https://eth.blockscout.com/api/v2/smart-contracts/{result['control']['implementation']})."]
    (ROOT/'research/eth/en/HGETH-LOAN-BOOK.md').write_text('\n'.join(article)+'\n')
    print('hgETH fixed-block book reconciled; actual carry use and individual loan income remain unclassified.')
if __name__=='__main__':run()
