"""Additional offline analysis for the colleague edition, with explicit measurement limits."""
import collections,datetime as dt,hashlib,json,math
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];DATA=ROOT/'data/eth';EN=ROOT/'research/eth/en';T=1790985599
read=lambda n:json.loads((DATA/(n+'.json')).read_text())
def stamp(t):return dt.datetime.fromtimestamp(t,dt.timezone.utc).strftime('%Y-%m-%d')
def write(n,d):(DATA/(n+'.json')).write_text(json.dumps(d,indent=2))
def run():
 points={r['target_timestamp']:r for r in read('etherfi_history_points')};months=read('etherfi_history_monthly');growth=[]
 for month in months:
  end=points[month['end_timestamp']];first=dt.datetime.fromtimestamp(month['end_timestamp'],dt.timezone.utc).replace(day=1,hour=0,minute=0,second=0);start=points[int(first.timestamp())-1]
  rate=0;supply=0
  for sk,pk in [('ethereum_liquidETH_supply','liquidETH_rate'),('optimism_liquidETH_supply','optimism_accountant_rate')]:
   rate+=start[sk]*(end[pk]-start[pk]);supply+=(end[sk]-start[sk])*end[pk]
  change=end['published_book_nav_eth']-start['published_book_nav_eth'];assert math.isclose(change,rate+supply,abs_tol=1e-7)
  growth.append({'month':month['month'],'start_NAV_ETH':start['published_book_nav_eth'],'end_NAV_ETH':end['published_book_nav_eth'],'NAV_change_ETH':change,'accounting_rate_effect_ETH':rate,'share_supply_effect_ETH':supply,'is_external_deposit_ledger':False})
 growth_summary={'start_month':'2024-10','end_month':'2026-09','start_NAV_ETH':growth[0]['start_NAV_ETH'],'end_NAV_ETH':growth[-1]['end_NAV_ETH'],'NAV_change_ETH':sum(x['NAV_change_ETH'] for x in growth),'accounting_rate_effect_ETH':sum(x['accounting_rate_effect_ETH'] for x in growth),'share_supply_effect_ETH':sum(x['share_supply_effect_ETH'] for x in growth),'method':'Per chain: old shares*(new rate-old rate) + (new shares-old shares)*new rate. Share effect uses the ending mark. Not measured external deposits or an attribution of strategy profit.'}
 events=read('etherfi_parameter_events');start=T-730*86400;fees=sorted([e for e in events if e['event']=='ManagementFeeUpdated'],key=lambda e:(e['timestamp'],e['block']))
 fee_rows=[]
 for e in fees:
  old,new=[int(p['value']) for p in e['decoded']['parameters']];fee_rows.append({'timestamp':e['timestamp'],'date_UTC':stamp(e['timestamp']),'old_fee_bps':old,'new_fee_bps':new,'transaction_hash':e['transaction_hash'],'within_730_day_window':e['timestamp']>=start})
 applicable=[x for x in fee_rows if x['timestamp']<=start];initial=applicable[-1]['new_fee_bps'];boundaries=[(start,initial)]+[(x['timestamp'],x['new_fee_bps']) for x in fee_rows if start<x['timestamp']<T]+[(T,None)]
 weighted=sum((boundaries[i+1][0]-t)*bps for i,(t,bps) in enumerate(boundaries[:-1]))/(T-start)
 claims=collections.defaultdict(lambda:{'count':0,'raw_amount':0})
 for e in events:
  if e['event']=='FeesClaimed' and start<=e['timestamp']<=T:
   asset,amount=[p['value'] for p in e['decoded']['parameters']];q=claims[asset.lower()];q['count']+=1;q['raw_amount']+=int(amount)
 symbols={'0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2':'WETH','0xcd5fe23c85820f7b72d0926fc9b05b43e359b7ee':'weETH'}
 claims=[{'asset':a,'symbol':symbols[a],'claims':q['count'],'amount_units':q['raw_amount']/1e18,'raw_amount':str(q['raw_amount']),'ETH_value_at_each_payment_not_reconstructed':a.endswith('7ee')} for a,q in claims.items()]
 metrics=read('etherfi_verified_metrics');fees_out={'window_start':start,'window_end':T,'initial_fee_bps':initial,'changes':fee_rows,'calendar_time_weighted_fee_bps':weighted,'time_weighted_fee_is_not_realized_fee_on_capital':True,'claims':claims,'current_fee_bps':metrics['fee_bps'],'flat_NAV_annual_management_fee_ETH':metrics['published_book_nav_eth']*metrics['fee_bps']/1e4,'flat_NAV_annual_management_fee_USD':metrics['published_book_nav_usd_nearest_quote']*metrics['fee_bps']/1e4,'Ethereum_circulating_share_fee_run_rate_ETH':metrics['ethereum_shares']*metrics['rate_eth_per_share']*metrics['fee_bps']/1e4,'fee_history_scope':'Ethereum Accountant only; Optimism fee history not reconstructed','operator_profit_unknown':True,'note':'Claim payments are fee withdrawals, not strategy gross income, investor losses or operator net profit. Fee units are not added across different tokens. Run rate assumes unchanged NAV/fee and excludes downstream fees and operating costs.'}
 returns=[]
 for days in [365,730]:
  st=next(x['stETH_cumulative_return'] for x in read('etherfi_staking_comparison') if x['days']==days)
  for product,route,fee,basis in [('Fluid Lite ETH','Checked withdrawal',.0005,'5 bp contract getter at T'),('Treehouse tETH','Standard',.0005,'Current published 5 bp fee; actual standard settlement uses minimum rate'),('Treehouse tETH','Fastlane',.005,'Current published 0.5% fee; capacity required'),('CIAN rsETH','Published policy',.0002,'Current published policy; deployment override is not verified')]:
   gross=next(x['ETH_pps_cumulative_return'] for x in read('vault_history_comparison') if x['product']==product and x['days']==days);net=(1+gross)*(1-fee)-1
   returns.append({'product':product,'route':route,'days':days,'book_return':gross,'one_exit_fee_fraction':fee,'illustrative_after_exit_return':net,'stETH_book_return':st,'illustrative_excess_vs_stETH_pp':(net-st)*100,'fee_source_scope':basis,'not_executed_historical_return':True})
 sample=read('morpho_borrower_screen');borrowers=collections.defaultdict(lambda:{'borrow_USD':0,'positions':0,'chains':set()});market_rows=[];debt_total=0;position_total=0
 for m in sample:
  positions=m['positions']['items'];debt=m['market']['state']['borrowAssetsUsd'];observed=sum(p['state']['borrowAssetsUsd'] for p in positions);debt_total+=debt;position_total+=observed
  market_rows.append({'market_id':m['market']['marketId'],'collateral':m['market']['collateralAsset']['symbol'],'loan':m['market']['loanAsset']['symbol'],'market_reported_borrow_USD':debt,'sampled_position_borrow_USD':observed,'sampled_positions':len(positions),'reported_total_positions':m['positions']['pageInfo']['countTotal'],'not_same_request_atomic_snapshot':True})
  for p in positions:
   q=borrowers[p['user']['address'].lower()];q['borrow_USD']+=p['state']['borrowAssetsUsd'];q['positions']+=1;q['chains'].add(p['market']['chain']['id'])
 b=[{'address':a,**{k:v for k,v in row.items() if k!='chains'},'chains':sorted(row['chains'])} for a,row in borrowers.items()];b.sort(key=lambda r:r['borrow_USD'],reverse=True)
 pairs={(p['market']['chain']['id'],p['user']['address'].lower()) for m in sample for p in m['positions']['items']}
 borrower_out={'markets':len(sample),'sampled_positions':sum(len(m['positions']['items']) for m in sample),'distinct_chain_addresses':len(pairs),'distinct_addresses':len(b),'markets_with_more_than_ten_positions':sum(m['positions']['pageInfo']['countTotal']>len(m['positions']['items']) for m in sample),'reported_market_borrow_USD_sum':debt_total,'sampled_position_borrow_USD_sum':position_total,'sampled_over_reported_debt_fraction':position_total/debt_total,'top1_share_of_sampled_debt':b[0]['borrow_USD']/position_total,'top5_share_of_sampled_debt':sum(r['borrow_USD'] for r in b[:5])/position_total,'borrowers':b,'market_rows':market_rows,'target_snapshot_verified':False,'purpose_classification_complete':False,'note':'Discovery captured after T. At most ten largest positions per selected market; not a holder census or complete borrower census. Debt is gross debt, not depositor equity. Market and position requests are asynchronous, so coverage is a diagnostic rather than an exact reconciliation.'}
 fluid=read('fluid_lite_balance_T');fluid_stress={'borrow_plus_100bp_equity_return_change_pp':-fluid['debt_eth_equivalent']/fluid['net_assets_eth_equivalent'],'gross_asset_markdown_1pct_equity_loss_percent':fluid['gross_assets_eth_equivalent']/fluid['net_assets_eth_equivalent'],'isolated_fixed_positions':True}
 files=['etherfi_history_points','etherfi_history_monthly','etherfi_parameter_events','etherfi_verified_metrics','etherfi_staking_comparison','vault_history_comparison','morpho_borrower_screen','fluid_lite_balance_T','permissions_review_T'];proof=[{'path':str((DATA/(n+'.json')).relative_to(ROOT)),'sha256':hashlib.sha256((DATA/(n+'.json')).read_bytes()).hexdigest()} for n in files]
 permissions=read('permissions_review_T');permission_rows=[]
 for c in permissions['capabilities_T']:
  if c['getter'].startswith('getRoles'):
   holders=[h['user'] for h in permissions['role_holders_T'] if set(c['roles'])&set(h['roles'])];permission_rows.append({'function':c['function'],'roles':c['roles'],'addresses':holders,'count':len(holders)})
 out={'financial_snapshot_timestamp':T,'financial_data_refreshed':False,'derivation':'presentation_analysis.py','inputs':proof,'growth':growth,'growth_summary':growth_summary,'fees':fees_out,'exit_illustrations':returns,'borrowers':borrower_out,'fluid_stress':fluid_stress,'permissions':permission_rows};write('presentation_analysis',out)
 lines=['# Where returns and capital growth come from','', 'This report adds calculations to the captured research edition. The financial snapshot remains 2 October 2026, 23:59:59 UTC. Current document terms used in exit illustrations are labelled separately.','', '## The practical findings','', f"- Liquid ETH\'s capital changed by {growth_summary['NAV_change_ETH']:,.3f} ETH over the 24 completed months. The accounting-rate effect contributed {growth_summary['accounting_rate_effect_ETH']:,.3f} ETH; changes in share supply contributed {growth_summary['share_supply_effect_ETH']:,.3f} ETH at month-end marks.",'- Capital growth is therefore different from investor return. New shares, withdrawals, internal transfers and other issuance events can change capital without changing return per share.','- Exit costs can reverse a close ranking. A single 0.5% Treehouse fast exit applied to the one-year book return leaves less than the matched stETH book return. This is an illustration using current terms, not a historical execution result.','- Liquid ETH management fees changed several times. Applying today\'s fee to the whole two-year history would misstate past terms.','- A 24-hour owner timelock is not a universal delay: a separate measured role can change Liquid ETH\'s management fee.','', '## Capital growth: a reconciliation, not a deposit ledger','', 'The published capital value is the share supply multiplied by the accounting rate on each chain. For each month, we separate the change into two terms. The first measures the effect of the rate change on the opening share balance. The second values changes in shares at the closing rate.','', '`NAV change = old shares × (new rate - old rate) + (new shares - old shares) × new rate`','', 'The calculation is performed separately for Ethereum and Optimism, using each chain\'s own rate. Every monthly row reconciles to the captured published NAV change. The share-supply term is not measured external deposits: a transaction-level ledger is still required to distinguish investor flows, migrations, fee shares and messages in flight. The rate term explains accounting marks, not the strategy positions that earned them.','', '| Month | Opening capital, ETH | Closing capital, ETH | Capital change, ETH | Rate effect, ETH | Share-supply effect, ETH |','|---|---:|---:|---:|---:|---:|']
 for r in growth:lines.append('| '+r['month']+' | '+' | '.join(f"{r[k]:,.3f}" for k in ['start_NAV_ETH','end_NAV_ETH','NAV_change_ETH','accounting_rate_effect_ETH','share_supply_effect_ETH'])+' |')
 lines+=['', '## What a one-off exit fee does to the comparison','', 'The table applies a single fee to the final proceeds: `(1 + book return) × (1 - exit fee) - 1`. It does not deduct management fees again. It excludes slippage, waits, market discounts, benchmark exit costs and external rewards. Fees could have differed during the historical window.','', '| Product / route | Days | Book return | One exit fee | Illustrative return after exit | Excess vs stETH book return, pp |','|---|---:|---:|---:|---:|---:|']
 for r in returns:lines.append(f"| {r['product']} / {r['route']} | {r['days']} | {r['book_return']*100:.4f}% | {r['one_exit_fee_fraction']*100:.2f}% | {r['illustrative_after_exit_return']*100:.4f}% | {r['illustrative_excess_vs_stETH_pp']:.4f} |")
 lines+=['', 'Fluid uses the checked 5 bp getter at T. Treehouse uses current published terms and still depends on route capacity and settlement rules. CIAN\'s 0.02% is the published policy; an actual contract override has not been verified here. Liquid ETH is omitted because a single verified cost for every exit route is unavailable. Concrete private distributions and settlement terms do not support a matched numerical return. See [product terms and exit routes](PRODUCT-TERMS.md).','', '## Ethereum fee changes and operator revenue','', f"The two-year calendar-time weighted Ethereum Accountant management fee is {weighted/100:.4f}%. This weights time, not capital, and must not be read as the investor\'s realized fee rate.",'', '| UTC date | Previous annual fee | New annual fee | Ethereum transaction |','|---|---:|---:|---|']
 for r in fee_rows:lines.append(f"| {r['date_UTC']} | {r['old_fee_bps']/100:.2f}% | {r['new_fee_bps']/100:.2f}% | [Transaction](https://etherscan.io/tx/{r['transaction_hash']}) |")
 lines+=['', f"Applying the Ethereum 0.35% annual fee to unchanged consolidated snapshot NAV gives an illustrative gross fee run rate of {fees_out['flat_NAV_annual_management_fee_ETH']:,.3f} ETH, or ${fees_out['flat_NAV_annual_management_fee_USD']:,.0f} at the research quote. This scenario assumes the same fee across all circulating shares. It is not a reconstruction of both chains’ actual fee accrual, annual revenue already earned or operator profit.",'', f"Using only Ethereum-circulating shares and the same flat-balance assumption gives {fees_out['Ethereum_circulating_share_fee_run_rate_ETH']:,.3f} ETH per year. Optimism has its own Accountant and its fee history has not been reconstructed here.",'', 'Within the matched 730-day window, captured Ethereum Accountant fee-claim events paid:']
 for r in claims:lines.append(f"- {r['amount_units']:,.6f} {r['symbol']} across {r['claims']} claim transactions.")
 lines+=['', 'WETH and weETH amounts are kept separate. Claim payments can settle fees accrued earlier, so payment timing does not equal fee-earning timing. Costs, revenue sharing and downstream curator charges are needed to calculate operator net profit.','', '## Who can change Liquid ETH\'s book and fee','', 'The historical role audit paginated the Authority\'s logs to creation and read permissions at Ethereum block 26,108,081. It found 36 addresses ever assigned roles and 22 addresses with at least one active role at T. These counts include contracts and do not identify 22 people or organizations.','', '| Function | Active role IDs | Eligible addresses at T | What this means |','|---|---|---:|---|']
 descriptions={'manage(address,bytes,uint256)':'Manager can instruct the vault; its Merkle permission tree is another control layer.','enter(address,address,uint256,address,uint256)':'The Teller can mint shares through the deposit path.','exit(address,address,uint256,address,uint256)':'The Teller can burn shares through the withdrawal path.','updateExchangeRate(uint96)':'Three addresses can publish the accounting rate.','updateManagementFee(uint16)':'Both the timelock role and a separate operator role can set the fee.','pause()':'Emergency pause permission is broader than unpause permission.','unpause()':'Restarting the Accountant is restricted to a smaller set.','setRateProviderData(address,bool,address)':'Changing asset-rate provider data uses the owner role.'}
 for r in permission_rows:lines.append(f"| `{r['function']}` | {', '.join(map(str,r['roles']))} | {r['count']} | {descriptions[r['function']]} |")
 lines+=['', 'The owner timelock\'s minimum delay is 24 hours. The management-fee selector also accepts role 55, held at T by `0x607d0c7e3578802eb46d388cb86cfba8ff657306`. That direct role permission means the owner delay does not guarantee a 24-hour notice period for every fee change. The Accountant source limits this setter to a maximum management fee of 20%; a code ceiling is not the current fee or a commitment to keep it unchanged.','', 'All tested selectors were non-public. The complete list of active role addresses and RPC responses is in the [historical permission record](../../../data/eth/permissions_review_T.json). Beneficial identities, every strategy leaf and every timelock proposer/executor remain separate checks.','', '## Borrower concentration: what the sample can tell us','', f"The captured Morpho sample contains {borrower_out['markets']} markets and {borrower_out['sampled_positions']} positions. There are {borrower_out['distinct_chain_addresses']} network/address pairs and {borrower_out['distinct_addresses']} unique addresses across networks. An address operating on two chains creates two network/address pairs.",'', f"It selects at most ten largest positions per market; {borrower_out['markets_with_more_than_ten_positions']} markets have more positions. The five largest sampled addresses account for {borrower_out['top5_share_of_sampled_debt']*100:.2f}% of sampled dollar debt. This is concentration inside a deliberately top-heavy sample, not a market-wide concentration statistic.",'', f"Sampled position debt totals ${position_total/1e6:,.3f}M, versus ${debt_total/1e6:,.3f}M in the separately captured market states. The ratio is {position_total/debt_total*100:.2f}%. Requests are asynchronous, so the gap is not a proved error, deficit or exact missing-debt amount.",'', '| Address | Sampled gross debt, USD millions | Sampled positions | Chain IDs |','|---|---:|---:|---|']
 for r in b[:10]:lines.append(f"| [{r['address']}](https://etherscan.io/address/{r['address']}) | {r['borrow_USD']/1e6:.3f} | {r['positions']} | {', '.join(map(str,r['chains']))} |")
 lines+=['', 'Addresses are not labelled carry traders solely because they borrow stablecoins against ETH. Known vaults can be traced through their contracts, but unknown borrower purpose and beneficial ownership are unresolved. The sample cannot replace a full holder or borrower census.','', '## Fluid: leverage outside Liquid ETH','', f"Using Fluid\'s captured resolver balance, a one-percentage-point increase in debt APR reduces annual equity return by approximately {abs(fluid_stress['borrow_plus_100bp_equity_return_change_pp']):.4f} percentage points if balances and asset income stay fixed. A uniform 1% markdown in gross assets reduces resolver net equity by approximately {fluid_stress['gross_asset_markdown_1pct_equity_loss_percent']:.4f}%. These isolated illustrations exclude lender-income offsets, rebalancing and transaction execution.",'', '## Evidence and remaining work','', 'Inputs and their SHA-256 hashes are recorded in the [calculation dataset](../../../data/eth/presentation_analysis.json). New historical permission reads retain their request URL, payload, block and response hashes. The frozen financial series have not been refreshed.','', 'The additions explain growth arithmetic, fee history and selected permissions. They do not close independent portfolio backing, transaction-level investor flows, a full holder census, realized fee-adjusted investor cash P&L, or executable liquidation and exit simulation.']
 (EN/'RETURN-DRIVERS.md').write_text('\n'.join(lines)+'\n')
 print(json.dumps({'growth':growth_summary,'weighted_fee_bps':weighted,'fee_claims':claims,'borrowers':{k:borrower_out[k] for k in ['distinct_addresses','distinct_chain_addresses','top5_share_of_sampled_debt']},'permissions':[(r['function'],r['count']) for r in permission_rows]}))
if __name__=='__main__':run()
