"""Offline reconstruction of selected large ETH product book marks and bounded exits.
Every value comes from retained archive responses at its specified block.
No live discovery amounts are substituted for fixed-T state.
"""
import datetime,hashlib,json,pathlib,re,sys
ROOT=pathlib.Path(__file__).resolve().parents[2];RAW=ROOT/'raw/eth/strategy-universe-deep-2026-10-04';T=1790985599;BLOCK=26108081
PRICE=ROOT/'raw/eth/2026-10-02/prices_T-264a0247388b1d63.json';price=json.loads(PRICE.read_text())['coins']['coingecko:ethereum']['price']
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def utc(t):return datetime.datetime.fromtimestamp(t,datetime.timezone.utc).isoformat()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
allrows=[];inputs=[PRICE]
for p in sorted(RAW.glob('*.json')):
 try:d=json.loads(p.read_text())
 except Exception:continue
 if isinstance(d,dict)and'records'in d:
  inputs.append(p)
  for r in d['records']:allrows.append({**r,'sourcePath':str(p.relative_to(ROOT))})
def usable(r):return r['response'].get('result')not in[None,'0x']
def row(label):
 matches=[r for r in allrows if r['label']==label and usable(r)];return matches[-1]if matches else next((r for r in allrows if r['label']==label),None)
def words(r):
 z=r['response'].get('result')if r else None
 return[int(z[i:i+64],16)for i in range(2,len(z),64)]if z not in[None,'0x']else[]
def n(label,div=1e18):
 w=words(row(label));return w[0]/div if w else None
def address(label):
 w=words(row(label));return'0x'+hex(w[0])[2:].zfill(40)if w else None
def arraddresses(label):
 w=words(row(label));return['0x'+hex(x)[2:].zfill(40)for x in w[2:2+w[1]]]if len(w)>1 else[]
def proof(labels):return sorted({row(x)['sourcePath']for x in labels if row(x)})
contracts={'oseth':'0xf1c9acdc66974dfb6decb12aa385b9cd01190e38','oseth_controller':'0x2a261e60fb14586b474c208b1b7ac6d0f5000306','meth':'0xd5f7838f5c461feff7fe49ea5ebaf7728bb0adfa','meth_staking':'0xe3cbd06d7dadb3f4e6557bab7edd924cd1489e8f','yearn_weth':'0xc56413869c6cdf96496f2b1ef801fedbdfa7ddb0','autoeth':'0x0a2b94f6871c1d7a32fe58e1ab5e6dea2f114e56','yb_weth':'0x2b9c9f3bdceb5d8e36a4704f08a78fca53343cea','cmeth':'0xe6829d9a7ee3040e1276fa75293bde931859e8fa'}
ps=[]
def product(id,family,name,contract,assets,supply,pps,capitalScope,sourceLabels,historyKey=None,supplyKey=None,capitalSig=None,ppsSig=None):
 d={'id':id,'familyId':family,'productIds':[id],'name':name,'contract':contract,'measuredTimestamp':T,'measuredDate':utc(T),'block':BLOCK,'assetUnit':'ETH'if id in['oseth','meth']else'WETH','capitalETH':assets,'capitalUSD':assets*price if assets is not None else None,'capitalScope':capitalScope,'shareSupply':supply,'ethPerShare':pps,'valuationBasis':'Contract accounting or oracle mark, translated at the original T ETH/USD quote; not independently audited backing or executable cash.','additiveAcrossProducts':False,'fees':{},'state':{},'controls':{},'history':[],'windowReturns':[],'exitTests':[],'limitations':[],'sourcePaths':proof(sourceLabels),'sourceURLs':['https://etherscan.io/address/'+contract+'#readContract','https://eth.blockscout.com/api/v2/smart-contracts/'+contract]}
 if historyKey:
  timestamps=sorted({r['timestamp']for r in allrows if r.get('productKey')==historyKey})
  for ts in timestamps:
   code=row(historyKey+'_'+str(ts)+'_code');prefix=historyKey+'_'+str(ts)+'_';asset=n(prefix+capitalSig)if capitalSig else None;pp=n(prefix+ppsSig)if ppsSig else None;sp=n((supplyKey or historyKey)+'_'+str(ts)+'_totalSupply()')
   b=next((r.get('block')for r in allrows if r.get('productKey')==historyKey and r.get('timestamp')==ts),None)
   if code and code['response'].get('result')=='0x':status='absent: no deployed code at sampled block';asset=sp=pp=None
   elif pp is not None:status='measured funded book/share mark'
   else:status='getter or transport gap; not zero'
   if historyKey=='yb_weth':
    updated=words(row(prefix+'updated_balances()'));sp=updated[0]/1e18 if updated else None;asset=sp*pp if sp is not None and pp is not None else None
   d['history'].append({'date':utc(ts),'timestamp':ts,'block':b,'capitalETH':asset,'shares':sp,'ethPerShare':pp,'bookReturnPct':None,'status':status,'sourcePaths':proof([prefix+(capitalSig or''),prefix+(ppsSig or''),(supplyKey or historyKey)+'_'+str(ts)+'_totalSupply()',prefix+'updated_balances()'])})
  valid=[x for x in d['history']if x['ethPerShare']is not None];base=valid[0]if valid else None
  for x in valid:x['bookReturnPct']=(x['ethPerShare']/base['ethPerShare']-1)*100
  if base:d['windowReturns']=[{'startDate':base['date'],'endDate':valid[-1]['date'],'windowDays':(valid[-1]['timestamp']-base['timestamp'])/86400,'bookReturnPct':valid[-1]['bookReturnPct'],'annualized':False,'measure':'ETH-equivalent share-value change; excludes separate rewards, distributions and execution costs.'}]
  d['sourcePaths']=sorted(set(d['sourcePaths']+[p for x in d['history']for p in x['sourcePaths']]))
 ps.append(d);return d
os=product('oseth','stakewise','StakeWise osETH',contracts['oseth'],n('oseth_controller_totalAssets()'),n('oseth_totalSupply()'),n('oseth_controller_convertToAssets(uint256)'),'Aggregate osETH controller ETH claim accounting; not all StakeWise gross deposits.',['oseth_controller_totalAssets()','oseth_totalSupply()','oseth_controller_convertToAssets(uint256)'],'oseth_controller','oseth','totalAssets()','convertToAssets(uint256)')
os['fees']={'controllerRewardFee_pct':n('oseth_controller_feePercent()',100),'feeDenominator':10000,'scope':'Controller fee applied to rewards. Underlying vault/operator charges are separate layers.'}
os['controls']={'controllerOwner':address('oseth_controller_owner()'),'setter':'setFeePercent(uint16) is onlyOwner in captured verified source. Owner signer set and effective delay are not mapped here.'}
os['state']={'queueShares':n('oseth_redeemer_queuedShares()'),'unclaimedETH':n('oseth_redeemer_unclaimedAssets()'),'canProcessExitQueue':bool(n('oseth_redeemer_canProcessExitQueue()',1)),'queueUpdateDelaySeconds':n('oseth_redeemer_exitQueueUpdateDelay()',1),'lastQueueTimestamp':n('oseth_redeemer_exitQueueTimestamp()',1)}
os['limitations']=['Queue and checkpoint state are measured. No new osETH redemption request or paid claim was simulated in this extension.','The controller exchange rate is an accounting claim with modeled reward accrual; it is not a secondary-market executable bid.']
meth=product('meth','meth','mETH staking',contracts['meth'],n('meth_staking_totalControlled()'),n('meth_totalSupply()'),n('meth_staking_mETHToETH(uint256)'),'ETH controlled book underlying mETH, including the lending buffer.',['meth_staking_totalControlled()','meth_totalSupply()','meth_staking_mETHToETH(uint256)'],'meth_staking','meth','totalControlled()','mETHToETH(uint256)')
meth['fees']={'entryAdjustment_bps':n('meth_staking_exchangeAdjustmentRate()',1),'bufferInterestFee_pct':n('meth_liquidity_buffer_feesBasisPoints()',100),'scope':'Configured entry adjustment and lending-buffer interest fee at T. Validator reward fee is not independently reread in this extension.'}
buf=n('meth_liquidity_buffer_getControlledBalance()');gross=n('meth_liquidity_buffer_totalInterestClaimed()');fee=n('meth_liquidity_buffer_totalFeesCollected()');net=n('meth_liquidity_buffer_totalInterestToppedUp()')
meth['state']={'bufferControlledETH':buf,'bufferPctBook':buf/meth['capitalETH']*100,'bufferAllocatedETH':n('meth_liquidity_buffer_totalAllocatedBalance()'),'bufferAvailableGetterETH':n('meth_liquidity_buffer_getAvailableBalance()'),'bufferNativeETH':n('meth_buffer_native'),'stakingNativeETH':n('meth_staking_native'),'queueNativeETH':n('meth_unstake_manager_native'),'queueAllocatedCumulativeETH':n('meth_unstake_manager_allocatedETHForClaims()'),'queueClaimedCumulativeETH':n('meth_unstake_manager_totalClaimed()'),'queueRequestedCumulativeETH':n('meth_unstake_manager_latestCumulativeETHRequested()'),'queueFundingDeficitETH':n('meth_unstake_manager_allocatedETHDeficit()'),'finalizationDelayBlocks':n('meth_unstake_manager_numberOfBlocksToFinalize()',1),'bufferCashflowCounters':{'grossInterestClaimedETH':gross,'feesCollectedETH':fee,'netInterestToppedUpETH':net,'reconciliationResidualETH':gross-fee-net,'period':'Cumulative contract counters through T, not an annual return or a matched historical denominator.'}}
meth['limitations']=['The 20,000 ETH available-balance getter is not native ETH sitting in the buffer contract; its assets are allocated to a position manager.','Cumulative interest/fee counters reconcile economic flows but are not a complete independently traced cash-receipt history.','The 3,600-block queue threshold does not promise a fixed wall-clock completion time or availability for every demand size.']
y=product('yearn_weth','curated_eth','Yearn WETH-1',contracts['yearn_weth'],n('yearn_weth_totalAssets()'),n('yearn_weth_totalSupply()'),n('yearn_weth_convertToAssets(uint256)'),'Whole WETH vault book including lending, accumulation and an ETH-debt loop.',['yearn_weth_totalAssets()','yearn_weth_totalSupply()','yearn_weth_convertToAssets(uint256)'],'yearn_weth',None,'totalAssets()','convertToAssets(uint256)')
fc=words(row('yearn_accountant_getVaultConfig(address)'));y['fees']={'managementFee_pct':fc[0]/100,'performanceFee_pct':fc[1]/100,'maxLoss_bps':fc[5],'scope':'Actual accountant getVaultConfig at T, not the discovery feed estimator.'}
y['state']={'idleWETH':n('yearn_weth_totalIdle()'),'idlePctBook':n('yearn_weth_totalIdle()')/y['capitalETH']*100,'totalDebtWETH':n('yearn_weth_totalDebt()'),'isShutdown':bool(n('yearn_weth_isShutdown()',1)),'withdrawalQueue':arraddresses('yearn_weth_get_default_queue()'),'profitUnlockMaxSeconds':n('yearn_weth_profitMaxUnlockTime()',1),'allocations':[]}
for name,a,label in [('stETH Accumulator','0x470e0e048f85cfd72eef325895e02c8d297e7435','yearn_strategy_0x470e0e048f85cfd72eef325895e02c8d297e7435'),('Yearn OG WETH','0xe89371eaaac6d46d4c3ed23453241987916224fc','yearn_strategy_0xe89371eaaac6d46d4c3ed23453241987916224fc'),('Spark WETH Lender','0xfca3f21d60d5bc8b4c5c35f169bb5b6402510151','yearn_strategy_0xfca3f21d60d5bc8b4c5c35f169bb5b6402510151'),('wstETH/WETH Spark Looper','0x68a14629cb07c74259f481382fe8b6cfd8970121','yearn_spark_looper_book_debt')]:
 w=words(row(label));value=w[2]/1e18;y['state']['allocations'].append({'name':name,'address':a,'bookWETH':value,'pctBook':value/y['capitalETH']*100,'lastReportTimestamp':w[1],'inDefaultWithdrawalQueue':a in y['state']['withdrawalQueue'],'sourcePaths':proof([label])})
account=words(row('yearn_spark_account'));y['state']['sparkLooper']={'collateralToken':address('yearn_spark_looper_collateralToken()'),'collateralUnits':n('yearn_spark_looper_balanceOfCollateral()'),'debtToken':'WETH','debtWETH':n('yearn_spark_looper_balanceOfDebt()'),'currentLTV_pct':n('yearn_spark_looper_getCurrentLTV()')*100,'currentLeverage':n('yearn_spark_looper_getCurrentLeverageRatio()'),'targetLeverage':n('yearn_spark_looper_targetLeverageRatio()'),'maxLeverage':n('yearn_spark_looper_maxLeverageRatio()'),'healthFactor':account[5]/1e18,'oracleCollateralUSD':account[0]/1e8,'oracleDebtUSD':account[1]/1e8,'estimatedNetWETH':n('yearn_spark_looper_estimatedTotalAssets()'),'scope':'Actual Spark account oracle marks and loop strategy getters. Do not add gross collateral to parent NAV.'}
y['state']['allocationReconciliationResidualWETH']=y['capitalETH']-y['state']['idleWETH']-sum(x['bookWETH']for x in y['state']['allocations'])
y['controls']={'roleManager':address('yearn_weth_role_manager()'),'accountant':address('yearn_weth_accountant()'),'feeManager':address('yearn_accountant_feeManager()'),'scope':'Actual role/fee-manager addresses at T; signer sets, detailed permissions and delays are not fully audited.'}
y['limitations']=['The fourth, leveraged strategy is absent from the default withdrawal queue but remains in totalDebt.','Successful simulations are not paid transfers, guaranteed future liquidity or independently audited underlying backing.','Book returns include strategy marks and profit unlocking and do not isolate organic income from rewards.']
a=product('autoeth','autoeth','Auto Finance autoETH',contracts['autoeth'],n('autoeth_totalAssets()'),n('autoeth_totalSupply()'),n('autoeth_convertToAssets(uint256)'),'Whole WETH-marked autopool book; cached destination debt and idle WETH.',['autoeth_totalAssets()','autoeth_totalSupply()','autoeth_convertToAssets(uint256)'],'autoeth',None,'totalAssets()','convertToAssets(uint256)')
af=words(row('autoeth_getFeeSettings()'));ab=words(row('autoeth_getAssetBreakdown()'));a['fees']={'periodicFee_bps':af[5],'streamingFee_bps':af[6],'highWaterMarkEnabled':bool(af[9]),'feeSink':'0x'+hex(af[0])[2:].zfill(40),'scope':'Actual fee settings at T. Mutable fee machinery remains present even with both measured rates zero.'}
a['state']={'idleWETH':ab[0]/1e18,'idlePctBook':ab[0]/1e18/a['capitalETH']*100,'cachedDebtWETH':ab[1]/1e18,'cachedDebtMinWETH':ab[2]/1e18,'cachedDebtMaxWETH':ab[3]/1e18,'isShutdown':bool(n('autoeth_isShutdown()',1)),'destinations':arraddresses('autoeth_getDestinations()'),'withdrawalQueue':arraddresses('autoeth_getWithdrawalQueue()')}
a['controls']={'accessController':address('autoeth_accessController()'),'strategy':address('autoeth_autoPoolStrategy()'),'scope':'Configured addresses at T. Role members, signer thresholds and delays remain unverified in this extension.'}
a['limitations']=['The history measures book WETH per share. Separate rewarder distributions are excluded, so these values are not complete investor total returns.','Cached debt values and minimum/maximum pricing differ. Large withdrawals can incur slippage or revert even when maxRedeem returns the holder shares.']
u=words(row('yb_weth_'+str(T)+'_updated_balances()'));pps=n('yb_weth_pricePerShare()');effective=u[0]/1e18
b=product('yb_weth_pool','yieldbasis_eth','YieldBasis WETH underlying LT pool','0x2b9c9f3bdceb5d8e36a4704f08a78fca53343cea',effective*pps,effective,pps,'Whole LT pool net oracle book: effective updated supply times fair price. Staked and unstaked claim classes divide this same pool.',['yb_weth_'+str(T)+'_updated_balances()','yb_weth_pricePerShare()'],'yb_weth',None,None,'pricePerShare()')
b['productIds']=['yb_weth_staked','yb_weth_unstaked'];b['state']={'rawERC20Supply':n('yb_weth_totalSupply()'),'effectiveSupply':effective,'effectiveStakedShares':u[1]/1e18,'stakedBookETH':u[1]/1e18*pps,'unstakedBookETH':(u[0]-u[1])/1e18*pps,'minimumAdminFee_pct':n('yb_weth_min_admin_fee()')*100,'isKilled':bool(n('yb_weth_is_killed()',1)),'stablecoin':address('yb_weth_STABLECOIN()'),'stablecoinAllocated':n('yb_weth_stablecoin_allocated()'),'gauge':address('yb_weth_staker()'),'amm':address('yb_weth_amm()'),'previewWithdrawals':[]}
loan=words(row('yb_AMM_get_state'));b['state']['loan']={'AMM':b['state']['amm'],'collateralCurveLPUnits':loan[0]/1e18,'debtCrvUSD':loan[1]/1e18,'debtToBookEquityAtNominalDollar':loan[1]/1e18/b['capitalUSD'],'scope':'Actual get_state debt in crvUSD. Debt/equity ratio assumes crvUSD at one dollar; allocated stablecoin balance is a distinct funding limit/amount, not the debt.'};b['historyMeasure']='Unstaked LT fair ETH value per fixed token unit; staked gauge token balances and external rewards require a separate return series.'
for w in b['windowReturns']:w['measure']=b['historyMeasure']
b['fees']={'minimumAdminFee_pct':b['state']['minimumAdminFee_pct'],'scope':'A fee parameter, not a fixed charge on all holder returns. Actual fee allocation changes with staked share and loss state.'}
b['limitations']=['Oracle fair value is not executable cash. Withdrawal previews are quoted WETH amounts, not successful withdrawal transactions.','Effective updated supply can differ from raw ERC-20 supply under the fee calculation; they are equal at T. Staked balances change through the separate staking-fee mechanism.','The historical fair-price series is the ETH mark per unstaked LT unit, not the complete return of a staked gauge receipt. External YB rewards are excluded.']
for pct in[1,10,30]:b['state']['previewWithdrawals'].append({'pctRawSupply':pct,'quotedWETH':n('yb_preview_'+str(pct)+'pct_raw_supply'),'scope':'Fraction of raw ERC-20 supply, not fraction of effective book NAV or a completed exit.'})
# Retain nominal cmETH token exposure separately; do not claim portfolio backing.
cm=product('cmeth','meth','cmETH Ethereum token principal claim',contracts['cmeth'],n('cmeth_totalSupply()')*n('meth_staking_mETHToETH(uint256)'),n('cmeth_totalSupply()'),n('meth_staking_mETHToETH(uint256)'),'Nominal mETH principal claim: Ethereum cmETH token supply times configured 1 mETH receipt rate and mETH ETH conversion. Not a reconstructed restaking portfolio.',['cmeth_totalSupply()','cmeth_accountant_getRate()','meth_staking_mETHToETH(uint256)'])
cm['assetUnit']='Nominal ETH-equivalent mETH principal';cm['state']={'accountantMETHRate':n('cmeth_accountant_getRate()'),'accountantBase':address('cmeth_accountant_base()')};cm['limitations']=['Receipt is nested in mETH; this principal mark must not be added to mETH controlled ETH.','L2 circulation and escrow require bridge netting. Restaking rewards and liabilities are not reconstructed.','Zero accounting management/performance settings do not establish absence of externally charged restaking reward fees.']
# Holder-specific non-persistent simulations and getter contradictions.
for p,k in[(y,'yearn_weth'),(a,'autoeth')]:
 for r in allrows:
  if r['label'].startswith(k+'_withdraw_')and'pctNAV'in r['label']:
   p['exitTests'].append({'method':r.get('signature'),'caller':r.get('caller'),'requestedPctNAV':r.get('requestedPctNAV'),'requestedAssetsWETH':r.get('requestedWETH'),'status':'successful read-only withdrawal simulation'if usable(r)else'reverted read-only withdrawal simulation','returnedShares':words(r)[0]/1e18 if usable(r)else None,'error':r['response'].get('error'),'decodedError':{'name':'PositivePriceRecoupNotCovered(uint256)','remainingRaw':str(int(r['response']['error']['data'][10:74],16)),'scope':'Withdrawal price-recoup constraint in the T-bound Autopool implementation; this is not a proven asset deficit.'}if r['response'].get('error',{}).get('data','').startswith('0xa51ad78a')else None,'denominator':r.get('denominator'),'sourcePath':r['sourcePath'],'paidCashReceipt':False})
 for x in p['exitTests']:
  proportion=p['shareSupply']*x['requestedPctNAV']/100
  x['bookProportionShares']=proportion
  x['simulatedSharesAboveBook_pct']=(x['returnedShares']/proportion-1)*100 if x['returnedShares'] is not None else None
 p['state']['sampledHolderGetters']=[]
 for r in allrows:
  if r['label'].startswith(k+'_')and any(z in r['label']for z in['maxWithdraw(address)','maxRedeem(address)']):p['state']['sampledHolderGetters'].append({'label':r['label'],'method':r.get('signature'),'resultNative':words(r)[0]/1e18 if usable(r)else None,'error':r['response'].get('error'),'sourcePath':r['sourcePath'],'decodedError':{'name':'TooFewAssets(uint256,uint256)','requestedRaw':str(int(r['response']['error']['data'][10:74],16)),'actualRaw':str(int(r['response']['error']['data'][74:138],16))}if r['response'].get('error',{}).get('data','').startswith('0x9db859db')else None,'scope':'Getter state for a verified T holder. Different holders share the same underlying liquidity; do not sum their getter maxima.'})
# Bind selected deployed code/implementation at T, distinguishing proxy storage from clones.
for p in[os,meth,y,a,b]:
 k={'oseth':'oseth_controller','meth':'meth_staking','yearn_weth':'yearn_weth','autoeth':'autoeth','yb_weth_pool':'yb_weth'}[p['id']];r=row(k+'_code_T');code=r['response'].get('result')if r else None;slot=address(k+'_implementation_slot_T');clone=re.search('363d3d373d3d3d363d73([0-9a-f]{40})',code or'')
 p['implementationBinding']={'contractExamined':contracts[k]if k in contracts else p['contract'],'runtimeCodeSHA256':hashlib.sha256(bytes.fromhex(code[2:])).hexdigest()if code else None,'implementationAtT':slot or('0x'+clone[1]if clone else None),'bindingMethod':'EIP-1967 slot'if slot else'embedded EIP-1167 clone target'if clone else'direct deployed contract','sourcePaths':proof([k+'_code_T',k+'_implementation_slot_T',k+'_implementation_code_T']),'limitation':'Published interface was captured later. Historical implementation source equivalence beyond the stated T target is not inferred for mutable proxies.'}
# Append all successful state evidence paths; preserving specific measurement fields above.
for p in ps:
 p['sourcePaths']=sorted(set(p['sourcePaths']+[r['sourcePath']for r in allrows if r['label'].startswith({'oseth':'oseth','meth':'meth','yearn_weth':'yearn','autoeth':'autoeth','yb_weth_pool':'yb','cmeth':'cmeth'}[p['id']])]))
findings=[{'id':'yearn_hidden_loop','text':'A fourth Yearn strategy is an actual wstETH/WETH Spark loop. Four measured strategy debts plus idle WETH reconcile the parent book. The loop is absent from the default withdrawal queue and its borrower health factor is close to one.','productId':'yearn_weth'},{'id':'auto_exit','text':'At T, autoETH withdrawal simulations accepted 1% and 10% of whole-vault NAV but rejected 30%, despite sufficient caller shares. The decoded 30% error is PositivePriceRecoupNotCovered, a withdrawal pricing constraint, rather than evidence that the entire pool lacks assets. Getter maxima and cached NAV do not establish full liquidity.','productId':'autoeth'},{'id':'meth_cashflow','text':'mETH buffer counters reconcile cumulative gross interest, fee collection and net top-ups. Current capital cannot be used as the denominator for an annual yield on those cumulative flows.','productId':'meth'},{'id':'book_vs_total','text':'Actual share marks replace forward APY assumptions, but still exclude separately distributed rewards and executable-exit costs. The autoETH quarterly decline is a book-mark observation, not a complete investor-return attribution.','productId':'autoeth'},{'id':'yb_denominator','text':'YieldBasis fair price uses effective updated supply. It equals raw ERC-20 supply at T, but may differ while fees are pending. Staked and unstaked class marks partition one pool; the historical per-token price does not include staked gauge rewards.','productId':'yb_weth_pool'}]
bench_history=[]
for r in allrows:
 if r.get('productKey')=='steth_benchmark' and usable(r):
  ts=r['timestamp'];value=words(r)[0]/1e18;bench_history.append({'date':utc(ts),'timestamp':ts,'block':r['block'],'ethPerShare':value,'bookReturnPct':None,'sourcePaths':[r['sourcePath']]})
bench_history.sort(key=lambda x:x['timestamp']);bench_by_ts={x['timestamp']:x for x in bench_history}
for x in bench_history:x['bookReturnPct']=(x['ethPerShare']/bench_history[0]['ethPerShare']-1)*100
benchmarks=[{'id':'steth_exact_blocks','name':'Unlevered stETH, identical sampled blocks','contract':'0xae7ab96520de3a18e5e111b5eaab095312d7fe84','method':'getPooledEthByShares(uint256)','argumentShares':'1000000000000000000','assetUnit':'ETH per fixed Lido share','history':bench_history,'sourcePaths':sorted({p for x in bench_history for p in x['sourcePaths']}),'sourceURLs':['https://docs.lido.fi/contracts/lido/'],'scope':'Funded Lido share-accounting growth including applied staking fees. No interpolation; secondary-market discounts, entry/exit costs and external rewards are excluded.'}]
for p in ps:
 for w in p['windowReturns']:
  start=int(datetime.datetime.fromisoformat(w['startDate']).timestamp());end=int(datetime.datetime.fromisoformat(w['endDate']).timestamp());bs=bench_by_ts.get(start);be=bench_by_ts.get(end)
  if bs and be:
   br=(be['ethPerShare']/bs['ethPerShare']-1)*100;w.update(benchmarkId='steth_exact_blocks',benchmarkBookReturnPct=br,bookExcessPercentagePoints=w['bookReturnPct']-br,relativeBookOutperformancePct=((1+w['bookReturnPct']/100)/(1+br/100)-1)*100,benchmarkSourcePaths=sorted(set(bs['sourcePaths']+be['sourcePaths'])))
 for x in p['history']:
  header=row('block_'+str(x['block']));result=header['response'].get('result')if header else None
  if isinstance(result,dict):x.update(observedBlockTimestamp=int(result['timestamp'],16),observedBlockUTC=utc(int(result['timestamp'],16)),targetMinusBlockSeconds=x['timestamp']-int(result['timestamp'],16))
findings.append({'id':'matched_steth_benchmark','text':'Across the same sampled 732-day window, the four core product book-share marks grow less than unlevered stETH. Separate rewards and execution are excluded, so this does not establish complete investor or organic underperformance.','productIds':['oseth','meth','yearn_weth','autoeth']})
output={'schemaVersion':1,'snapshot':{'UTC':utc(T),'timestamp':T,'ethereumBlock':BLOCK,'ETH_USD':price,'priceTimestamp':1790985600,'quoteOffsetSeconds':1},'scope':'Six selected large product book/principal marks, sparse historical funded endpoints and bounded non-persistent exit simulations. No broadcasting or signing. No whole-market completeness claim.','products':ps,'benchmarks':benchmarks,'findings':findings,'coverage':{'productCount':len(ps),'historicalPointCount':sum(len(p['history'])for p in ps),'usableBookPriceHistoryPoints':sum(x['ethPerShare']is not None for p in ps for x in p['history']),'paidCashReceiptsAdded':0,'readOnlyDemandSimulations':sum(len(p['exitTests'])for p in ps),'limitations':'No new historical token payout receipt census was collected for these families. mETH cumulative contract counters are reported separately from receipt-level proof.'}}
OUT=ROOT/'data/eth/strategy_universe_deep.json';write(OUT,output)
requests=[json.loads(x)for x in(RAW/'requests.jsonl').read_text().splitlines()];inputs += [ROOT/x['path']for x in requests if x.get('path')]+[pathlib.Path(__file__).resolve(),RAW/'requests.jsonl']
manifest={'snapshot':output['snapshot'],'inputs':[{'path':str(p.relative_to(ROOT)),'sha256':sha(p),'bytes':p.stat().st_size}for p in sorted(set(inputs))],'rawRequests':requests,'outputs':[{'path':str(OUT.relative_to(ROOT)),'sha256':sha(OUT),'bytes':OUT.stat().st_size}]};write(ROOT/'data/eth/strategy_universe_deep_manifest.json',manifest)
assert abs(y['state']['allocationReconciliationResidualWETH'])<1e-9
assert abs(meth['state']['bufferCashflowCounters']['reconciliationResidualETH'])<1e-9
assert abs(meth['state']['queueAllocatedCumulativeETH']-meth['state']['queueClaimedCumulativeETH']-meth['state']['queueNativeETH'])<1e-8
assert all(p['capitalETH']>0 and p['capitalUSD']>0 for p in ps)
print(json.dumps({'coverage':output['coverage'],'capital':[(p['id'],p['capitalETH'],p['capitalUSD'])for p in ps],'SHA256':sha(OUT)}))
