"""Offline, deterministic strategy-family evidence build. No network or transaction operations.
Usage: python3 tools/eth/strategy_universe_expansion_build.py
Input hashes and dated capture scopes are written alongside the output.
"""
import hashlib,json,pathlib,datetime,re
ROOT=pathlib.Path(__file__).resolve().parents[2]
RAW=ROOT/'raw/eth/strategy-universe-expansion-2026-10-04'
OUT=ROOT/'data/eth/strategy_universe_expansion.json'
T='2026-10-02T23:59:59Z'; REVIEW='2026-10-04'; FEED_DATE='2026-10-03T13:40:39Z'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
records=[json.loads(x)for x in(RAW/'capture_manifest.jsonl').read_text().splitlines()]
def content_ok(x):
 if not x.get('path')or x.get('status')!=200:return False
 return not (ROOT/x['path']).read_text(errors='replace').lstrip().startswith('# Page Not Found')
bykey={x['key']:x for x in records if content_ok(x)}
def read(k):return json.loads((ROOT/bykey[k]['path']).read_text())
def url(k):return bykey[k]['url']
def urls(keys):return[url(k)for k in keys]
pools=json.loads((ROOT/'raw/eth/2026-10-02/yield_pools-65cd13598ec237ee.json').read_text())['data']
# This file is a discovery derivative. The authoritative original capture is separately hashed.
feedpath=ROOT/'raw/eth/2026-10-02/yield_pools-65cd13598ec237ee.json'
def feed(project,symbol=None,meta=None,chain=None):
 rows=[x for x in pools if x['project']==project and(symbol is None or x['symbol']==symbol)and(meta is None or meta in(x.get('poolMeta')or''))and(chain is None or x['chain']==chain)]
 if not rows:raise ValueError((project,symbol,meta,chain))
 return max(rows,key=lambda x:x['tvlUsd'])
def observation(row,scope=None):return {'amountUSD':row['tvlUsd'],'amountNative':None,'unit':'USD','measuredDate':FEED_DATE,'scope':scope or'reported full-pool value; discovery only, not reconciled product NAV at T','fixedBlockVerified':False,'source':'https://yields.llama.fi/pools','sourceId':'existing_yield_feed','poolId':row['pool'],'quotedAPY_pct':row.get('apy'),'quotedBaseAPY_pct':row.get('apyBase'),'quotedRewardAPY_pct':row.get('apyReward'),'returnMeasure':'forward/discovery quote, not realized investor return','additive':False}
def contract(address,chain='Ethereum',role='product'):return{'address':address.lower(),'chain':chain,'role':role,'binding':'official registry observed 4 October; implementation and role configuration at T not separately verified'}
families=[];products=[]
def family(id,name,category,mechanic,payers,eth,ret,exit,controls,risks,capacity,rewards,coverage,keys,notes=None):
 d={'id':id,'name':name,'categories':category,'mechanic':mechanic,'payers':payers,'products':[],'materiality':[],'ETHexposure':eth,'returnBasis':ret,'exitTerms':exit,'controls':controls,'risks':risks,'capacity':capacity,'incentivesOff':rewards,'coverageStatus':coverage,'sourceIds':keys,'sources':urls(keys),'notes':notes or[]};families.append(d);return d
DEFAULT_MISSING=['Capital, share supply, holdings and fee configuration at frozen T have not been independently reconstructed for this expansion.','No matched 24-month realized return, historical allocation or executable exit series has been added for this product.']
def product(f,id,name,chain,contracts,denom,status,keys,obs=None,events=None,missing=None,extra=None):
 d={'id':id,'familyId':f['id'],'name':name,'chain':chain,'contracts':contracts,'denomination':denom,'status':status,'ETHexposure':f['ETHexposure'],'returnBasis':f['returnBasis'],'exitTerms':f['exitTerms'],'controls':f['controls'],'payers':f['payers'],'risks':f['risks'],'capacity':f['capacity'],'incentivesOff':f['incentivesOff'],'coverageStatus':f['coverageStatus'],'materiality':obs or[],'quantitativeObservations':obs or[],'historicalEvents':events or[],'missingMeasurements':missing if missing is not None else DEFAULT_MISSING,'sourceIds':keys,'sources':urls(keys)}
 if extra:d.update(extra)
 products.append(d);f['products'].append(id);f['materiality']+=obs or[];return d
# 1. Staking and a distinct ETH-debt loop.
f=family('stakewise','StakeWise osETH and Boost',['E1','E3'],'osETH is a liquid claim on ETH staking. Boost deposits osETH as Aave collateral, borrows ETH, stakes it and repeats. Borrowed ETH increases both staking income and debt.',['Ethereum issuance, priority fees and MEV','Boost borrowers pay ETH interest to Aave suppliers'],'ETH long. Boost has additional ETH debt and liquidation exposure.','Unlevered return is net staking growth in ETH. Boost adds staking earnings on borrowed capital and subtracts variable ETH borrowing costs and fees. Compare the complete position with simply holding ETH.','osETH direct redemption uses a ticket and checkpoint before an ETH claim. Validator exits and the available redemption buffer affect timing. A market sale instead depends on pool depth. Unboosting must repay debt.','Vault operators and DAO contracts control different layers. Published Boost settings are 93% LTV and 95% liquidation threshold, with third-party unboosting above 94.5%; these are document observations, not verified T configuration.',['Validator penalties','Contract and oracle dependencies','ETH borrowing rates can overtake staking yield','Secondary-market exit price can differ from oracle collateral value'],'Validator capacity, osETH minting collateral, Aave supply/borrow limits and usable ETH liquidity. High LTV magnifies the consequences of a small adverse spread.','Base staking remains without token incentives. Boost needs a positive net staking-to-borrow spread; points are not required for the arithmetic.','Material product family identified; separate T balances, Boost position population and role mapping remain outside this expansion.',['stakewise_index','stakewise_mainnet','stakewise_networks','stakewise_concepts'])
product(f,'oseth','StakeWise osETH','Ethereum',[contract('0xf1c9acdc66974dfb6decb12aa385b9cd01190e38'),contract('0xc43a7b16a7a167c0318390cba16787c11e9e1fd0',role='redemption')],'ETH','Current official product documentation, reviewed 4 October',['stakewise_mainnet','stakewise_index'],[observation(feed('stakewise-v3','OSETH'))] if any(x['project']=='stakewise-v3'and x['symbol']=='OSETH'for x in pools)else[observation(next(x for x in pools if x['symbol']=='OSETH'and x['tvlUsd']>400e6))])
product(f,'stakewise_genesis','StakeWise Genesis Vault','Ethereum',[contract('0xac0f906e433d58fa868f936e8a43230473652885')],'ETH','Current registry identity; osETH and vault claims can overlap',['stakewise_mainnet'],[observation(next(x for x in pools if 'Genesis' in(x.get('poolMeta')or'')and x['project'].startswith('stakewise')),'vault balance may overlap with osETH collateral; do not add both as unique capital')])
# 2. Staking with a lending buffer, plus a separate restaking receipt.
f=family('meth','mETH and cmETH',['E1','E2','E5'],'mETH combines validator staking with an ETH liquidity buffer deployed to Aave, introduced on 24 October 2025. cmETH restakes mETH and exposes holders to the configured restaking portfolio.',['Ethereum validator economics','Aave ETH borrowers for the buffer','Restaking service payments and third-party reward issuers'],'ETH long. mETH and cmETH are nested receipts, not separate unique ETH principal.','mETH exchange-rate growth reflects net ETH staking and buffer earnings. cmETH adds restaking rewards, which may be other tokens. Reward token value, claiming costs and fees belong in total return.','Published mETH exits are FIFO with a minimum 12-hour wait; available buffer and validator queue can make the actual wait longer. cmETH has a separate published cooldown of approximately seven days.','Published policy charges roughly 10% of mETH rewards and 20% of cmETH restaking rewards; staking entry fee is 4 basis points. Upgrade, pause and restaking allocation roles exist and require a T-specific authority review.',['Validator penalties','Aave buffer credit/liquidity','Restaking penalties and operator risk for cmETH','Cross-chain messaging and nested receipt risk'],'Validator queues, liquid ETH buffer, Aave liquidity and each restaking service allocation limit. Bridge liquidity is an additional exit constraint.','Ethereum staking and borrower interest can persist without COOK or promotional points. Sustainable restaking income requires actual service fees; token distributions alone do not establish it.','Large staking family with an important documented hybrid mechanism; current buffer/restaking allocation and service-payer cashflows are not reconstructed.',['meth_overview','meth_staking_contracts','cmeth_contracts'])
product(f,'meth','mETH','Ethereum / Mantle',[contract('0xd5f7838f5c461feff7fe49ea5ebaf7728bb0adfa')],'ETH','Current official staking receipt',['meth_staking_contracts','meth_overview'],[observation(feed('meth-protocol','METH'))],events=[{'date':'2025-10-24','event':'Aave ETH liquidity-buffer integration introduced','sourceURLs':[url('meth_overview')]}])
product(f,'cmeth','cmETH','Ethereum / Mantle',[contract('0xe6829d9a7ee3040e1276fa75293bde931859e8fa')],'mETH underlying; restaking rewards may use other tokens','Current official restaking receipt',['cmeth_contracts','meth_overview'],missing=DEFAULT_MISSING+['No standalone current cmETH capital figure is established here; mETH backing must be netted before aggregation.'])
# 3. Curated allocation is not necessarily pure lending.
f=family('curated_eth','Curated ETH lending and allocation',['E5','EH'],'A vault accepts WETH and allocates it across permitted strategies. Borrower interest is one possible source; Yearn WETH also lists staking-related strategies, so the wrapper name does not prove a pure lending portfolio.',['Collateralized ETH borrowers','Ethereum staking economics where a strategy stakes ETH','Reward token sponsors where enabled'],'ETH long for WETH products. Nested lending vaults create overlap with their underlying markets.','Measure WETH assets per share, including losses and fees. A reported net APR or base APY is a quote or recent estimator, not a separately audited organic cashflow series.','ERC-4626 exits follow available idle liquidity and the withdrawal queue. Borrowed assets need repayment or a strategy unwind. maxWithdraw and a marked share price do not prove execution for a large order.','Euler Earn separates owner, curator, allocator and guardian powers over strategies, caps, queues and fees. Yearn vault managers control strategy allocation and withdrawal ordering. Immutable code does not make strategy management immutable.',['Borrower bad debt','Illiquid lending utilization','Curator and strategy changes','Accounting losses and nested share valuation'],'Strategy deposit caps and borrower demand. New deposits can dilute yields unless additional borrowers or staking capacity absorb the capital.','Borrower interest and genuine validator earnings remain. In the selected K3 quote, base APY is materially below total APY because incentives supply part of the displayed return.','Material new Monad lending allocator and a documented Yearn mixed vault; live/T allocations and all configured roles require deeper work.',['euler_use_earn','euler_earn_docs','euler_addresses_current','euler_sunset','yearn_registry','yearn_v3_docs'])
product(f,'euler_k3_weth','Euler K3 Capital Earn WETH','Monad',[],'WETH','Current discovery feed; official April 2026 handover proposal identifies the Monad WETH Earn family',['euler_sunset','euler_use_earn','euler_addresses_current'],[observation(next(x for x in pools if x['project']=='euler-v2'and x['chain']=='Monad'and 'K3 Capital Earn' in(x.get('poolMeta')or'')and x['symbol']=='WETH'))],events=[{'date':'2026-04-08','event':'Official handover inventory reports Monad Euler Earn WETH supply of $7.75 million and names K3 as the proposed incoming curator. It is a dated proposal inventory, not proof of the T role configuration.','sourceURLs':[url('euler_sunset')]}],missing=DEFAULT_MISSING+['The official general registry was captured, but an exact K3 WETH Earn address was not independently bound to the discovery row. Keep this product unbound rather than importing a guessed address.'])
y=next(x for x in read('yearn_registry')if x['address'].lower()=='0xc56413869c6cdf96496f2b1ef801fedbdfa7ddb0')
p=product(f,'yearn_weth','Yearn WETH-1 yVault','Ethereum',[contract(y['address'])],'WETH','Current official registry, reviewed 4 October',['yearn_registry','yearn_v3_docs'],[observation(feed('yearn-finance','WETH'))],extra={'registryObservation':{'date':REVIEW,'assetsNative':int(y['tvl']['totalAssets'])/1e18,'asset':'WETH','amountUSD':y['tvl']['tvl'],'netAPR_pct':y['apr']['netAPR']*100,'performanceFee_pct':y['apr']['fees']['performance']*100,'managementFee_pct':y['apr']['fees']['management']*100,'scope':'later official registry accounting and estimator; not frozen T or executable cash','sourceURLs':[url('yearn_registry')]}})
product(f,'yearn_yeth_recovery','Yearn yETH Recovery Vault','Ethereum',[contract('0xd7a540ba3626c0aa66e7db4088971d0cd64695b6'),contract('0xccd04073f4bdc4510927ea9ba350875c3c65bf81',role='retired yETH pool')],'WETH recovery assets for eligible prior holders','Recovery only; former yETH product retired, not a normal new-deposit yield product',['yearn_registry','yearn_incident','yearn_recovery','yearn_recovery_app'],obs=[{'amountUSD':6609363.427314476,'amountNative':2446.805846524712,'unit':'WETH','measuredDate':REVIEW,'scope':'official recovery-vault accounting; not total pre-exploit yETH capital or available cash','fixedBlockVerified':False,'source':url('yearn_registry'),'additive':False}],events=[{'date':'2025-11-30','event':'Official disclosure identifies yETH exploit at block 23914086. V2 and V3 vaults were stated unaffected.','sourceURLs':[url('yearn_incident')]},{'date':'2026-10-04','event':'Official yETH interface states the product has been retired and is available for recovery.','sourceURLs':[url('yearn_recovery_app')]}],extra={'ETHexposure':'Historical weighted LST pool; current WETH recovery claim. This is distinct from Yearn WETH-1.'})
# 4. Principal tokens, yield tokens and verified route boundaries.
f=family('fixed_yield','ETH principal and yield tokens',['E6','E3'],'A yield-bearing claim is split into principal and future-yield tokens. Buying discounted PT fixes a contractual maturity payoff in its accounting unit. YT buys the right to future yield and ends with no principal redemption. LP owns a separate trading position.',['Underlying staking or vault earnings','PT/YT counterparties through the traded discount','Traders paying pool fees','Reward token issuers for incentivized LP'],'Depends on the actual redemption unit. PT-stETH retains ETH price exposure; dollar-family PT does not become ETH long because a vault uses ETH collateral elsewhere.','PT return is maturity claim value minus purchase cost and fees, measured in the actual accounting unit. YT total payoff includes distributions and any resale value minus purchase cost. LP fee APY is only one component of total return.','PT can be sold before maturity at the market price or redeemed after maturity subject to the underlying standardized-yield redemption path. LP and YT exits have separate pricing and liquidity.','Underlying yield tokens retain issuer/vault controls. Router integration and approved money-market collateral introduce additional dependencies and caps.',['Underlying issuer loss','PT/YT repricing','Redemption-unit errors','Borrowing and liquidation risk in leveraged PT'],'Maturity-specific market liquidity, underlying withdrawal liquidity, PT collateral caps and variable debt rates constrain loops.','PT and ordinary underlying yield need no promotional emissions. YT and LP return estimates must remove reward token subsidies while retaining price and underlying-yield changes.','Full 494-record Ethereum registry captured. 117 are ETH tagged; only four are active and unexpired at the 4 October discovery. Other chains and ETH PT collateral routes outside the published loop registry remain unmeasured.',['pendle_market_registry','pendle_registry_100','pendle_registry_200','pendle_registry_300','pendle_registry_400','pendle_eth_loop_pairs','pendle_loop_docs','spectra_faq','spectra_contract_index'],notes=['The feed repeats one market value for a PT-buy row and an LP row. These are different payoffs against the same market liquidity, not twice the capital.','The official 15-PT Ethereum loop catalog contains no ETH-tagged PT matches. Generic PT-loop mechanics do not establish an active ETH PT loop product.'])
# Fix family helper argument order: risks are explicitly supplied after construction for this concise catalog.
f['risks']=['Underlying issuer loss','PT/YT market repricing','Redemption-unit errors','Borrowing-rate and liquidation risk in leveraged PT']
allmarkets=[]
for k in ['pendle_market_registry','pendle_registry_100','pendle_registry_200','pendle_registry_300','pendle_registry_400']:allmarkets+=read(k)['results']
ethmarkets=[x for x in allmarkets if'eth'in x.get('categoryIds',[])]
active=[x for x in ethmarkets if x.get('isActive')and x['expiry']>'2026-10-04T00:00:00Z']
for x in active:
 product(f,'pendle_'+x['address'],x['pt']['name'],'Ethereum',[contract(x['address'],role='market LP'),contract(x['pt']['address'],role='principal token'),contract(x['sy']['address'],role='standardized yield')],x.get('accountingAsset',{}).get('symbol')or x.get('extendedInfo',{}).get('pyUnit')or'Underlying-specific','Active/unexpired in official registry on 4 October; T state not bound',['pendle_market_registry','pendle_registry_100','pendle_registry_200','pendle_registry_300','pendle_registry_400'],obs=[{'amountUSD':x['liquidity']['usd'],'amountNative':x['liquidity']['acc'],'unit':x.get('accountingAsset',{}).get('symbol'),'measuredDate':REVIEW,'scope':'market trading liquidity; not PT outstanding principal, YT cashflows or unique protocol capital','fixedBlockVerified':False,'source':url('pendle_market_registry'),'additive':False}],events=[{'date':x['expiry'],'event':'Scheduled maturity; future date is contractual, not an observed successful redemption.','sourceURLs':[url('pendle_market_registry')]}])
# 5. Managed correlated-asset LP allocation.
f=family('autoeth','Auto Finance autoETH, formerly Tokemak',['E7','EH'],'autoETH allocates ETH across approved destinations, including ETH/LST trading pools and their incentive wrappers. The solver proposes rebalances against the configured strategy.',['Traders paying DEX swap fees','Ethereum validator economics embedded in LSTs','DEX and incentive-token issuers'],'Predominantly ETH-family inventory exposure; LST, LP and reward receipt risks remain. It is not a neutral dollar strategy.','Total WETH-equivalent return includes staking, realized swap fees and reward sales, less slippage, transaction costs and configured fees. Cached NAV and a displayed forward yield are different measures.','Published user terms have no standard deposit lock. An exit above idle liquidity needs destination unwinds. Large withdrawal tooling can use custom swap routes; quoted NAV does not guarantee a same-price, same-block full exit.','Approved destinations, allocation strategy and role-gated rebalancing constrain the solver. Documentation supports periodic and streaming fees, including a high-water-mark mechanism; actual rates at T are not independently measured.',['LST depeg','DEX inventory loss','Reward dilution','Cached destination valuation','Manager and oracle dependencies'],'Destination depth, DEX trade demand and rebalance costs. Rewards can attract capital faster than organic swap volume grows.','The discovery quote contains 2.47077% base APY and 0.18631% reward APY. Base is the feed classification, not audited cash-only return; remove rewards without assuming every remaining quoted component is realized.','Official autoETH address and destination catalog identified; no T strategy allocation, realized return or configured role delay audit.',['auto_contracts','auto_withdraw','auto_strategy','auto_large_exits','auto_vault_terms'])
product(f,'autoeth','autoETH','Ethereum',[contract('0x0a2b94f6871c1d7a32fe58e1ab5e6dea2f114e56')],'WETH','Current Auto Finance documentation; Tokemak documentation redirects to the new name',['auto_contracts','auto_strategy','auto_large_exits'],[observation(feed('autofinance','WETH','autoETH'))] if any(x['project']=='autofinance'and x.get('poolMeta')=='autoETH'for x in pools)else[observation(next(x for x in pools if x['symbol']=='AUTOETH'))])
# 6. Leveraged LP, not automatically a generic USD carry position.
f=family('yieldbasis_eth','YieldBasis WETH leveraged liquidity',['E7'],'The core pool borrows crvUSD to maintain a leveraged WETH/stablecoin liquidity position. The target leverage of two is intended to offset ordinary constant-product impermanent loss. Staked and unstaked LT claims use different fee/reward treatment.',['Traders paying pool fees','YB token emissions for eligible stakers'],'Designed to track the underlying ETH asset while liquidity management and leverage add losses and constraints. It is not automatically delta neutral.','Unstaked return includes the ETH value of LP fees and pool value changes after leverage mechanics. Staking changes the claim and incentive treatment. Do not stack unstaked fee APY and staked YB APY as if one holder receives both unchanged.','Pool exits depend on available collateral, debt unwind and oracle state. Staked receipts may require unstaking first. Hybrid-vault emergency exits have distinct paths and cannot be inferred from the basic LT getter.','Factory and pool parameters, fee allocation and gauge governance affect returns. Current source code is captured; the implementation and parameter state at T were not exhaustively bound for this family expansion.',['Leverage and rebalance loss','Stablecoin and oracle assumptions','Liquidity bottlenecks','Different staked/unstaked claims'],'crvUSD funding limits, WETH pool depth, trading demand and pool parameter settings. Leverage targets do not create unlimited lossless capacity.','Unstaked fee income can persist if traders use the pool. The selected staked quote is reported entirely as reward APY, so its incentives-off value cannot be treated as the displayed 3.13979%.','Material WETH market discovered; full T debt, fee distribution and historical two-class return series still require a separate product chapter.',['yb_repository','yb_deployments','yb_lt_code','yb_paper'])
product(f,'yb_weth_unstaked','YieldBasis WETH unstaked LT','Ethereum',[contract('0x2b9c9f3bdceb5d8e36a4704f08a78fca53343cea')],'WETH-related LT claim','Discovered active feed row; exact LT has been identified in earlier fixed-T research',['yb_deployments','yb_lt_code'],[observation(next(x for x in pools if x['project']=='yield-basis'and x['symbol']=='YB-WETH'and 'Unstaked' in(x.get('poolMeta')or'')))],extra={'identityEvidenceScope':'LT address comes from the earlier fixed-T nested-holder work, not from the factory deployment log alone.'})
product(f,'yb_weth_staked','YieldBasis WETH staked LT','Ethereum',[contract('0xd829456fd63ada7de0657714a3a7a26de403e3d8',role='gauge')],'Staked WETH-related LT; reward token exposure','Discovered active feed row; related receipt rather than a second independent underlying pool',['yb_deployments','yb_lt_code'],[observation(next(x for x in pools if x['project']=='yield-basis'and x['symbol']=='YB-WETH'and 'Staked' in(x.get('poolMeta')or'')and 'Unstaked'not in(x.get('poolMeta')or'')))],extra={'identityEvidenceScope':'Gauge address comes from earlier fixed-T nested-holder work; no standalone full gauge backing audit is claimed.'})
# 7. Perpetual liquidity: fee income does not describe the whole payoff.
f=family('perpetual_lp','GMX GM and GLV liquidity',['E7','E9-adjacent'],'GM supplies collateral liquidity for perpetual markets. Its marked value incorporates net trader profit or loss as well as inventory and fees. GLV reallocates among approved GM markets with a common collateral pair.',['Perpetual traders paying trading, borrowing and liquidation fees','Swap users','Losing trader positions increase LP value; winning positions reduce it'],'ETH/USDC mixes ETH and USD inventory. ETH/ETH retains ETH inventory. Neither is automatically delta neutral. A USDG/USDG ETH-index market has no ETH principal merely because its index is ETH.','Complete return is pool inventory price change plus the LP share of fees and net trader PnL, less execution costs. Funding transfers between opposing trader sides are not automatically LP income. A separate short hedge adds funding, collateral and liquidation costs.','Deposits and withdrawals execute through oracle/keeper steps. Open-interest reserves can restrict withdrawal capacity; liquidity must be released before all shares can exit.','Market approval, open-interest and reserve limits, fees, oracle feeds and GLV allocation controls can change the payoff and exit conditions. Published docs describe a 63% pool / 37% protocol fee split; T settings are not bound here.',['Trader PnL','Inventory price risk','Reserved-liquidity exits','Oracle and keeper dependencies','Optional external hedge failure'],'Trader demand, collateral liquidity, open-interest reserve constraints and maximum pool/PnL settings. Adding LP capital without traders dilutes fee return.','Fees and net counterparty trading results remain when emissions stop. A fee-only APY omits the largest sources of positive or negative total return.','Official Arbitrum market catalog and material GM pool identities captured. Historical holdings, NAV plus distributions and any actual hedge are not reconstructed.',['gmx_market_registry','gmx_liquidity_docs','gmx_performance','gmx_deployments'])
gm=read('gmx_market_registry')['markets']
for id,needle,symbol in [('gmx_eth_usdc','ETH/USD [ETH-USDC]','ETH-USDC'),('gmx_eth_eth','ETH/USD [ETH-ETH]','ETH-ETH')]:
 m=next(x for x in gm if x['name']==needle)
 product(f,id,needle,'Arbitrum',[contract(m['marketToken'],'Arbitrum','GM market'),contract(m['longToken'],'Arbitrum','long collateral'),contract(m['shortToken'],'Arbitrum','short collateral')],symbol,'Listed official market on 4 October',['gmx_market_registry','gmx_liquidity_docs','gmx_performance'],[observation(next(x for x in pools if x['project']=='gmx-v2-perps'and x['chain']=='Arbitrum'and x['symbol']==symbol))],extra={'indexToken':m['indexToken'],'listingDate':m.get('listingDate'),'hedgeVerified':False})
# 8. Historical material options, plus unquantified official contemporary catalog.
f=family('options','ETH options and structured vaults',['E8'],'A covered-call vault sells calls against ETH collateral. Option buyers pay premium in exchange for upside above the strike. Cash-secured puts instead start with dollar collateral and sell ETH downside protection. Wheel products rotate between these exposures.',['Option buyers paying insurance or speculative premia','Reward-token sponsors where enabled'],'Covered calls are ETH long with capped upside. Cash-secured ETH puts are USD-funded short downside exposure, not ordinary ETH staking.','Covered-call total return includes premium, the short-option settlement and ETH collateral movement, less fees. ETH-relative performance can be negative in a sharp rally. Cash-secured put return includes settlement losses. Annualizing auction premium alone is not realized net return.','Option collateral is committed until the round settles. Ribbon withdrawal requests are completed after rollover; unused pending deposits can use a separate instant withdrawal path. Secondary exits depend on the specific wrapper and liquidity.','Ribbon historical docs list a 2% annual management fee and 10% performance fee, charged only for profitable strategy weeks. Keeper/manager roles select or roll options and auction parameters; T authority and current operations are not established.',['Short volatility and tail losses','Upside surrendered by covered calls','Auction execution','Round-bound liquidity','Stale contract catalogs'],'Option buyer appetite, executable strike liquidity and risk limits. Larger vaults can depress auction premiums. Weekly caps and auction fills are real capacity measures.','Option premiums can remain without RBN or NUTS incentives, but premium alone is not profit. The 2021 Ribbon period was explicitly incentivized, so the historical growth does not establish unsubsidized demand.','Historical material ETH covered calls verified. Thetanuts official ETH contract identities are discovery only; no current $5 million ETH option-vault balance is established.',['ribbon_retro','ribbon_contracts','ribbon_v2','ribbon_fees','ribbon_architecture','ribbon_user_withdraw','thetanuts_registry','thetanuts_faq'])
product(f,'ribbon_eth_call','Ribbon ETH Theta covered-call vault','Ethereum',[contract('0x25751853eab4d0eb3652b5eb6ecb102a2789644b')],'ETH','Historically material; current operating status and balance not independently established',['ribbon_retro','ribbon_contracts','ribbon_fees','ribbon_architecture','ribbon_user_withdraw'],[{'amountUSD':None,'amountNative':10000,'unit':'ETH','measuredDate':'2021-06-18 / 2021-07-16','scope':'official retrospective: ETH call cap increased from 5,000 to 10,000 ETH and was full during the incentive program; not a current balance or a dated USD peak','fixedBlockVerified':False,'source':url('ribbon_retro'),'additive':False}],events=[{'date':'2021-07-29','event':'Published incentive retrospective reports full ETH-call capacity after cap increase to 10,000 ETH.','sourceURLs':[url('ribbon_retro')]}])
product(f,'ribbon_eth_put','Ribbon ETH put vault','Ethereum',[],'USDC','Historically material adjacent USD-funded option product; excluded from ETH-principal capital',['ribbon_retro','ribbon_fees'],[{'amountUSD':20000000,'amountNative':20000000,'unit':'USDC','measuredDate':'2021-06-18 / 2021-07-16','scope':'official retrospective: cap increased from $9.5 million to $20 million and was full during incentive program; not ETH principal or current AUM','fixedBlockVerified':False,'source':url('ribbon_retro'),'additive':False}],extra={'ETHexposure':'USD collateral with short ETH put exposure.','excludedFromETHPrincipal':True})
for id,name,chain,address in [('thetanuts_eth_call','Thetanuts weekly ETH call','Ethereum','0x9014f8e90423766343ed4fe41668563526df6715'),('thetanuts_eth_call_arb','Thetanuts weekly ETH call','Arbitrum','0x1d1cd4abe0f2af9d79b5e3149bf4a503f97c1ead'),('thetanuts_meth_call','Thetanuts mETH call','Mantle','0x7bf3c7c23501ea3e09b237d6f8adcb7ea3cef41c')]:
 product(f,id,name,chain,[contract(address,chain)],'ETH or mETH option collateral','Official contract catalog only; activity and materiality unverified',['thetanuts_registry','thetanuts_faq'],missing=DEFAULT_MISSING+['No verified current TVL, historical peak, recent option auction or settlement census establishes a material active ETH product.'])
# 9. Distinct dollar-neutral universe and a verified recovery case.
f=family('dollar_neutral','ETH-backed dollar-neutral products and recovery',['E9','extended USD scope'],'Ethena and the historical Resolv design combine crypto collateral with short futures. The shorts offset ETH/BTC price exposure; collateral staking and derivative carry can contribute income. The dollar receipt is different from an ETH-long vault.',['Ethereum staking where ETH collateral is used','Futures counterparties through funding or basis convergence','Borrower interest or stable-asset returns where deployed'],'Targets dollar neutrality, not preservation of ETH upside. Whole USDe/USR value cannot be called ETH strategy capital without a collateral and hedge decomposition.','USD total return includes staking, funding/basis, collateral income and derivative marks, less hedge losses, custody/trading costs, fees and impairments. Negative funding can reverse the carry.','sUSDe unstaking returns USDe after its documented cooldown, not ETH. Rewards are discretionary under the current Ethena mechanism. Offchain hedge and collateral liquidity affect cash redemption. Resolv published pre-incident ordinary redemption terms must not be presented as an active exit policy after its March 2026 recovery transition.','Centralized trading/custody counterparties and protocol roles control collateral, hedge and mint/redeem operations. Resolv is paused and in recovery according to current official docs.',['Exchange/custody failure','Hedge liquidation','Negative funding','Basis and collateral mismatch','Mint authorization and recovery restrictions'],'Exchange risk limits, available open interest, collateral liquidity and basis demand. Market size does not imply an ETH-only neutral strategy can absorb all that capital.','Actual funding and collateral income can remain without token rewards, but they are cyclical. Sustainable yield requires realized positive net carry and adequate reserves, not an assumed fixed yield.','Extended USD universe identified. Ethena whole-product discovery value is not an ETH sleeve. Resolv has a documented historical failure/recovery case, but its current ETH collateral and eligible recovery value are unmeasured.',['ethena_overview','ethena_derivatives','ethena_rewards','ethena_staking','ethena_addresses','resolv_collateral','resolv_futures','resolv_fees','resolv_contracts','resolv_recovery','resolv_deprecated'])
product(f,'ethena_susde','Ethena sUSDe','Ethereum / multichain',[],'USD','Large existing discovery product; ETH sleeve remains unmeasured',['ethena_overview','ethena_derivatives','ethena_rewards','ethena_staking','ethena_addresses'],[observation(feed('ethena-usde','SUSDE'),'whole USD staking product, not ETH collateral NAV')],extra={'excludedFromETHPrincipal':True,'primaryProductSources':[url('ethena_overview'),url('ethena_derivatives')],'sourceQualification':'Ethena primary overview and derivative documentation support the dollar-neutral mechanism; current ETH allocation is not measured.'})
product(f,'resolv_recovery','Resolv USR / RLP recovery','Ethereum',[],'USD and recovery rights','Paused / recovery, as described by current official documentation',['resolv_recovery','resolv_contracts','resolv_deprecated'],events=[{'date':'2026-03-22','event':'Official recovery documentation dates the incident and transition to recovery.','sourceURLs':[url('resolv_recovery')]},{'date':'2026-09-26','event':'Extended claims deadline stated in the recovery documentation; it precedes frozen T.','sourceURLs':[url('resolv_recovery')]},{'date':'2025-11-03','event':'TAC USR vault deprecation is separately documented; it is not the same event as the March incident.','sourceURLs':[url('resolv_deprecated')]}],extra={'excludedFromETHPrincipal':True})
# 10. Custodial and securities-based ETH staking access.
f=family('offchain_staking','Exchange and listed-fund staking access',['E1','extended offchain scope'],'WBETH represents Binance-managed ETH staking with an accruing ETH conversion ratio. ETHE and ETH are listed securities holding ETH and participating in staking; the retail holder owns shares rather than an onchain redemption claim.',['Ethereum issuance, priority fees and validator economics'],'ETH long, through custodial receipts or securities. Exchange balances and WBETH backing overlap; fund shares and the ETH they hold are also the same capital at different layers.','WBETH return is ETH conversion-ratio growth after reward commissions. Listed-fund investor total return includes share-price changes and distributions, less fund and staking costs; market discounts or premiums differ from NAV return.','WBETH redemption is quota- and queue-dependent and cannot be cancelled once requested. Retail ETF holders normally sell shares in the market; Authorized Participant creations/redemptions are a separate channel.','Custodian, exchange and sponsor policies replace much of onchain role visibility. Binance reserves discretion to change its reward commission without advance notice. The 2025 ETHE annual filing states a 2.5% annual sponsor fee and aggregate 23% of gross staking rewards for sponsor/custodian/provider; those dated terms are not a fresh October 2026 policy audit.',['Custody and counterparty risk','Withdrawal restrictions','Fund share discount/premium','Staking penalties','Fee drag'],'Exchange quotas, validator exit queues and custody/provider capacity. Fund market depth differs from underlying ETH redemption liquidity.','Native staking earnings do not require promotions. WBETH Flexible Simple Earn does not add a second yield merely because it appears in another product menu. Fees can consume a substantial portion of gross staking return.','Official exchange terms and historical public fund filing reviewed. Product-level current custodial assets and October policy amendments remain outside frozen-T reconstruction.',['binance_wbeth_web','binance_fee_web','grayscale_10k_web'])
product(f,'wbeth','Binance WBETH','Ethereum / BNB Chain',[contract('0xa2e3356610840701bdf5611a53974510ae27e2e1')],'ETH','Current official staking terms reviewed 4 October',['binance_wbeth_web','binance_fee_web'],[observation(feed('binance-staked-eth','WBETH'))],events=[{'date':'2023-04-27','event':'WBETH launch dated in the official support FAQ.','sourceURLs':[url('binance_wbeth_web')]}],extra={'fees':'Official fee FAQ lists a standard 10% staking reward commission for reference, with unilateral changes permitted without advance notice; token conversion/redemption has no separate stated charge.'})
product(f,'grayscale_ethe','Grayscale Ethereum Staking ETF (ETHE)','Offchain / NYSE Arca',[],'USD-priced shares backed by ETH','Staking enabled October 2025; dated filing reviewed 4 October',['grayscale_10k_web'],[{'amountUSD':2703115000,'amountNative':910328.89953386,'unit':'ETH','measuredDate':'2025-12-31','scope':'historical audited filing: net assets in USD (table amounts are thousands), gross investment ETH quantity; not current NAV or all staked ETH','fixedBlockVerified':False,'source':url('grayscale_10k_web'),'additive':False}],events=[{'date':'2025-10-06','event':'Staking began, according to the 2025 annual filing.','sourceURLs':[url('grayscale_10k_web')]},{'date':'2026-01-05','event':'Fund renamed Grayscale Ethereum Staking ETF.','sourceURLs':[url('grayscale_10k_web')]}])
# Evidence inventories and independently dated discovery statistics.
source_rows=[]
for key,row in sorted(bykey.items()):
 source_rows.append({'id':key,**row,'sourceType':'secondary adapter discovery'if key=='euler_monad_adapter'else'primary publisher','fixedBlockFinancialEvidence':False,'scope':row.get('scope','Later official registry/document capture, not a refreshed financial snapshot.')})
source_rows.append({'id':'existing_yield_feed','url':'https://yields.llama.fi/pools','path':str(feedpath.relative_to(ROOT)),'sha256':sha(feedpath),'observedUTC':FEED_DATE,'sourceType':'secondary discovery feed','fixedBlockFinancialEvidence':False,'scope':'Original yield-feed capture, read as a discovery screen; no T financial join.'})
registry=[{'id':x['id'],'chainId':x['chainId'],'market':x['address'],'pt':x['pt']['address'],'yt':x['yt']['address'],'sy':x['sy']['address'],'name':x['pt']['name'],'expiry':x['expiry'],'isActiveAtDiscovery':x.get('isActive'),'categoryIds':x.get('categoryIds',[]),'accountingUnit':x.get('accountingAsset',{}).get('symbol'),'pyUnit':x.get('extendedInfo',{}).get('pyUnit'),'underlyingToken':x.get('underlyingAsset',{}).get('address'),'discoveryLiquidityUSD':x['liquidity']['usd'],'measuredDate':REVIEW,'notFrozenT':True}for x in allmarkets]
knownpt={x['pt']['address'].lower():x for x in allmarkets}
loops=[]
for x in read('pendle_eth_loop_pairs'):
 m=knownpt.get(x['ptAddress'].lower());opts=x.get('info',{}).get('options',[])
 loops.append({'ptAddress':x['ptAddress'],'name':m['pt']['name']if m else None,'categoryIds':m.get('categoryIds',[])if m else[],'isETHFamilyMatch':bool(m and'eth'in m.get('categoryIds',[])),'optionCount':len(opts),'protocols':sorted(set(z.get('protocol')or''for z in opts)),'rawOptions':opts,'measuredDate':REVIEW,'notFrozenT':True})
findings=[
 {'id':'coverage_boundary','title':'Registry coverage and deep product coverage measure different things','text':'The original 85 adapter rows, 5,688 symbol candidates and five deep carry chapters do not establish whole-market product completeness. This expansion adds ten selected families and preserves registry identities, while T capital and historical return coverage remain separate.','sources':[]},
 {'id':'pendle_survivorship','title':'Expired ETH principal-token markets belong in the historical universe','text':f'The captured official Ethereum registry has {len(allmarkets)} unique markets, {len(ethmarkets)} ETH-tagged markets and {len(active)} ETH-tagged active, unexpired markets at the 4 October discovery. Historical entries preserve maturities and identities, not historical peak capital.','sources':urls(['pendle_market_registry','pendle_registry_100','pendle_registry_200','pendle_registry_300','pendle_registry_400'])},
 {'id':'pt_units','title':'PT-stETH is denominated in stETH despite a wstETH feed label','text':'The December 2027 market identifies stETH as its accounting unit while wstETH is the underlying token. A one-unit maturity payoff is not automatically one wstETH. The feed reports the same market liquidity for the PT-buy and LP rows, so summing them would duplicate capital.','sources':urls(['pendle_market_registry'])},
 {'id':'loop_boundary','title':'Published PT looping is not proof of current ETH PT loops','text':f'The official Ethereum looping catalog contains {len(loops)} PT identities. None matches an ETH-tagged market in the full captured registry. These published routes are USD families. ETH loops elsewhere require their own contract and borrowing evidence.','sources':urls(['pendle_eth_loop_pairs','pendle_loop_docs'])},
 {'id':'base_quote','title':'Base APY is a feed classification, not audited organic cash','text':'The K3 Monad WETH row reports 2.69201% total APY, including 1.20737% base and 1.48464% rewards. autoETH reports 2.65708% total, including 2.47077% base and 0.18631% rewards. Incentives-off comparisons retain the distinction between quoted estimates and realized net returns.','sources':['https://yields.llama.fi/pools']},
 {'id':'perp_lp','title':'A perpetual LP earns a total trading payoff, not only a fee yield','text':'GM token value includes net trader PnL and inventory price exposure. The ETH index does not determine the collateral denomination: ETH-USDC, ETH-ETH and USDG-USDG markets have different capital exposure. A hedge is a separate position and is not verified by the GM wrapper itself.','sources':urls(['gmx_market_registry','gmx_liquidity_docs','gmx_performance'])},
 {'id':'recovery','title':'A current yield list hides retired and impaired products','text':'The official Yearn interface identifies yETH as retired and recovery-only. Resolv documents a March 2026 incident and recovery process. These are different failure cases, with different eligibility and cash rights; neither can be represented by an ordinary current APY.','sources':urls(['yearn_incident','yearn_recovery_app','resolv_recovery'])},
 {'id':'options_materiality','title':'ETH options have proven historical capacity; current capacity still needs proof','text':'Ribbon documented a full 10,000 ETH call cap during its 2021 incentive program. Thetanuts publishes ETH call contract identities across Ethereum, Arbitrum and Mantle. The latter catalog alone does not establish active auctions, balances or material current ETH capacity.','sources':urls(['ribbon_retro','thetanuts_registry'])},
 {'id':'offchain','title':'Listed and custodial staking can be large without adding a new payer','text':'WBETH and staking ETFs ultimately earn Ethereum validator rewards. Their distinctive risks lie in custody, charges, share pricing and exit access. Receipt layers and the ETH backing must be netted before combining them with onchain products.','sources':urls(['binance_wbeth_web','binance_fee_web','grayscale_10k_web'])}
]
summary={'familyCount':len(families),'selectedProductCount':len(products),'primaryRegistryEthereumMarkets':len(allmarkets),'ethTaggedRegistryMarkets':len(ethmarkets),'activeUnexpiredETHTaggedRegistryMarkets':len(active),'publishedEthereumPTLoopProducts':len(loops),'ethTaggedPublishedPTLoopMatches':sum(x['isETHFamilyMatch']for x in loops),'financialMarketCoverageStatus':'unknown','fixedTProductFinancialJoinsAdded':0,'discoverySelection':'$5 million current discovery value or $20 million historical value, with separately flagged native-unit historical evidence and unquantified contract/recovery boundary cases','aggregation':'No values are summed as a new unique ETH market total. Discovery pool value, wrapper accounting, historical NAV and USD-only products use different denominators.'}
d={'schemaVersion':1,'snapshot':{'timestamp':T,'ethereumBlock':26108081,'financialSnapshotUnchanged':True},'discoveryDate':REVIEW,'discoveryFeedDate':FEED_DATE,'summary':summary,'findings':findings,'families':families,'products':products,'sources':source_rows,'registryCoverage':{'pendleEthereum':{'recordCount':len(registry),'uniqueMarketCount':len(set(x['market'].lower()for x in registry)),'registryFile':'data/eth/strategy_universe_expansion_pendle_registry.json','loopCatalogFile':'data/eth/strategy_universe_expansion_pendle_loops.json','otherChainsComplete':False}},'reproduction':{'command':'python3 tools/eth/strategy_universe_expansion_build.py','captureCommand':'python3 tools/eth/strategy_universe_expansion_capture.py seeds; python3 tools/eth/strategy_universe_expansion_capture.py follow','manifest':'data/eth/strategy_universe_expansion_manifest.json'}}
write(OUT,d);write(ROOT/'data/eth/strategy_universe_expansion_pendle_registry.json',registry);write(ROOT/'data/eth/strategy_universe_expansion_pendle_loops.json',loops)
inputs=[ROOT/x['path']for x in source_rows]+[ROOT/'tools/eth/strategy_universe_expansion_build.py',RAW/'capture_manifest.jsonl']
manifest={'schemaVersion':1,'snapshot':T,'reviewDate':REVIEW,'inputs':[{'path':str(p.relative_to(ROOT)),'sha256':sha(p),'bytes':p.stat().st_size}for p in sorted(set(inputs))],'failedOrNonContentCaptures':[r for r in records if not content_ok(r)],'outputs':[{'path':str(p.relative_to(ROOT)),'sha256':sha(p),'bytes':p.stat().st_size}for p in[OUT,ROOT/'data/eth/strategy_universe_expansion_pendle_registry.json',ROOT/'data/eth/strategy_universe_expansion_pendle_loops.json']]}
write(ROOT/'data/eth/strategy_universe_expansion_manifest.json',manifest)
assert len(allmarkets)==494 and len(set(x['address'].lower()for x in allmarkets))==494
assert len(ethmarkets)==117 and len(active)==4 and len(loops)==15 and not any(x['isETHFamilyMatch']for x in loops)
assert len(families)==10 and len(set(x['id']for x in products))==len(products)
for f in families:
 for k in ['mechanic','payers','ETHexposure','returnBasis','exitTerms','controls','risks','capacity','incentivesOff','coverageStatus','sources']:assert f[k],(f['id'],k)
for p in products:
 for c in p['contracts']:assert re.fullmatch(r'0x[0-9a-f]{40}',c['address']),(p['id'],c)
 for o in p['quantitativeObservations']:assert o['fixedBlockVerified']is False and o['measuredDate']!=T
print(json.dumps(summary));print('Output SHA256',sha(OUT))
